import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUnapprovedSource1790300000000 implements MigrationInterface {
  name = "AddUnapprovedSource1790300000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TYPE "public"."user_contexts_source_enum" ADD VALUE IF NOT EXISTS 'UNAPPROVED'`,
    );

    await queryRunner.query(
      `UPDATE "user_contexts"
       SET "source" = 'UNAPPROVED'
       WHERE "contextKey" = 'Q_AND_A'
         AND "source" = 'AUTOGENERATED'`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `UPDATE "user_contexts"
       SET "source" = 'AUTOGENERATED'
       WHERE "contextKey" = 'Q_AND_A'
         AND "source" = 'UNAPPROVED'`,
    );
  }
}
