import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * First-class category families: a `category_families` table plus a `familyId`
 * foreign key on `user_contexts` (meaningful only for EMAIL_CATEGORY rows).
 * Families group the fine-grained categories for the inbox hierarchy. They are
 * seeded from the keyword taxonomy after this migration and are user-editable.
 */
export class CreateCategoryFamilies1794600000000 implements MigrationInterface {
  name = "CreateCategoryFamilies1794600000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "category_families" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "userId" uuid NOT NULL,
        "name" text NOT NULL,
        "displayOrder" integer NOT NULL DEFAULT 0,
        "source" "user_contexts_source_enum" NOT NULL DEFAULT 'AUTOGENERATED',
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "PK_category_families" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_category_families_userId" ON "category_families" ("userId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "category_families" ADD CONSTRAINT "FK_category_families_user" ` +
        `FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE`,
    );

    await queryRunner.query(
      `ALTER TABLE "user_contexts" ADD COLUMN IF NOT EXISTS "familyId" uuid`,
    );
    // ON DELETE SET NULL: deleting a family leaves its categories unassigned
    // (they fall back to "Other / Uncategorised"), it does not delete them.
    await queryRunner.query(
      `ALTER TABLE "user_contexts" ADD CONSTRAINT "FK_user_contexts_family" ` +
        `FOREIGN KEY ("familyId") REFERENCES "category_families"("id") ON DELETE SET NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_user_contexts_familyId" ON "user_contexts" ("familyId")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "user_contexts" DROP CONSTRAINT IF EXISTS "FK_user_contexts_family"`,
    );
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_user_contexts_familyId"`);
    await queryRunner.query(
      `ALTER TABLE "user_contexts" DROP COLUMN IF EXISTS "familyId"`,
    );
    await queryRunner.query(
      `ALTER TABLE "category_families" DROP CONSTRAINT IF EXISTS "FK_category_families_user"`,
    );
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_category_families_userId"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "category_families"`);
  }
}
