/**
 * Category rules accordion — inline rules shown beneath an EMAIL_CATEGORY context item.
 *
 * Stories cover:
 *  1. "Add matching rule" state (no rules exist for the category yet)
 *  2. "{n} rules" expanded state (rules are present and the accordion is open)
 *
 * The real ContextSection component is used — no fake JSX.
 * The CategoryRuleFromCategoryContext is provided via a mock so the
 * accordion actions (add/edit/delete/toggle) are wired up.
 */
import React, { useState } from 'react';
import { I18nextProvider } from 'react-i18next';
import type { Meta, StoryObj } from '@storybook/react';
import i18n from 'i18n';
import type { CategoryRuleDto } from 'types/category-rules.types';

import { ContextSection } from 'components/settings/guide-ai/ContextSection';
import { CONTEXT_SOURCE_AUTOGENERATED } from 'constants/strings';
import type { CategoryRuleFromCategoryContextValue } from 'contexts/CategoryRuleFromCategoryContext';
import { CategoryRuleFromCategoryContext } from 'contexts/CategoryRuleFromCategoryContext';

// ---------------------------------------------------------------------------
// Mock data
// ---------------------------------------------------------------------------

const MOCK_CATEGORY_CONTEXT = [
  {
    contextId: 'ctx-newsletters',
    contextKey: 'EMAIL_CATEGORY',
    contextValue: 'Newsletters',
    source: CONTEXT_SOURCE_AUTOGENERATED,
    explanation: 'Marketing digests and product update emails',
  },
];

const MOCK_RULES: CategoryRuleDto[] = [
  {
    id: 'rule-1',
    categoryName: 'Newsletters',
    categoryId: 'cat-newsletters',
    ruleKind: 'composite',
    ruleType: null,
    pattern: '',
    subjectPrefix: null,
    compositeSpec: {
      v: 2,
      senderMatchesAny: ['@substack.com', '@newsletter.'],
      subjectContainsAny: ['weekly digest', 'monthly roundup'],
      bodyContainsAny: ['unsubscribe'],
    },
    isEnabled: true,
    hitCount: 42,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'rule-2',
    categoryName: 'Newsletters',
    categoryId: 'cat-newsletters',
    ruleKind: 'legacy',
    ruleType: 'sender_domain',
    pattern: 'mailchimp.com',
    subjectPrefix: null,
    compositeSpec: null,
    isEnabled: true,
    hitCount: 17,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const Wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <I18nextProvider i18n={i18n}>
    <div style={{ maxWidth: 720, margin: '0 auto' }}>{children}</div>
  </I18nextProvider>
);

/**
 * Wraps ContextSection with a CategoryRuleFromCategoryContext so the real
 * component can look up rules and open the add/edit flow.
 */
const CategoryRulesAccordionDemo: React.FC<{
  initialRules: CategoryRuleDto[];
}> = ({ initialRules }) => {
  const [rules, setRules] = useState<CategoryRuleDto[]>(initialRules);
  const [addingContextType, setAddingContextType] = useState<string | null>(null);
  const [editingContextId, setEditingContextId] = useState<string | null>(null);
  const [editContextValue, setEditContextValue] = useState('');
  const [newContextValue, setNewContextValue] = useState('');

  const contextValue: CategoryRuleFromCategoryContextValue = {
    rules,
    openAddRuleForCategoryDisplayName: (displayName: string) => {
       
      console.info('[Storybook] openAddRuleForCategoryDisplayName', displayName);
    },
    onToggleEnabled: (id: string, nextEnabled: boolean) => {
      setRules(prev => prev.map(rule => (rule.id === id ? { ...rule, isEnabled: nextEnabled } : rule)));
    },
    onDeleteRule: async (id: string) => {
      setRules(prev => prev.filter(rule => rule.id !== id));
    },
    onEditRule: (rule: CategoryRuleDto) => {
       
      console.info('[Storybook] onEditRule', rule);
    },
  };

  return (
    <CategoryRuleFromCategoryContext.Provider value={contextValue}>
      <ContextSection
        title="Newsletters"
        contextKey="EMAIL_CATEGORY"
        contexts={MOCK_CATEGORY_CONTEXT}
        addLabel="Add email category"
        addingContextType={addingContextType}
        editingContextId={editingContextId}
        editContextValue={editContextValue}
        newContextValue={newContextValue}
        onAddContext={async () => {}}
        onUpdateContext={async () => {}}
        onDeleteContext={() => {}}
        onNewContextValueChange={setNewContextValue}
        onAddingContextTypeChange={setAddingContextType}
        onEditingContextIdChange={setEditingContextId}
        onEditContextValueChange={setEditContextValue}
        isInitiallyExpanded
      />
    </CategoryRuleFromCategoryContext.Provider>
  );
};

// ---------------------------------------------------------------------------
// Meta
// ---------------------------------------------------------------------------

const meta: Meta<typeof ContextSection> = {
  title: 'Settings/GuideAI/CategoryRulesAccordion',
  component: ContextSection,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'Inline category rules accordion shown beneath an EMAIL_CATEGORY context item (PR #1658). ' +
          'Two key states: (1) no rules — shows "Add matching rule" button; ' +
          '(2) rules present — shows "{n} rules" toggle that expands the inline accordion.',
      },
    },
  },
};

export default meta;
type Story = StoryObj<typeof ContextSection>;

// ---------------------------------------------------------------------------
// Stories
// ---------------------------------------------------------------------------

/**
 * State 1: No rules for the category yet.
 * The "Add matching rule" button is shown inline next to the category name.
 */
export const AddMatchingRuleState: Story = {
  name: 'State: Add matching rule (no rules yet)',
  render: () => (
    <Wrapper>
      <CategoryRulesAccordionDemo initialRules={[]} />
    </Wrapper>
  ),
};

/**
 * State 2: Rules already exist; accordion is expanded showing all rules plus
 * the inline "+ Add matching rule" button at the bottom.
 */
export const ExpandedRulesState: Story = {
  name: 'State: {n} rules — accordion expanded',
  render: () => (
    <Wrapper>
      <CategoryRulesAccordionDemo initialRules={MOCK_RULES} />
    </Wrapper>
  ),
};
