/**
 * Guide AI → Email categories (UserContext EMAIL_CATEGORY): learned category names
 * the model uses for inbox grouping — not the same as deterministic `/category-rules`.
 *
 * For static screenshots: `cd client && npm run build-storybook`, open `storybook-static/index.html`.
 */
import React, { useState } from 'react';
import { I18nextProvider, useTranslation } from 'react-i18next';
import type { Meta, StoryObj } from '@storybook/react';
import i18n from 'i18n';

import { ContextSection } from 'components/settings/guide-ai/ContextSection';
import { CONTEXT_SOURCE_AUTOGENERATED, CONTEXT_SOURCE_USER_EDITED } from 'constants/strings';

const meta: Meta<typeof ContextSection> = {
  title: 'Settings/GuideAI/ContextEmailCategories',
  component: ContextSection,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'Learned email category names under Guide our AI (context). Deterministic matching rules are documented under Settings/CategoryRules/DeterministicRules.',
      },
    },
  },
};

export default meta;
type Story = StoryObj<typeof ContextSection>;

type UserContextRow = {
  contextId: string;
  contextKey: string;
  contextValue: string;
  source: string;
  explanation?: string;
};

const MOCK_CATEGORIES: UserContextRow[] = [
  {
    contextId: 'cat-work',
    contextKey: 'EMAIL_CATEGORY',
    contextValue: 'Work / Engineering',
    source: CONTEXT_SOURCE_AUTOGENERATED,
    explanation: 'Threads about sprints, code review, and internal tooling',
  },
  {
    contextId: 'cat-finance',
    contextKey: 'EMAIL_CATEGORY',
    contextValue: 'Finance & receipts',
    source: CONTEXT_SOURCE_USER_EDITED,
    explanation: 'Invoices, expenses, and subscription billing',
  },
  {
    contextId: 'cat-personal',
    contextKey: 'EMAIL_CATEGORY',
    contextValue: 'Personal',
    source: CONTEXT_SOURCE_AUTOGENERATED,
    explanation: 'Friends, family, and non-work plans',
  },
];

const MOCK_LONG_RULE: UserContextRow[] = [
  {
    contextId: 'cat-long',
    contextKey: 'EMAIL_CATEGORY',
    contextValue:
      'Vendor procurement — RFPs, security questionnaires, MSAs, and anything that needs legal or security review before we can sign or renew',
    source: CONTEXT_SOURCE_USER_EDITED,
    explanation:
      'Learned from threads mentioning procurement, vendor onboarding, data processing agreements, or renewal dates with external suppliers',
  },
];

const Wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <I18nextProvider i18n={i18n}>
    <div style={{ maxWidth: 720, margin: '0 auto' }}>{children}</div>
  </I18nextProvider>
);

const InteractiveEmailCategorySection: React.FC<{
  initialContexts: UserContextRow[];
  initialEditingId?: string | null;
  initialAdding?: boolean;
  isInitiallyExpanded?: boolean;
}> = ({ initialContexts, initialEditingId = null, initialAdding = false, isInitiallyExpanded = true }) => {
  const { t } = useTranslation();
  const [contexts, setContexts] = useState<UserContextRow[]>(initialContexts);
  const [addingContextType, setAddingContextType] = useState<string | null>(initialAdding ? 'EMAIL_CATEGORY' : null);
  const [editingContextId, setEditingContextId] = useState<string | null>(initialEditingId);
  const [editContextValue, setEditContextValue] = useState(() => {
    if (initialEditingId) {
      return initialContexts.find(row => row.contextId === initialEditingId)?.contextValue ?? '';
    }
    return '';
  });
  const [newContextValue, setNewContextValue] = useState('');

  const onAddContext = async () => {
    const trimmed = newContextValue.trim();
    if (!trimmed) {
      return;
    }
    setContexts(prev => [
      ...prev,
      {
        contextId: `new-${Date.now()}`,
        contextKey: 'EMAIL_CATEGORY',
        contextValue: trimmed,
        source: CONTEXT_SOURCE_USER_EDITED,
        explanation: '',
      },
    ]);
    setNewContextValue('');
    setAddingContextType(null);
  };

  const onUpdateContext = async () => {
    const trimmed = editContextValue.trim();
    if (!trimmed || !editingContextId) {
      return;
    }
    setContexts(prev =>
      prev.map(row =>
        row.contextId === editingContextId ? { ...row, contextValue: trimmed, source: CONTEXT_SOURCE_USER_EDITED } : row
      )
    );
    setEditingContextId(null);
    setEditContextValue('');
  };

  const onDeleteContext = (contextId: string) => {
    setContexts(prev => prev.filter(row => row.contextId !== contextId));
    if (editingContextId === contextId) {
      setEditingContextId(null);
      setEditContextValue('');
    }
  };

  return (
    <ContextSection
      title={t('settings.contextSections.emailCategories')}
      contextKey="EMAIL_CATEGORY"
      contexts={contexts}
      addLabel={t('settings.addContext.emailCategories')}
      tooltipContent={t('settings.contextTypes.tooltip.emailCategories')}
      addingContextType={addingContextType}
      editingContextId={editingContextId}
      editContextValue={editContextValue}
      newContextValue={newContextValue}
      onAddContext={onAddContext}
      onUpdateContext={onUpdateContext}
      onDeleteContext={onDeleteContext}
      onNewContextValueChange={setNewContextValue}
      onAddingContextTypeChange={setAddingContextType}
      onEditingContextIdChange={setEditingContextId}
      onEditContextValueChange={setEditContextValue}
      isInitiallyExpanded={isInitiallyExpanded}
    />
  );
};

export const DefaultRulesList: Story = {
  render: () => (
    <Wrapper>
      <InteractiveEmailCategorySection initialContexts={MOCK_CATEGORIES} />
    </Wrapper>
  ),
};

export const EmptyAddCategory: Story = {
  render: () => (
    <Wrapper>
      <InteractiveEmailCategorySection initialContexts={[]} initialAdding />
    </Wrapper>
  ),
};

export const EditingCategoryName: Story = {
  render: () => (
    <Wrapper>
      <InteractiveEmailCategorySection initialContexts={MOCK_CATEGORIES} initialEditingId="cat-finance" />
    </Wrapper>
  ),
};

export const LongCategoryWithTruncation: Story = {
  render: () => (
    <Wrapper>
      <InteractiveEmailCategorySection initialContexts={MOCK_LONG_RULE} />
    </Wrapper>
  ),
};

export const CollapsedSection: Story = {
  render: () => (
    <Wrapper>
      <InteractiveEmailCategorySection initialContexts={MOCK_CATEGORIES} isInitiallyExpanded={false} />
    </Wrapper>
  ),
};
