/**
 * QAndASection — Approved/Pending Review Tabs (Issue #1521 Phase 4)
 *
 * Demonstrates the Q&A section with two tabs:
 * - Pending Review: unapproved auto-extracted Q&A with approve/reject/edit actions
 * - Approved: user-approved Q&A with edit/delete actions
 */
import React, { useState } from 'react';
import { I18nextProvider } from 'react-i18next';
import type { Meta, StoryObj } from '@storybook/react';
import i18n from 'i18n';

import { QAndASection } from 'components/settings/guide-ai/QAndASection';

const meta: Meta<typeof QAndASection> = {
  title: 'Settings/GuideAI/QAndASection',
  component: QAndASection,
  parameters: {
    layout: 'padded',
  },
};

export default meta;
type Story = StoryObj<typeof QAndASection>;

const MOCK_PENDING = [
  {
    contextId: 'pending-1',
    contextKey: 'Q_AND_A',
    contextValue: 'Q: What is your return policy? | A: We offer 30-day returns on all items.',
    source: 'UNAPPROVED',
    explanation: 'Appeared 5 times in your replies',
  },
  {
    contextId: 'pending-2',
    contextKey: 'Q_AND_A',
    contextValue: 'Q: Do you offer discounts for bulk orders? | A: Yes, contact sales for bulk pricing.',
    source: 'UNAPPROVED',
    explanation: 'Appeared 3 times in your replies',
  },
  {
    contextId: 'pending-3',
    contextKey: 'Q_AND_A',
    contextValue: 'Q: What are your business hours? | A: We are open Monday to Friday, 9am to 5pm.',
    source: 'UNAPPROVED',
    explanation: 'Appeared 4 times in your replies',
  },
];

const MOCK_APPROVED = [
  {
    contextId: 'approved-1',
    contextKey: 'Q_AND_A',
    contextValue: 'Q: How do I reset my password? | A: Click "Forgot Password" on the login page.',
    source: 'AUTOGENERATED',
    explanation: '',
  },
  {
    contextId: 'approved-2',
    contextKey: 'Q_AND_A',
    contextValue: 'Q: Where is the documentation? | A: Check docs.example.com for full documentation.',
    source: 'USER_EDITED',
    explanation: '',
  },
];

const MOCK_OTHER = [
  {
    contextId: 'other-1',
    contextKey: 'VIP_CONTACT',
    contextValue: 'John Doe',
    source: 'USER_EDITED',
    explanation: '',
  },
];

const Wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <I18nextProvider i18n={i18n}>
    <div style={{ maxWidth: 700, margin: '0 auto' }}>{children}</div>
  </I18nextProvider>
);

const noop = async () => {};
const noopSync = () => {};

const InteractiveQAndASection: React.FC<{
  initialContexts: React.ComponentProps<typeof QAndASection>['contexts'];
}> = ({ initialContexts }) => {
  const [addingContextType, setAddingContextType] = useState<string | null>(null);
  const [editingContextId, setEditingContextId] = useState<string | null>(null);
  const [editContextValue, setEditContextValue] = useState('');
  const [newContextValue, setNewContextValue] = useState('');

  return (
    <QAndASection
      contexts={initialContexts}
      addingContextType={addingContextType}
      editingContextId={editingContextId}
      editContextValue={editContextValue}
      newContextValue={newContextValue}
      onAddContext={noop}
      onUpdateContext={noop}
      onDeleteContext={noopSync}
      onNewContextValueChange={setNewContextValue}
      onAddingContextTypeChange={setAddingContextType}
      onEditingContextIdChange={setEditingContextId}
      onEditContextValueChange={setEditContextValue}
      onRefresh={() => console.log('Refresh called')}
      isInitiallyExpanded
      tooltipContent="Common questions and answers that the auto-responder can use"
    />
  );
};

export const WithPendingAndApproved: Story = {
  render: () => (
    <Wrapper>
      <InteractiveQAndASection initialContexts={[...MOCK_PENDING, ...MOCK_APPROVED, ...MOCK_OTHER]} />
    </Wrapper>
  ),
};

export const PendingOnly: Story = {
  render: () => (
    <Wrapper>
      <InteractiveQAndASection initialContexts={[...MOCK_PENDING, ...MOCK_OTHER]} />
    </Wrapper>
  ),
};

export const ApprovedOnly: Story = {
  render: () => (
    <Wrapper>
      <InteractiveQAndASection initialContexts={[...MOCK_APPROVED, ...MOCK_OTHER]} />
    </Wrapper>
  ),
};

export const Empty: Story = {
  render: () => (
    <Wrapper>
      <InteractiveQAndASection initialContexts={[]} />
    </Wrapper>
  ),
};
