/**
 * Query limit constants
 * Use these instead of magic numbers for database and API query limits
 */

/**
 * Inbox mode constants
 * Use these instead of magic strings for inbox mode comparisons
 */
export const INBOX_MODES = {
  TRIAGE: "triage",
  ACTION: "action",
  FOLLOW_UP: "follow-up",
} as const;

export type InboxMode = (typeof INBOX_MODES)[keyof typeof INBOX_MODES];

export const QUERY_LIMITS = {
  INBOX_TOTAL: 500,
  INBOX_PROCESS_TOTAL: 1000,
  THREAD_QUERY: 100,
  EMAIL_QUERY: 100,
  MAX_CONTACTS: 5000,
  MAX_SENT_EMAILS: 150,
  MAX_SENT_EMAILS_FOR_STYLE: 50,
  MAX_THREADS_FOR_ANALYSIS: 200,
  MAX_ISSUES_SEARCH: 30,
  MAX_RESULTS_DEFAULT: 20,
  MAX_RESULTS_MULTIPLIER: 2,
  CONTACTS_SEARCH_LIMIT: 50,
  CONTACTS_SEARCH_OFFSET: 20,
  CONTACTS_PAGE_SIZE: 20,
  SEARCH_INDEX_TRIGRAM_PAD: 16,
  SUBSTRING_PREVIEW_LENGTH: 50,
  SUBSTRING_PREVIEW_LONG: 150,
  SUBSTRING_BODY_PREVIEW: 500,
  SUBSTRING_SUBJECT_SHORT: 30,
  SUBSTRING_SNIPPET_LENGTH: 200,
  SUBSTRING_EXPLANATION_MAX: 100,
  SUBSTRING_EXPLANATION_TRUNCATE: 97,
  THREAD_ID_PREVIEW: 12,
  LLM_MAX_TOKENS: 500,
  LLM_TEMPERATURE: 0.3,
  LLM_CHUNK_SIZE: 8,
  LLM_CONTEXT_WINDOW: 2048,
  LLM_SENT_EMAILS_LIMIT: 30,
  LLM_QUICK_REPLY_MINUTES: 30,
  THREAD_ID_SHORT: 8,
  PRIORITY_LEARNING_SAMPLE_SIZE: 50,
  PRIORITY_LEARNING_MIN_SAMPLES: 15,
  PRIORITY_LEARNING_MAX_SAMPLES: 20,
  LLM_MAX_TOKENS_LARGE: 1500,
  LLM_MAX_TOKENS_MEDIUM: 1000,
  LLM_MAX_TOKENS_SMALL: 500,
  LLM_MAX_TOKENS_TINY: 400,
  LLM_MAX_TOKENS_EXPLANATION: 200,
  LLM_BODY_PREVIEW_LENGTH: 2000,
  LLM_MAX_TOKENS_VERY_SMALL: 150,
  LLM_REASONING_MAX_LENGTH: 200,
  LLM_BATCH_EXPLANATION_BASE: 2000,
  LLM_BATCH_EXPLANATION_PER_EMAIL: 200,
  SUBJECT_WORDS_TOP_COUNT: 10,
} as const;
