// This file was previously generated by Create React App and contained:
//   /// <reference types="react-scripts" />
//
// That directive has been removed as part of the CRA → Vite migration cleanup (Issue #941).
// Vite type references are provided by vite-env.d.ts (/// <reference types="vite/client" />).
// Do not re-add the react-scripts reference — it pulls in CRA ambient globals that are
// incompatible with a Vite project and can mask missing React imports at compile time.
