import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import axios from 'axios';

import { CategoryFamiliesSection } from './CategoryFamiliesSection';

vi.mock('axios');
const mockedAxios = axios as jest.Mocked<typeof axios>;

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, params?: Record<string, unknown>) =>
      params ? `${key}:${JSON.stringify(params)}` : key,
  }),
}));

const FAMILIES = [
  {
    id: 'fam-1',
    name: 'GitHub / Pull Requests',
    displayOrder: 0,
    source: 'AUTOGENERATED',
    categories: [{ contextId: 'c1', name: '🔧 GitHub PR Updates' }],
  },
  {
    id: null,
    name: 'Other / Uncategorised',
    displayOrder: 999,
    source: 'AUTOGENERATED',
    categories: [{ contextId: 'c2', name: 'Newsletters' }],
  },
];

describe('CategoryFamiliesSection', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockedAxios.get.mockResolvedValue({ data: FAMILIES });
    mockedAxios.patch.mockResolvedValue({ data: {} });
    mockedAxios.post.mockResolvedValue({ data: {} });
  });

  it('loads and renders families with their categories', async () => {
    render(<CategoryFamiliesSection />);
    expect(await screen.findByText('🔧 GitHub PR Updates')).toBeInTheDocument();
    expect(screen.getByText('Newsletters')).toBeInTheDocument();
    expect(mockedAxios.get).toHaveBeenCalledWith(expect.stringContaining('/category-families'));
  });

  it('reassigns a category to another family via the dropdown', async () => {
    render(<CategoryFamiliesSection />);
    await screen.findByText('Newsletters');

    // The "Newsletters" category sits in the Other group; move it to fam-1.
    const selects = screen.getAllByLabelText('settings.categoryFamilies.moveCategoryLabel');
    // second select belongs to the Other group's category
    await userEvent.selectOptions(selects[1], 'fam-1');

    await waitFor(() =>
      expect(mockedAxios.patch).toHaveBeenCalledWith(
        expect.stringContaining('/category-families/categories/c2'),
        { familyId: 'fam-1' },
      ),
    );
  });

  it('creates a new family', async () => {
    render(<CategoryFamiliesSection />);
    await screen.findByText('🔧 GitHub PR Updates');

    await userEvent.type(
      screen.getByLabelText('settings.categoryFamilies.newFamilyLabel'),
      'My Family',
    );
    await userEvent.click(screen.getByText('settings.categoryFamilies.create'));

    await waitFor(() =>
      expect(mockedAxios.post).toHaveBeenCalledWith(
        expect.stringContaining('/category-families'),
        { name: 'My Family' },
      ),
    );
  });
});
