import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { theme } from 'theme/theme';
import { InfoTooltip } from 'components/InfoTooltip';
import { OPACITY_DISABLED, OPACITY_FULL } from 'constants/numbers';
import { CONTEXT_KEY_Q_AND_A, CONTEXT_SOURCE_AUTOGENERATED, CONTEXT_SOURCE_USER_EDITED, CONTEXT_EXPLANATION_VIP_CONTACT_STARRED, KEY_ENTER, KEY_ESCAPE } from 'constants/strings';
import { captureEvent } from 'utils/posthog';

const TRUNCATE_LENGTH = 100; // Characters before truncation

interface UserContext {
  contextId: string;
  contextKey: string;
  contextValue: string;
  source: string;
  priority?: number;
  explanation?: string;
  sourceThreadIds?: string[];
}

interface ContextSectionProps {
  title: string;
  contextKey: string | string[];
  contexts: UserContext[];
  addLabel: string;
  tooltipContent?: string;
  actionButton?: React.ReactNode;
  addingContextType: string | null;
  editingContextId: string | null;
  editContextValue: string;
  newContextValue: string;
  onAddContext: () => Promise<void>;
  onUpdateContext: () => Promise<void>;
  onDeleteContext: (contextId: string) => void;
  onNewContextValueChange: (value: string) => void;
  onAddingContextTypeChange: (type: string | null) => void;
  onEditingContextIdChange: (id: string | null) => void;
  onEditContextValueChange: (value: string) => void;
}

export const ContextSection: React.FC<ContextSectionProps> = ({
  title,
  contextKey,
  contexts,
  addLabel,
  tooltipContent,
  actionButton,
  addingContextType,
  editingContextId,
  editContextValue,
  newContextValue,
  onAddContext,
  onUpdateContext,
  onDeleteContext,
  onNewContextValueChange,
  onAddingContextTypeChange,
  onEditingContextIdChange,
  onEditContextValueChange,
}) => {
  const { t } = useTranslation();
  const keys = Array.isArray(contextKey) ? contextKey : [contextKey];
  const filteredContexts = contexts.filter(c => keys.includes(c.contextKey));
  const addType = keys[0];

  return (
    <div style={{ marginBottom: theme.spacing.lg }}>
      <h3 style={{ 
        fontSize: theme.typography.fontSize.lg, 
        color: theme.colors.text.primary,
        marginBottom: theme.spacing.sm,
        borderBottom: `1px solid ${theme.colors.border.light}`,
        paddingBottom: theme.spacing.xs,
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing.xs
      }}>
        {title}
        {tooltipContent && <InfoTooltip content={tooltipContent} />}
        {actionButton}
      </h3>
      
      <div style={{ display: 'flex', flexDirection: 'column', gap: theme.spacing.sm }}>
        {filteredContexts.length > 0 ? (
          filteredContexts.map(context => (
            <ContextItem
              key={context.contextId}
              context={context}
              editingContextId={editingContextId}
              editContextValue={editContextValue}
              onUpdateContext={onUpdateContext}
              onEditingContextIdChange={onEditingContextIdChange}
              onEditContextValueChange={onEditContextValueChange}
              onDeleteContext={onDeleteContext}
            />
          ))
        ) : (
          <div style={{ color: theme.colors.text.tertiary, fontSize: theme.typography.fontSize.sm, fontStyle: 'italic' }}>
            {t('settings.context.noItems')}
          </div>
        )}

        {addingContextType === addType ? (
          <ContextAddInput
            newContextValue={newContextValue}
            onNewContextValueChange={onNewContextValueChange}
            onAddContext={onAddContext}
            onCancel={() => {
              onAddingContextTypeChange(null);
              onNewContextValueChange('');
            }}
          />
        ) : (
          <button
            onClick={() => {
              onAddingContextTypeChange(addType);
              onNewContextValueChange('');
            }}
            style={{
              alignSelf: 'flex-start',
              marginTop: theme.spacing.xs,
              background: 'transparent',
              border: `1px dashed ${theme.colors.border.medium}`,
              borderRadius: theme.borderRadius.md,
              padding: `${theme.spacing.xs} ${theme.spacing.md}`,
              color: theme.colors.text.secondary,
              cursor: 'pointer',
              fontSize: theme.typography.fontSize.sm,
              display: 'flex',
              alignItems: 'center',
              gap: theme.spacing.xs
            }}
          >
            <span>+</span> {addLabel}
          </button>
        )}
      </div>
    </div>
  );
};

interface ContextItemProps {
  context: UserContext;
  editingContextId: string | null;
  editContextValue: string;
  onUpdateContext: () => Promise<void>;
  onEditingContextIdChange: (id: string | null) => void;
  onEditContextValueChange: (value: string) => void;
  onDeleteContext: (contextId: string) => void;
}

const ContextItem: React.FC<ContextItemProps> = ({
  context,
  editingContextId,
  editContextValue,
  onUpdateContext,
  onEditingContextIdChange,
  onEditContextValueChange,
  onDeleteContext,
}) => {
  const { t } = useTranslation();

  if (editingContextId === context.contextId) {
    return (
      <div style={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center',
        padding: theme.spacing.sm,
        backgroundColor: theme.colors.background.subtle,
        borderRadius: theme.borderRadius.md,
        border: `1px solid ${theme.colors.border.light}`
      }}>
        <div style={{ display: 'flex', flex: 1, gap: theme.spacing.sm }}>
          <input
            type="text"
            value={editContextValue}
            onChange={(e) => onEditContextValueChange(e.target.value)}
            style={{
              flex: 1,
              padding: theme.spacing.xs,
              borderRadius: theme.borderRadius.sm,
              border: `1px solid ${theme.colors.border.medium}`
            }}
          />
          <button onClick={onUpdateContext} style={{ cursor: 'pointer', color: theme.colors.primary.main, border: 'none', background: 'none' }}>{t('common.save')}</button>
          <button onClick={() => onEditingContextIdChange(null)} style={{ cursor: 'pointer', color: theme.colors.text.secondary, border: 'none', background: 'none' }}>{t('common.cancel')}</button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ 
      display: 'flex', 
      justifyContent: 'space-between', 
      alignItems: 'center',
      padding: theme.spacing.sm,
      backgroundColor: theme.colors.background.subtle,
      borderRadius: theme.borderRadius.md,
      border: `1px solid ${theme.colors.border.light}`
    }}>
      <ContextItemContent context={context} />
      <div style={{ display: 'flex', gap: theme.spacing.sm }}>
        <button 
          onClick={() => {
            captureEvent('context_edit_clicked', { context_key: context.contextKey });
            onEditingContextIdChange(context.contextId);
            onEditContextValueChange(context.contextValue);
          }}
          style={{ cursor: 'pointer', color: theme.colors.primary.main, border: 'none', background: 'none', fontSize: theme.typography.fontSize.sm }}
        >
          {t('common.edit')}
        </button>
        <button 
          onClick={() => {
            captureEvent('context_deleted', { context_key: context.contextKey });
            onDeleteContext(context.contextId);
          }}
          style={{ cursor: 'pointer', color: theme.colors.accent.error, border: 'none', background: 'none', fontSize: theme.typography.fontSize.sm }}
        >
          {t('common.delete')}
        </button>
      </div>
    </div>
  );
};

interface ContextItemContentProps {
  context: UserContext;
}

const ContextItemContent: React.FC<ContextItemContentProps> = ({ context }) => {
  const { t } = useTranslation();
  const [isExpanded, setIsExpanded] = useState(false);
  
  const shouldTruncate = context.contextValue.length > TRUNCATE_LENGTH;
  const displayValue = shouldTruncate && !isExpanded 
    ? context.contextValue.substring(0, TRUNCATE_LENGTH) + '...'
    : context.contextValue;

  return (
    <div style={{ flex: 1 }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: theme.spacing.xs }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: theme.spacing.sm, flexWrap: 'wrap' }}>
          {context.contextKey === CONTEXT_KEY_Q_AND_A && context.contextValue.includes('|') ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: theme.spacing.xs, width: '100%' }}>
              {(() => {
                const parts = context.contextValue.split(' | ');
                const question = parts.find(part => part.startsWith('Q:'))?.replace('Q:', '').trim() || '';
                const answer = parts.find(part => part.startsWith('A:'))?.replace('A:', '').trim() || '';
                return (
                  <>
                    <div style={{ color: theme.colors.text.primary, fontWeight: theme.typography.fontWeight.medium }}>
                      {t('settings.context.question')}: {question}
                    </div>
                    <div style={{ color: theme.colors.text.secondary, marginLeft: theme.spacing.md }}>
                      {t('settings.context.answer')}: {answer}
                    </div>
                  </>
                );
              })()}
            </div>
          ) : (
            <span style={{ color: theme.colors.text.primary, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
              {displayValue}
              {shouldTruncate && (
                <button
                  onClick={() => setIsExpanded(!isExpanded)}
                  style={{
                    marginLeft: theme.spacing.xs,
                    color: theme.colors.primary.main,
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    fontSize: theme.typography.fontSize.sm,
                    padding: 0,
                  }}
                >
                  {isExpanded ? t('common.showLess') : t('common.showMore')}
                </button>
              )}
            </span>
          )}
          {(context.source === CONTEXT_SOURCE_AUTOGENERATED || context.source === CONTEXT_SOURCE_USER_EDITED) && (
            <span style={{ 
              fontSize: theme.typography.fontSize.xs, 
              color: theme.colors.text.tertiary,
              backgroundColor: theme.colors.background.paper,
              padding: '2px 6px',
              borderRadius: theme.borderRadius.sm,
              border: `1px solid ${theme.colors.border.light}`
            }}>
              {context.source === CONTEXT_SOURCE_USER_EDITED ? t('common.custom') : t('common.auto')}
            </span>
          )}
        </div>
        {context.explanation && (
          <span style={{ 
            fontSize: theme.typography.fontSize.xs, 
            color: theme.colors.text.secondary,
            fontStyle: 'italic',
          }}>
            {(() => {
              if (context.explanation.includes(':')) {
                const [key, ...params] = context.explanation.split(':');
                try {
                  if (key === CONTEXT_EXPLANATION_VIP_CONTACT_STARRED && params[0]) {
                    const count = parseInt(params[0], 10);
                    return t('settings.contextExplanations.vipContactStarredExplanation', { 
                      count,
                      plural: count > 1 ? 's' : ''
                    });
                  }
                  // Normalize key: convert "Learned from override" to "learnedFromOverride"
                  const normalizedKey = key.trim()
                    .toLowerCase()
                    .split(/\s+/)
                    .map((word, index) => index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1))
                    .join('');
                  const translationKey = `settings.contextExplanations.${normalizedKey}`;
                  const reasonText = params.join(':').trim();
                  // Try to translate, fallback to showing the explanation if translation doesn't exist
                  const translated = t(translationKey, { reason: reasonText, defaultValue: context.explanation });
                  return translated;
                } catch {
                  return context.explanation;
                }
              }
              return context.explanation;
            })()}
          </span>
        )}
        {context.sourceThreadIds && context.sourceThreadIds.length > 0 && (
          <span style={{ 
            fontSize: theme.typography.fontSize.xs, 
            color: theme.colors.primary.main,
            cursor: 'pointer',
          }}>
            <a 
              href={`/email/${context.sourceThreadIds[0]}`}
              style={{ color: theme.colors.primary.main, textDecoration: 'none' }}
              title={`View source email thread (${context.sourceThreadIds.length} source${context.sourceThreadIds.length > 1 ? 's' : ''})`}
            >
              {/* eslint-disable-next-line i18next/no-literal-string */}
              📧 {context.sourceThreadIds.length} source{context.sourceThreadIds.length > 1 ? 's' : ''}
            </a>
          </span>
        )}
      </div>
    </div>
  );
};

interface ContextAddInputProps {
  newContextValue: string;
  onNewContextValueChange: (value: string) => void;
  onAddContext: () => Promise<void>;
  onCancel: () => void;
}

const ContextAddInput: React.FC<ContextAddInputProps> = ({
  newContextValue,
  onNewContextValueChange,
  onAddContext,
  onCancel,
}) => {
  const { t } = useTranslation();

  return (
    <div style={{ display: 'flex', gap: theme.spacing.sm, marginTop: theme.spacing.xs }}>
      <input
        type="text"
        value={newContextValue}
        onChange={(e) => onNewContextValueChange(e.target.value)}
        placeholder={t('settings.addContext.placeholder')}
        autoFocus
        style={{
          flex: 1,
          padding: theme.spacing.sm,
          borderRadius: theme.borderRadius.md,
          border: `1px solid ${theme.colors.primary.main}`
        }}
        onKeyDown={(e) => {
          if (e.key === KEY_ENTER) onAddContext();
          if (e.key === KEY_ESCAPE) onCancel();
        }}
      />
      <button 
        onClick={onAddContext}
        disabled={!newContextValue.trim()}
        style={{
          padding: `${theme.spacing.xs} ${theme.spacing.md}`,
          backgroundColor: theme.colors.primary.main,
          color: 'white',
          border: 'none',
          borderRadius: theme.borderRadius.md,
          cursor: newContextValue.trim() ? 'pointer' : 'not-allowed',
          opacity: newContextValue.trim() ? OPACITY_FULL : OPACITY_DISABLED
        }}
      >
        {t('common.add')}
      </button>
      <button 
        onClick={onCancel}
        style={{
          padding: `${theme.spacing.xs} ${theme.spacing.md}`,
          backgroundColor: 'transparent',
          color: theme.colors.text.secondary,
          border: 'none',
          cursor: 'pointer'
        }}
      >
        {t('common.cancel')}
      </button>
    </div>
  );
};


