import { Test, TestingModule } from "@nestjs/testing";
import { getRepositoryToken } from "@nestjs/typeorm";

import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import {
  GITHUB_RESERVED_CATEGORY_KEYS,
  GitHubCategoryOverrideService,
} from "./github-category-override.service";

describe("GitHubCategoryOverrideService.bootstrapReservedCategoriesForUser", () => {
  let service: GitHubCategoryOverrideService;
  let repo: { find: jest.Mock; create: jest.Mock; save: jest.Mock };

  beforeEach(async () => {
    repo = {
      find: jest.fn().mockResolvedValue([]),
      create: jest.fn((row) => row),
      save: jest.fn().mockResolvedValue(undefined),
    };
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        GitHubCategoryOverrideService,
        { provide: getRepositoryToken(UserContext), useValue: repo },
      ],
    }).compile();
    service = module.get(GitHubCategoryOverrideService);
  });

  it("creates both reserved categories when none exist", async () => {
    await service.bootstrapReservedCategoriesForUser("u1");

    expect(repo.save).toHaveBeenCalledTimes(2);
    const createdKeys = repo.create.mock.calls.map(
      (call) => call[0].categoryKey,
    );
    expect(createdKeys).toEqual([
      GITHUB_RESERVED_CATEGORY_KEYS.AWAITING_REVIEW,
      GITHUB_RESERVED_CATEGORY_KEYS.BOT_UPDATES,
    ]);
    expect(repo.create).toHaveBeenCalledWith(
      expect.objectContaining({
        userId: "u1",
        contextKey: ContextKey.EMAIL_CATEGORY,
        source: Source.AUTOGENERATED,
      }),
    );
  });

  it("is idempotent — skips reserved categories that already exist", async () => {
    repo.find.mockResolvedValue([
      { categoryKey: GITHUB_RESERVED_CATEGORY_KEYS.AWAITING_REVIEW },
      { categoryKey: GITHUB_RESERVED_CATEGORY_KEYS.BOT_UPDATES },
    ]);

    await service.bootstrapReservedCategoriesForUser("u1");

    expect(repo.save).not.toHaveBeenCalled();
  });
});
