import { Injectable, Logger } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";

import { EmailThread } from "../database/entities/email-thread.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";

/**
 * Reserved category keys for GitHub-derived inbox grouping. These bypass the
 * LLM category-suggestion path: when a thread carries the relevant GitHub
 * signal, we override whatever the LLM picked with the matching reserved
 * category.
 */
export const GITHUB_RESERVED_CATEGORY_KEYS = {
  AWAITING_REVIEW: "__github_awaiting_review__",
  BOT_UPDATES: "__github_bot_updates__",
} as const;

const RESERVED_CATEGORY_SEEDS: Array<{
  key: string;
  name: string;
  description: string;
}> = [
  {
    key: GITHUB_RESERVED_CATEGORY_KEYS.AWAITING_REVIEW,
    name: "PRs awaiting your review",
    description:
      "GitHub pull-request notifications where you are a requested reviewer.",
  },
  {
    key: GITHUB_RESERVED_CATEGORY_KEYS.BOT_UPDATES,
    name: "Bot updates",
    description:
      "Pull requests opened by automation (Renovate, Dependabot, GitHub Actions, etc.) — safe to batch.",
  },
];

const BOT_AUTHOR_TYPE = "Bot";

type ThreadLink = NonNullable<EmailThread["githubMetadata"]>["links"][number];

/**
 * Owns the GitHub-derived category-override logic:
 *  - bootstraps the two reserved categories per user on GitHub connect
 *  - resolves which reserved category (if any) a thread should be assigned to
 *
 * Called from both the GitHub metadata processor and the LLM priority-result
 * service so that whichever processor runs last, the GitHub signal still wins.
 */
@Injectable()
export class GitHubCategoryOverrideService {
  private readonly logger = new Logger(GitHubCategoryOverrideService.name);

  constructor(
    @InjectRepository(UserContext)
    private readonly contextRepository: Repository<UserContext>,
  ) {}

  /**
   * Idempotently create the two reserved EMAIL_CATEGORY rows for a user.
   * Safe to call on every GitHub OAuth callback.
   */
  async bootstrapReservedCategoriesForUser(userId: string): Promise<void> {
    const existing = await this.contextRepository.find({
      where: { userId, contextKey: ContextKey.EMAIL_CATEGORY },
      select: ["categoryKey"],
    });
    const existingKeys = new Set(
      existing
        .map((ctx) => ctx.categoryKey)
        .filter((key): key is string => Boolean(key)),
    );

    for (const seed of RESERVED_CATEGORY_SEEDS) {
      if (existingKeys.has(seed.key)) {
        continue;
      }
      const newContext = this.contextRepository.create({
        userId,
        contextKey: ContextKey.EMAIL_CATEGORY,
        contextValue: `${seed.name} - ${seed.description}`,
        categoryKey: seed.key,
        source: Source.AUTOGENERATED,
      });
      await this.contextRepository.save(newContext);
      this.logger.log(
        `Created reserved category "${seed.name}" (${seed.key}) for user ${userId}`,
      );
    }
  }

  /**
   * Look up the contextId of a reserved GitHub category for a user.
   * Returns null if the user has not yet been bootstrapped (the row will be
   * created on their next GitHub connect or first metadata fetch).
   */
  async findReservedCategoryId(
    userId: string,
    categoryKey: string,
  ): Promise<string | null> {
    const ctx = await this.contextRepository.findOne({
      where: { userId, contextKey: ContextKey.EMAIL_CATEGORY, categoryKey },
      select: ["contextId"],
    });
    return ctx?.contextId ?? null;
  }

  /**
   * Resolve which reserved category (if any) a thread should be filed under
   * based on its GitHub metadata.
   *
   * Conflict resolution: "awaiting your review" beats "bot updates" because
   * a reviewer-requested PR is more actionable than a bot batch.
   * Returns null when no GitHub signal applies — in that case callers should
   * fall back to whatever the LLM picked.
   */
  resolveCategoryKey(
    links: ThreadLink[] | undefined,
    githubUsername: string | null,
  ): string | null {
    if (!links || links.length === 0) {
      return null;
    }

    const userLogin = githubUsername?.toLowerCase() ?? null;

    let isAwaitingReview = false;
    let isBotPr = false;
    for (const link of links) {
      const { status } = link;
      if (!status) continue;

      if (
        userLogin &&
        status.reviewerDetail?.requestedReviewers?.some(
          (reviewer) => reviewer.toLowerCase() === userLogin,
        )
      ) {
        isAwaitingReview = true;
      }

      if (status.author?.type === BOT_AUTHOR_TYPE) {
        isBotPr = true;
      }
    }

    if (isAwaitingReview) {
      return GITHUB_RESERVED_CATEGORY_KEYS.AWAITING_REVIEW;
    }
    if (isBotPr) {
      return GITHUB_RESERVED_CATEGORY_KEYS.BOT_UPDATES;
    }
    return null;
  }

  /**
   * One-shot helper for callers that have a thread + user: resolves the
   * override category and returns its contextId, or null when no override
   * applies or the reserved category hasn't been bootstrapped yet.
   */
  async resolveOverrideCategoryId(
    userId: string,
    links: ThreadLink[] | undefined,
    githubUsername: string | null,
  ): Promise<string | null> {
    const key = this.resolveCategoryKey(links, githubUsername);
    if (!key) {
      return null;
    }
    return this.findReservedCategoryId(userId, key);
  }
}
