import { Injectable, Logger } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";

import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";

/**
 * Reserved category keys for GitHub-derived inbox grouping. These two
 * categories are bootstrapped automatically when a user connects GitHub so they
 * exist as normal, model-assignable categories. (They used to auto-override the
 * model/LLM category; that override was removed — the model now decides.)
 */
export const GITHUB_RESERVED_CATEGORY_KEYS = {
  AWAITING_REVIEW: "__github_awaiting_review__",
  BOT_UPDATES: "__github_bot_updates__",
} as const;

const RESERVED_CATEGORY_SEEDS: Array<{
  key: string;
  name: string;
  description: string;
}> = [
  {
    key: GITHUB_RESERVED_CATEGORY_KEYS.AWAITING_REVIEW,
    name: "PRs awaiting your review",
    description:
      "GitHub pull-request notifications where you are a requested reviewer.",
  },
  {
    key: GITHUB_RESERVED_CATEGORY_KEYS.BOT_UPDATES,
    name: "Bot updates",
    description:
      "Pull requests opened by automation (Renovate, Dependabot, GitHub Actions, etc.) — safe to batch.",
  },
];

/**
 * Bootstraps the two reserved GitHub categories per user on GitHub connect.
 * (The GitHub-derived category override was removed; these categories now
 * behave like any other category the model/LLM/rule can assign.)
 */
@Injectable()
export class GitHubCategoryOverrideService {
  private readonly logger = new Logger(GitHubCategoryOverrideService.name);

  constructor(
    @InjectRepository(UserContext)
    private readonly contextRepository: Repository<UserContext>,
  ) {}

  /**
   * Idempotently create the two reserved EMAIL_CATEGORY rows for a user.
   * Safe to call on every GitHub OAuth callback.
   */
  async bootstrapReservedCategoriesForUser(userId: string): Promise<void> {
    const existing = await this.contextRepository.find({
      where: { userId, contextKey: ContextKey.EMAIL_CATEGORY },
      select: {
        categoryKey: true,
      },
    });
    const existingKeys = new Set(
      existing
        .map((ctx) => ctx.categoryKey)
        .filter((key): key is string => Boolean(key)),
    );

    for (const seed of RESERVED_CATEGORY_SEEDS) {
      if (existingKeys.has(seed.key)) {
        continue;
      }
      const newContext = this.contextRepository.create({
        userId,
        contextKey: ContextKey.EMAIL_CATEGORY,
        contextValue: `${seed.name} - ${seed.description}`,
        categoryKey: seed.key,
        source: Source.AUTOGENERATED,
      });
      await this.contextRepository.save(newContext);
      this.logger.log(
        `Created reserved category "${seed.name}" (${seed.key}) for user ${userId}`,
      );
    }
  }
}
