import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";

import { makeEncryptedColumnTransformer } from "../../encryption/encryption.helper";
import { User } from "./user.entity";
import { Source } from "./user-context.entity";

/**
 * A category family — the coarse level of the category hierarchy. Each user's
 * EMAIL_CATEGORY contexts ({@link UserContext}) point at a family via
 * `UserContext.familyId`, so the inbox can group categories and the local
 * classifier can commit a confident family even when the exact category is
 * ambiguous.
 *
 * Families are seeded automatically from the keyword taxonomy
 * (`category-family.taxonomy.ts`) and are user-editable thereafter (rename,
 * reorder, reassign categories), which is why the name is stored and encrypted
 * at rest rather than derived on the fly.
 */
@Entity("category_families")
@Index(["userId"])
export class CategoryFamily {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column()
  userId: string;

  @Column("text", {
    transformer: makeEncryptedColumnTransformer("category_families.name"),
  })
  name: string;

  @Column({
    type: "int",
    default: 0,
    comment: "Sort order for display in the inbox and settings.",
  })
  displayOrder: number;

  @Column({
    type: "enum",
    enum: Source,
    default: Source.AUTOGENERATED,
    comment:
      "AUTOGENERATED when seeded from the taxonomy; USER_EDITED once the user changes it.",
  })
  source: Source;

  @ManyToOne(() => User, { onDelete: "CASCADE" })
  @JoinColumn({ name: "userId" })
  user: User;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
