import { Entity, Column, PrimaryGeneratedColumn, ManyToOne, UpdateDateColumn, CreateDateColumn, JoinColumn, Index } from 'typeorm';
import { User } from './user.entity';
import { encryptedColumnTransformer } from '../../encryption/encryption.helper';

export enum ContextKey {
  // Core context categories
  VIP_CONTACT = 'VIP_CONTACT',           // Important contacts to prioritize
  MY_GOALS = 'MY_GOALS',                 // User's goals for prioritization
  DONT_CARE = 'DONT_CARE',               // Things user doesn't care about (deprioritize)
  WORKING_ON = 'WORKING_ON',             // Current projects/topics with priority (1-3)
  USER_INFO = 'USER_INFO',               // Info about the user for drafting
  URGENT = 'URGENT',                     // What the user considers urgent
  NOT_IMPORTANT = 'NOT_IMPORTANT',       // What the user doesn't consider important
  Q_AND_A = 'Q_AND_A',                   // Common questions and answers from user replies
  
  // Legacy/other
  PROJECT_NAME = 'PROJECT_NAME',         // Kept for backward compatibility
  COLLEAGUE_NAME = 'COLLEAGUE_NAME',     // Kept for backward compatibility
  CURRENT_TOPIC = 'CURRENT_TOPIC',       // Kept for backward compatibility
  WRITING_STYLE_TONE = 'WRITING_STYLE_TONE',
  COMMON_PHRASE = 'COMMON_PHRASE',
  AVERAGE_REPLY_TIME = 'AVERAGE_REPLY_TIME',
  OTHER = 'OTHER',
}

export enum Source {
  AUTOGENERATED = 'AUTOGENERATED',
  USER_EDITED = 'USER_EDITED',
}

@Entity('user_contexts')
@Index(['userId']) // Critical index for getUserContext queries
@Index(['userId', 'contextKey']) // For filtering by context type
export class UserContext {
  @PrimaryGeneratedColumn('uuid')
  contextId: string;

  @Column()
  userId: string;

  @Column({
    type: 'enum',
    enum: ContextKey,
  })
  contextKey: ContextKey;

  @Column('text', { transformer: encryptedColumnTransformer })
  contextValue: string;

  @Column({ type: 'int', nullable: true })
  priority: number; // 1 = top priority, 2 = medium, 3 = low (used for WORKING_ON items)

  @Column({
    type: 'enum',
    enum: Source,
    default: Source.AUTOGENERATED,
  })
  source: Source;

  @Column('text', { nullable: true, transformer: encryptedColumnTransformer })
  explanation: string; // Explanation/rationale for why this context was identified

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  lastModified: Date;

  @ManyToOne(() => User, (user) => user.contexts)
  @JoinColumn({ name: 'userId' })
  user: User;
}

