import { Entity, Column, PrimaryGeneratedColumn, ManyToOne, UpdateDateColumn, CreateDateColumn, JoinColumn } from 'typeorm';
import { User } from './user.entity';

export enum ContextKey {
  PROJECT_NAME = 'PROJECT_NAME',
  COLLEAGUE_NAME = 'COLLEAGUE_NAME',
  WRITING_STYLE_TONE = 'WRITING_STYLE_TONE',
  COMMON_PHRASE = 'COMMON_PHRASE',
}

export enum Source {
  AUTOGENERATED = 'AUTOGENERATED',
  USER_EDITED = 'USER_EDITED',
}

@Entity('user_contexts')
export class UserContext {
  @PrimaryGeneratedColumn()
  contextId: number;

  @Column()
  userId: number;

  @Column({
    type: 'enum',
    enum: ContextKey,
  })
  contextKey: ContextKey;

  @Column('text')
  contextValue: string;

  @Column({
    type: 'enum',
    enum: Source,
    default: Source.AUTOGENERATED,
  })
  source: Source;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  lastModified: Date;

  @ManyToOne(() => User, (user) => user.contexts)
  @JoinColumn({ name: 'userId' })
  user: User;
}

