import {
  IsNotEmpty,
  IsOptional,
  IsString,
  Matches,
  MaxLength,
} from "class-validator";

const FEEDBACK_MESSAGE_MAX_LENGTH = 5000;

/**
 * Regex that validates a server-generated screenshot S3 key.
 * Keys must start with "feedback/" prefix and contain only safe characters
 * (UUID-based filenames produced by FeedbackScreenshotsService).
 * This prevents clients from referencing arbitrary keys or keys belonging
 * to other users.
 */
const SCREENSHOT_S3_KEY_PATTERN = /^feedback\/[a-zA-Z0-9_\-.]+$/;

export class CreateFeedbackDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(FEEDBACK_MESSAGE_MAX_LENGTH)
  message: string;

  /**
   * Optional S3 key for a screenshot that was previously uploaded via
   * POST /feedback/screenshot. Must start with "feedback/" to ensure only
   * keys generated by the server presign flow are accepted.
   */
  @IsOptional()
  @IsString()
  @Matches(SCREENSHOT_S3_KEY_PATTERN, {
    message:
      'screenshotS3Key must start with "feedback/" and contain only safe characters',
  })
  screenshotS3Key?: string;
}
