import { useEffect, useRef, useState } from 'react';
import axios from 'axios';

import { API_URL } from 'config/api';
import { CONTEXT_SOURCE_AUTOGENERATED } from 'constants/strings';

interface UseInboxInitializationProps {
  authLoading: boolean;
  user: any;
  fetchEmails: () => Promise<void>;
  fetchBatchStatus: () => Promise<void>;
  fetchTabCounts: (force?: boolean) => Promise<void>;
}

export function useInboxInitialization({
  authLoading,
  user,
  fetchEmails,
  fetchBatchStatus,
  fetchTabCounts,
}: UseInboxInitializationProps) {
  const [hasInitiallyLoaded, setHasInitiallyLoaded] = useState(false);
  const [hasRunAnalysis, setHasRunAnalysis] = useState<boolean | null>(null);
  const isInitializingRef = useRef(false);

  useEffect(() => {
    if (authLoading) {
      return;
    }

    if (!user) {
      return;
    }

    if (hasInitiallyLoaded || isInitializingRef.current) {
      return;
    }

    const initializeData = async () => {
      isInitializingRef.current = true;

      try {
        await Promise.all([
          fetchEmails().catch(err => console.error('Error fetching emails:', err)),
          fetchBatchStatus().catch(err => console.error('Error fetching batch status:', err)),
          fetchTabCounts(true).catch(err => console.error('Error fetching tab counts:', err)),

          axios
            .get(`${API_URL}/context`)
            .then(contextResponse => {
              const contexts = contextResponse.data || [];
              const hasAutogenerated = contexts.some((ctx: any) => ctx.source === CONTEXT_SOURCE_AUTOGENERATED);
              setHasRunAnalysis(hasAutogenerated);
            })
            .catch(error => {
              console.error('Error fetching contexts:', error);
              setHasRunAnalysis(false);
            }),
        ]);
      } finally {
        isInitializingRef.current = false;
        // Set after fetch completes so the loading state is shown while data is being fetched.
        // Setting it early (before await) caused an empty state flash on re-navigation because
        // loading=false (persisted Redux) + hasInitiallyLoaded=true + categorySummary=null => EmptyState.
        setHasInitiallyLoaded(true);
      }
    };

    initializeData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [authLoading, user, hasInitiallyLoaded]);

  return { hasInitiallyLoaded, hasRunAnalysis };
}
