import { useEffect, useEffectEvent, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import axios from 'axios';
import { getCachedSummary } from 'utils/emailCache';

import { API_URL } from 'config/api';
import { CONTEXT_SOURCE_AUTOGENERATED } from 'constants/strings';
import { INBOX_CACHE_TTL_MS } from 'hooks/useEmailFetching';
import { InboxFilter } from 'hooks/useInboxFilters';
import { selectCategorySummary, selectLastFetchedAt } from 'store/selectors/emailSelectors';
import { setCategorySummary, setLoading, setTotalCount } from 'store/slices/emailSlice';
import { AppDispatch } from 'store/store';

interface UseInboxInitializationProps {
  authLoading: boolean;
  user: any;
  mode: string;
  fetchEmails: () => Promise<void>;
  fetchBatchStatus: () => Promise<void>;
  fetchTabCounts: (force?: boolean, filters?: Partial<InboxFilter> | null) => Promise<void>;
  filters?: Partial<InboxFilter> | null;
  /** Silent background refresh — does not show a loading spinner. Used for stale-while-revalidate. */
  refreshInPlace: () => Promise<void>;
}

/**
 * Check whether the inbox cache is considered fresh (i.e. fetched within the TTL window
 * and category data is already present in the store).
 */
function isCacheFresh(lastFetchedAt: number | null, hasCachedData: boolean): boolean {
  if (!lastFetchedAt || !hasCachedData) {
    return false;
  }
  return Date.now() - lastFetchedAt < INBOX_CACHE_TTL_MS;
}

export function useInboxInitialization({
  authLoading,
  user,
  mode,
  fetchEmails,
  fetchBatchStatus,
  fetchTabCounts,
  filters,
  refreshInPlace,
}: UseInboxInitializationProps) {
  const [hasInitiallyLoaded, setHasInitiallyLoaded] = useState(false);
  const [hasRunAnalysis, setHasRunAnalysis] = useState<boolean | null>(null);
  const isInitializingRef = useRef(false);
  const dispatch = useDispatch<AppDispatch>();

  const lastFetchedAt = useSelector(selectLastFetchedAt);
  const categorySummary = useSelector(selectCategorySummary);
  const hasCachedData = categorySummary !== null && categorySummary.length > 0;

  // useEffectEvent captures the latest values of all inbox initialization dependencies
  // (dispatch, fetch functions, cache state) so the effect only re-runs when the
  // gating conditions change (authLoading, user, hasInitiallyLoaded) — not every time
  // a callback reference or Redux selector value changes.
  const runInitialization = useEffectEvent(async () => {
    isInitializingRef.current = true;

    try {
      const shouldUseReduxCache = isCacheFresh(lastFetchedAt, hasCachedData);

      // Check localStorage for data persisted across page refreshes.
      // This handles the case where the user refreshes the page or opens a new tab.
      const localStorageSummary = !shouldUseReduxCache ? getCachedSummary(mode) : null;
      const hasLocalStorageData = localStorageSummary !== null && localStorageSummary.length > 0;

      if (shouldUseReduxCache || hasLocalStorageData) {
        // If we only have localStorage data (e.g. after a page refresh), populate Redux
        // immediately so the UI renders without a spinner.
        if (hasLocalStorageData && !shouldUseReduxCache) {
          dispatch(setCategorySummary(localStorageSummary));
          dispatch(setTotalCount(localStorageSummary.reduce((sum, cat) => sum + cat.count, 0)));
          dispatch(setLoading(false));
        }

        // Cache is fresh (Redux) or restored from localStorage: render immediately,
        // then silently revalidate in the background so the list stays up-to-date.
        setHasInitiallyLoaded(true);
        await Promise.all([
          refreshInPlace().catch(err => console.error('Error refreshing inbox in background:', err)),
          fetchBatchStatus().catch(err => console.error('Error fetching batch status:', err)),
          fetchTabCounts(false, filters).catch(err => console.error('Error fetching tab counts:', err)),

          axios
            .get(`${API_URL}/context`)
            .then(contextResponse => {
              const contexts = contextResponse.data || [];
              const hasAutogenerated = contexts.some((ctx: any) => ctx.source === CONTEXT_SOURCE_AUTOGENERATED);
              setHasRunAnalysis(hasAutogenerated);
            })
            .catch(error => {
              console.error('Error fetching contexts:', error);
              setHasRunAnalysis(false);
            }),
        ]);
      } else {
        // No cache at all — full fetch with loading indicator.
        // fetchEmails itself also checks localStorage (stale-while-revalidate),
        // so if localStorage has data it will show it immediately and refresh in background.
        await Promise.all([
          fetchEmails().catch(err => console.error('Error fetching emails:', err)),
          fetchBatchStatus().catch(err => console.error('Error fetching batch status:', err)),
          fetchTabCounts(true, filters).catch(err => console.error('Error fetching tab counts:', err)),

          axios
            .get(`${API_URL}/context`)
            .then(contextResponse => {
              const contexts = contextResponse.data || [];
              const hasAutogenerated = contexts.some((ctx: any) => ctx.source === CONTEXT_SOURCE_AUTOGENERATED);
              setHasRunAnalysis(hasAutogenerated);
            })
            .catch(error => {
              console.error('Error fetching contexts:', error);
              setHasRunAnalysis(false);
            }),
        ]);

        // Set after fetch completes so the loading state is shown while data is being fetched.
        // Setting it early (before await) caused an empty state flash on re-navigation because
        // loading=false (persisted Redux) + hasInitiallyLoaded=true + categorySummary=null => EmptyState.
        setHasInitiallyLoaded(true);
      }
    } finally {
      isInitializingRef.current = false;
    }
  });

  useEffect(() => {
    if (authLoading || !user || hasInitiallyLoaded || isInitializingRef.current) {
      return;
    }
    runInitialization();
  }, [authLoading, user, hasInitiallyLoaded, runInitialization]);

  return { hasInitiallyLoaded, hasRunAnalysis };
}
