import { Inject, Injectable, Logger } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import type { PgBoss } from "pg-boss";
import { Repository } from "typeorm";

import { CONTEXT_ANALYSIS_STATUS } from "../constants/domain-statuses";
import { ERROR_MESSAGES } from "../constants/error-messages";
import { INJECT_TOKENS } from "../constants/inject-tokens";
import { JOB_NAMES } from "../constants/job-names";
import { ContextCrudService } from "../context/context-crud.service";
import { ContextAnalysis } from "../database/entities/context-analysis.entity";
import { EmailThread } from "../database/entities/email-thread.entity";
import { ContextKey, Source } from "../database/entities/user-context.entity";
import { getJobPriority } from "../queue/job-priorities";
import { UsersService } from "../users/users.service";

const DEFAULT_CATEGORY_NAMES = {
  NEWSLETTERS: "Newsletters",
} as const;

@Injectable()
export class OnboardingService {
  private readonly logger = new Logger(OnboardingService.name);

  constructor(
    @Inject(INJECT_TOKENS.PG_BOSS) private readonly boss: PgBoss,
    private readonly usersService: UsersService,
    private readonly contextCrudService: ContextCrudService,
    @InjectRepository(EmailThread)
    private readonly emailThreadRepository: Repository<EmailThread>,
    @InjectRepository(ContextAnalysis)
    private readonly contextAnalysisRepository: Repository<ContextAnalysis>,
  ) {}

  async startHistoricalScan(userId: string): Promise<{ message: string }> {
    const user = await this.usersService.findOne(userId);
    if (!user) {
      throw new Error(ERROR_MESSAGES.USER_NOT_FOUND);
    }
    if (!user.googleCalendarAccessToken) {
      throw new Error(
        "Google account not connected. Please connect your Google account first.",
      );
    }

    this.logger.log(`Queueing historical email scan for user ${userId}`);
    await this.boss.send(
      JOB_NAMES.SCAN_HISTORY,
      { userId },
      {
        priority: getJobPriority(JOB_NAMES.SCAN_HISTORY, false),
      },
    );
    return { message: "Historical email scan initiated in the background." };
  }

  async getScanProgress(
    userId: string,
  ): Promise<{ progress: { current: number; total: number } | null }> {
    const user = await this.usersService.findOne(userId);
    if (!user) {
      return { progress: null };
    }

    if (user.scanProgress !== null && user.scanTotal !== null) {
      return {
        progress: {
          current: user.scanProgress,
          total: user.scanTotal,
        },
      };
    }

    return { progress: null };
  }

  async getOnboardingStatus(userId: string): Promise<{
    hasCompletedOnboarding: boolean;
    needsTermsAcceptance: boolean;
    needsPrivacyAcceptance: boolean;
  }> {
    return this.usersService.getOnboardingStatus(userId);
  }

  async completeOnboarding(userId: string): Promise<{ success: boolean }> {
    await this.usersService.completeOnboarding(userId);
    await this.createDefaultCategories(userId);
    return { success: true };
  }

  private async createDefaultCategories(userId: string): Promise<void> {
    try {
      await this.contextCrudService.createOrUpdateContext(
        userId,
        ContextKey.EMAIL_CATEGORY,
        DEFAULT_CATEGORY_NAMES.NEWSLETTERS,
        Source.AUTOGENERATED,
      );
      this.logger.log(
        `Created default Newsletters category for user ${userId}`,
      );
    } catch (error) {
      // Don't fail onboarding if default category creation fails
      this.logger.warn(
        `Failed to create default categories for user ${userId}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  async getEmailImportProgress(userId: string): Promise<{
    prioritizedCount: number;
    isReady: boolean;
  }> {
    const count = await this.emailThreadRepository.count({
      where: {
        userId,
      },
    });

    // Check if the context analysis has completed or failed.
    // Don't block the user if analysis failed — that's not their fault.
    const latestAnalysis = await this.contextAnalysisRepository.findOne({
      where: { userId },
      order: { createdAt: "DESC" },
    });

    const analysisCompleted =
      latestAnalysis?.status === CONTEXT_ANALYSIS_STATUS.COMPLETED;
    const analysisFailed =
      latestAnalysis?.status === CONTEXT_ANALYSIS_STATUS.FAILED;
    const hasSyncedEmails = count > 0;

    // Context analysis reads emails straight from the provider and never writes
    // EmailThread rows; those come from the separate FETCH_USER_EMAILS/scanHistory
    // sync, which typically lags the (much faster) analysis. So the analysis can
    // report "completed" while `count` is still 0, i.e. before any email has been
    // synced. Gating readiness on the completed analysis alone froze the onboarding
    // "Reading your recent emails" step at "(0 so far)" with the bar at 100%, because
    // the client stops polling once isReady flips true. Require at least one synced
    // email alongside a completed analysis so the count keeps climbing while the sync
    // runs. Failure still unblocks unconditionally (not the user's fault), and large
    // mailboxes short-circuit once enough has landed.
    const isReady =
      analysisFailed || (analysisCompleted && hasSyncedEmails) || count >= 100;

    return {
      prioritizedCount: count,
      isReady,
    };
  }
}
