// Common string constants to avoid magic strings

// Email modes (must match InboxMode type)
export const MODE_TRIAGE = 'triage' as const;
export const MODE_ACTION = 'action' as const;
export const MODE_FOLLOW_UP = 'follow-up' as const;

export type InboxModeType = typeof MODE_TRIAGE | typeof MODE_ACTION | typeof MODE_FOLLOW_UP;

// Reply modes
export const REPLY_MODE_REPLY = 'reply' as const;
export const REPLY_MODE_REPLY_ALL = 'replyAll' as const;
export const REPLY_MODE_FORWARD = 'forward' as const;

// Action item sources
export const ACTION_ITEM_SOURCE_MANUAL = 'manual' as const;
export const ACTION_ITEM_SOURCE_AI = 'ai' as const;

// GitHub status values
export const GITHUB_STATUS_OPEN = 'open' as const;
export const GITHUB_STATUS_CLOSED = 'closed' as const;
export const GITHUB_STATUS_MERGED = 'merged' as const;
export const GITHUB_STATUS_DRAFT = 'draft' as const;

// GitHub issue states
export const GITHUB_STATE_OPEN = 'open' as const;
export const GITHUB_STATE_CLOSED = 'closed' as const;

// GitHub PR states
export const GITHUB_PR_STATE_OPEN = 'open' as const;
export const GITHUB_PR_STATE_CLOSED = 'closed' as const;
export const GITHUB_PR_STATE_MERGED = 'merged' as const;
export const GITHUB_PR_STATE_DRAFT = 'draft' as const;

// Follow-up status
export const FOLLOW_UP_STATUS_GENERATING = 'generating' as const;
export const FOLLOW_UP_STATUS_ERROR = 'error' as const;

// Debug panel tabs
export const DEBUG_TAB_STATS = 'stats' as const;

// Booking form status
export const BOOKING_STATUS_SUCCESS = 'success' as const;

// Action types
export const ACTION_TYPE_CUSTOM = 'Custom' as const;
export const ACTION_TYPE_GITHUB_CREATE_ISSUE = 'github_create_issue' as const;
export const ACTION_TYPE_GITHUB_UPDATE_STATUS = 'github_update_status' as const;
export const ACTION_TYPE_GITHUB_ADD_COMMENT = 'github_add_comment' as const;
export const ACTION_TYPE_GITHUB_SEARCH_ISSUES = 'github_search_issues' as const;
export const ACTION_TYPE_CALENDAR_CREATE_INVITE = 'calendar_create_invite' as const;
export const ACTION_TYPE_CALENDAR_FIND_EVENTS = 'calendar_find_events' as const;

// Action type prefixes
export const GITHUB_ACTION_PREFIX = 'github_' as const;
export const CALENDAR_ACTION_PREFIX = 'calendar_' as const;

// GitHub review status
export const GITHUB_REVIEW_STATUS_APPROVED = 'approved' as const;
export const GITHUB_REVIEW_STATUS_CHANGES_REQUESTED = 'changes_requested' as const;

// Follow-up send status
export const FOLLOW_UP_SEND_STATUS_SENT = 'sent' as const;
export const FOLLOW_UP_SEND_STATUS_FAILED = 'failed' as const;
export const FOLLOW_UP_SEND_STATUS_SENDING = 'sending' as const;

// Search result markers
export const SEARCH_RESULT_NO_RESULTS = 'no-results' as const;

// Summary types
export const SUMMARY_TYPE_CUSTOM = 'custom' as const;
export const SUMMARY_TYPE_CUSTOM_PREFIX = 'custom-' as const;

// Keyboard keys
export const KEY_ENTER = 'Enter' as const;
export const KEY_ESCAPE = 'Escape' as const;
export const KEY_TAB = 'Tab' as const;
export const KEY_ARROW_DOWN = 'ArrowDown' as const;
export const KEY_ARROW_UP = 'ArrowUp' as const;
export const KEY_J = 'j' as const;
export const KEY_K = 'k' as const;
export const KEY_DELETE = 'Delete' as const;
export const KEY_BACKSPACE = 'Backspace' as const;
export const KEY_E = 'e' as const;

// Error messages
export const ERROR_NETWORK = 'Network Error' as const;
export const ERROR_CODE_ERR_NETWORK = 'ERR_NETWORK' as const;
export const ERROR_GMAIL_REQUIRED = 'Gmail account connection required' as const;
export const ERROR_GMAIL = 'Gmail' as const;
export const ERROR_CODE_GMAIL_REQUIRED = 'GMAIL_REQUIRED' as const;

// API endpoints
export const API_ENDPOINT_USERS_ME = '/users/me' as const;

// HTTP methods
export const HTTP_METHOD_GET = 'get' as const;

// Environment
export const ENV_DEVELOPMENT = 'development' as const;

// Typeof checks
export const TYPEOF_STRING = 'string' as const;
export const TYPEOF_UNDEFINED = 'undefined' as const;

// Search progress steps
export const SEARCH_PROGRESS_CRAFTING = 'Crafting' as const;
export const SEARCH_PROGRESS_SEARCHING = 'Searching for emails' as const;
export const SEARCH_PROGRESS_FILTERING = 'Filtering' as const;
export const SEARCH_PROGRESS_GENERATING = 'Generating explanations' as const;

// Draft status
export const DRAFT_STATUS_PENDING = 'pending' as const;
export const DRAFT_STATUS_GENERATING = 'generating' as const;
export const DRAFT_STATUS_COMPLETED = 'completed' as const;
export const DRAFT_STATUS_ERROR = 'error' as const;

// Action item source
export const ACTION_ITEM_SOURCE_LLM = 'llm' as const;

// Context source
export const CONTEXT_SOURCE_AUTOGENERATED = 'AUTOGENERATED' as const;

// Context key
export const CONTEXT_KEY_Q_AND_A = 'Q_AND_A' as const;

// Context explanation keys
export const CONTEXT_EXPLANATION_VIP_CONTACT_STARRED = 'vipContactStarredExplanation' as const;

// Context source additional values
export const CONTEXT_SOURCE_USER_EDITED = 'USER_EDITED' as const;

// Context key additional values
export const CONTEXT_KEY_WORKING_ON = 'WORKING_ON' as const;

// Button variants
export const BUTTON_VARIANT_PRIMARY = 'primary' as const;
export const BUTTON_VARIANT_SECONDARY = 'secondary' as const;

// Input types
export const INPUT_TYPE_TEXTAREA = 'textarea' as const;

// Email fields (standard field names, but extracted to constants for ESLint)
export const EMAIL_FIELD_TO = 'to' as const;
export const EMAIL_FIELD_CC = 'cc' as const;
export const EMAIL_FIELD_BCC = 'bcc' as const;

// Delivery status
export const DELIVERY_STATUS_OVERDUE = 'overdue' as const;

// Animation types
export const ANIMATION_TYPE_SEND = 'send' as const;
export const ANIMATION_TYPE_ARCHIVE = 'archive' as const;

// Link types
export const LINK_TYPE_ISSUE = 'issue' as const;
export const LINK_TYPE_PR = 'pr' as const;

