import { Test, TestingModule } from "@nestjs/testing";
import { getRepositoryToken } from "@nestjs/typeorm";

import { Email } from "../database/entities/email.entity";
import { EmailThread } from "../database/entities/email-thread.entity";
import { PriorityOverride } from "../database/entities/priority-override.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { LLMService } from "../llm/llm.service";
import { PriorityService } from "./priority.service";

describe("PriorityService", () => {
  let service: PriorityService;

  const mockEmailRepository = {
    findOne: jest.fn(),
  };

  const mockEmailThreadRepository = {
    findOne: jest.fn(),
  };

  const mockUserContextRepository = {
    find: jest.fn(),
  };

  const mockPriorityOverrideRepository = {
    findOne: jest.fn(),
  };

  const mockLLMService = {};

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        PriorityService,
        {
          provide: getRepositoryToken(Email),
          useValue: mockEmailRepository,
        },
        {
          provide: getRepositoryToken(EmailThread),
          useValue: mockEmailThreadRepository,
        },
        {
          provide: getRepositoryToken(UserContext),
          useValue: mockUserContextRepository,
        },
        {
          provide: getRepositoryToken(PriorityOverride),
          useValue: mockPriorityOverrideRepository,
        },
        {
          provide: LLMService,
          useValue: mockLLMService,
        },
      ],
    }).compile();

    service = module.get<PriorityService>(PriorityService);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe("calculatePriorityWithExplanation", () => {
    it("should calculate base priority with no contexts", () => {
      const email: Partial<Email> = {
        subject: "Test email",
        body: "Test body",
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result).toHaveProperty("score");
      expect(result).toHaveProperty("factors");
      expect(result).toHaveProperty("breakdown");
      expect(result).toHaveProperty("dimensions");
      expect(result.score).toBeGreaterThanOrEqual(0);
      expect(result.score).toBeLessThanOrEqual(100);
    });

    it("should add VIP contact boost", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
        from: "vip@example.com",
        fromName: "VIP Contact",
      };
      const contexts: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.VIP_CONTACT,
          contextValue: "vip@example.com",
          source: Source.AUTOGENERATED,
          priority: null,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const vipFactor = result.factors.find(
        (factor) => factor.type === "VIP_CONTACT",
      );
      expect(vipFactor).toBeDefined();
      expect(vipFactor?.contribution).toBe(25);
      expect(result.score).toBeGreaterThanOrEqual(25);
    });

    it("should calculate goal alignment", () => {
      const email: Partial<Email> = {
        subject: "Project update",
        body: "Here is the update on the important project",
      };
      const contexts: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.MY_GOALS,
          contextValue: "important project",
          source: Source.AUTOGENERATED,
          priority: null,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const goalFactor = result.factors.find(
        (factor) => factor.type === "GOAL_ALIGNMENT",
      );
      expect(goalFactor).toBeDefined();
      expect(goalFactor?.contribution).toBeGreaterThan(0);
      expect(result.dimensions?.goalAlignment.score).toBeGreaterThan(0);
    });

    it("should apply working on project boost", () => {
      const email: Partial<Email> = {
        subject: "Current project update",
        body: "Update on the active project",
      };
      const contexts: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.WORKING_ON,
          contextValue: "active project",
          priority: 1,
          source: Source.AUTOGENERATED,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const projectFactor = result.factors.find(
        (factor) => factor.type === "CURRENT_PROJECT",
      );
      expect(projectFactor).toBeDefined();
      // Priority 1 = +15
      expect(projectFactor?.contribution).toBe(15);
    });

    it("should apply different priority boosts for working on projects", () => {
      const email: Partial<Email> = {
        subject: "Project update",
        body: "Update on project",
      };

      // Test priority 2
      const contexts2: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.WORKING_ON,
          contextValue: "project",
          priority: 2,
          source: Source.AUTOGENERATED,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result2 = service.calculatePriorityWithExplanation(
        email,
        contexts2,
      );
      const factor2 = result2.factors.find(
        (factor) => factor.type === "CURRENT_PROJECT",
      );
      // Priority 2 = +10
      expect(factor2?.contribution).toBe(10);

      // Test priority 3
      const contexts3: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.WORKING_ON,
          contextValue: "project",
          priority: 3,
          source: Source.AUTOGENERATED,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result3 = service.calculatePriorityWithExplanation(
        email,
        contexts3,
      );
      const factor3 = result3.factors.find(
        (factor) => factor.type === "CURRENT_PROJECT",
      );
      // Priority 3 = +5
      expect(factor3?.contribution).toBe(5);
    });

    it("should apply dont care penalty", () => {
      const email: Partial<Email> = {
        subject: "Newsletter",
        body: "Weekly newsletter content",
      };
      const contexts: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.DONT_CARE,
          contextValue: "newsletter",
          source: Source.AUTOGENERATED,
          priority: null,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const dontCareFactor = result.factors.find(
        (factor) => factor.type === "NOT_IMPORTANT",
      );
      expect(dontCareFactor).toBeDefined();
      expect(dontCareFactor?.contribution).toBe(-20);
    });

    it("should handle sentiment analysis", () => {
      const email: Partial<Email> = {
        subject: "Urgent issue",
        body: "We have a critical problem that needs immediate attention",
        // Negative sentiment
        sentimentScore: -0.5,
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const sentimentFactor = result.factors.find(
        (factor) => factor.type === "SENTIMENT",
      );
      expect(sentimentFactor).toBeDefined();
      expect(result.dimensions?.sentiment.type).toBe("negative");
    });

    it("should handle positive sentiment", () => {
      const email: Partial<Email> = {
        subject: "Great news",
        body: "Everything is going well!",
        // Positive sentiment
        sentimentScore: 0.5,
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.dimensions?.sentiment.type).toBe("positive");
    });

    it("should handle neutral sentiment", () => {
      const email: Partial<Email> = {
        subject: "Update",
        body: "Here is an update",
        // Neutral
        sentimentScore: 0,
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.dimensions?.sentiment.type).toBe("neutral");
    });

    it("should apply job title boost", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
        senderJobTitle: "CEO",
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const jobFactor = result.factors.find(
        (factor) => factor.type === "SENDER_ROLE",
      );
      expect(jobFactor).toBeDefined();
      expect(jobFactor?.contribution).toBeGreaterThan(0);
    });

    it("should apply user override", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
        userPriorityOverride: 85,
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.score).toBe(85);
      const overrideFactor = result.factors.find(
        (factor) => factor.type === "USER_OVERRIDE",
      );
      expect(overrideFactor).toBeDefined();
    });

    it("should clamp score to 0-100 range", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
        // Over 100
        userPriorityOverride: 150,
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.score).toBeLessThanOrEqual(100);
    });

    it("should handle days since last email", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
      };
      const contexts: UserContext[] = [];
      const daysSinceLastEmail = 5;

      const result = service.calculatePriorityWithExplanation(
        email,
        contexts,
        daysSinceLastEmail,
      );

      const recencyFactor = result.factors.find(
        (factor) => factor.type === "RECENCY",
      );
      expect(recencyFactor).toBeDefined();
      expect(recencyFactor?.contribution).toBeGreaterThan(0);
    });

    it("should include breakdown array", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.breakdown).toBeDefined();
      expect(Array.isArray(result.breakdown)).toBe(true);
    });

    it("should include dimensions object", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.dimensions).toBeDefined();
      expect(result.dimensions).toHaveProperty("urgency");
      expect(result.dimensions).toHaveProperty("goalAlignment");
      expect(result.dimensions).toHaveProperty("vipContact");
      expect(result.dimensions).toHaveProperty("sentiment");
    });

    it("should handle email without body", () => {
      const email: Partial<Email> = {
        subject: "Test subject",
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.score).toBeGreaterThanOrEqual(0);
      expect(result.score).toBeLessThanOrEqual(100);
    });

    it("should handle email without subject", () => {
      const email: Partial<Email> = {
        body: "Test body",
      };
      const contexts: UserContext[] = [];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      expect(result.score).toBeGreaterThanOrEqual(0);
      expect(result.score).toBeLessThanOrEqual(100);
    });

    it("should match VIP contact by email address", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
        from: "vip@example.com",
      };
      const contexts: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.VIP_CONTACT,
          contextValue: "vip@example.com",
          source: Source.AUTOGENERATED,
          priority: null,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const vipFactor = result.factors.find(
        (factor) => factor.type === "VIP_CONTACT",
      );
      expect(vipFactor).toBeDefined();
    });

    it("should match VIP contact by name", () => {
      const email: Partial<Email> = {
        subject: "Test",
        body: "Test body",
        fromName: "VIP Person",
      };
      const contexts: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.VIP_CONTACT,
          contextValue: "VIP Person",
          source: Source.AUTOGENERATED,
          priority: null,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const vipFactor = result.factors.find(
        (factor) => factor.type === "VIP_CONTACT",
      );
      expect(vipFactor).toBeDefined();
    });

    it("should handle multiple goal matches", () => {
      const email: Partial<Email> = {
        subject: "Project A and Project B update",
        body: "Updates on both projects",
      };
      const contexts: UserContext[] = [
        {
          contextId: "1",
          userId: "user-123",
          contextKey: ContextKey.MY_GOALS,
          contextValue: "Project A",
          source: Source.AUTOGENERATED,
          priority: null,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
        {
          contextId: "2",
          userId: "user-123",
          contextKey: ContextKey.MY_GOALS,
          contextValue: "Project B",
          source: Source.AUTOGENERATED,
          priority: null,
          explanation: null,
          lastModified: new Date(),
          createdAt: new Date(),
        } as UserContext,
      ];

      const result = service.calculatePriorityWithExplanation(email, contexts);

      const goalFactor = result.factors.find(
        (factor) => factor.type === "GOAL_ALIGNMENT",
      );
      expect(goalFactor).toBeDefined();
      expect(goalFactor?.description).toContain("Project A");
      expect(goalFactor?.description).toContain("Project B");
    });
  });
});
