import { Email } from "../database/entities/email.entity";
import { GitHubRepoMapping } from "../database/entities/github-repo-mapping.entity";
import { GoogleAccount } from "../database/entities/google-account.entity";
import { SummarizationRule } from "../database/entities/summarization-rule.entity";
import { User } from "../database/entities/user.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { EncryptionHelper } from "./encryption.helper";
import { encryptionKeyProvider } from "./encryption-key-provider";
import {
  decryptEmailEntityForApi,
  decryptGitHubRepoMappingEntityForApi,
  decryptGoogleAccountEntityForApi,
  decryptSummarizationRuleEntityForApi,
  decryptUserContextEntityForApi,
  decryptUserEntityForApi,
  mapRawUserContextRowToApiEntity,
} from "./entity-api-decrypt.util";

describe("entity-api-decrypt.util", () => {
  const originalEnv = process.env.ENCRYPTION_KEY;

  beforeEach(() => {
    process.env.ENCRYPTION_KEY = "test-encryption-key-32-chars-long!!";
    encryptionKeyProvider.initialize();
    EncryptionHelper.globalConsecutiveFailures = 0;
  });

  afterEach(() => {
    if (originalEnv) {
      process.env.ENCRYPTION_KEY = originalEnv;
    } else {
      delete process.env.ENCRYPTION_KEY;
    }
  });

  it("decryptEmailEntityForApi turns ciphertext fields into plaintext", () => {
    const plainFrom = "sender@example.com";
    const plainSubject = "Hello";
    const email = {
      from: EncryptionHelper.encrypt(plainFrom),
      subject: EncryptionHelper.encrypt(plainSubject),
    } as Email;

    decryptEmailEntityForApi(email);

    expect(email.from).toBe(plainFrom);
    expect(email.subject).toBe(plainSubject);
  });

  it("decryptUserEntityForApi turns ciphertext profile fields into plaintext", () => {
    const plainDisplay = "Jane Doe";
    const user = {
      displayName: EncryptionHelper.encrypt(plainDisplay),
      jobTitle: null,
    } as User;

    decryptUserEntityForApi(user);

    expect(user.displayName).toBe(plainDisplay);
  });

  it("decryptGoogleAccountEntityForApi decrypts email field", () => {
    const plain = "user@gmail.com";
    const account = {
      email: EncryptionHelper.encrypt(plain),
      accessToken: EncryptionHelper.encrypt("tok"),
      refreshToken: EncryptionHelper.encrypt("ref"),
    } as GoogleAccount;

    decryptGoogleAccountEntityForApi(account);

    expect(account.email).toBe(plain);
  });

  it("mapRawUserContextRowToApiEntity decrypts SQL row fields", () => {
    const plainValue = "vip@example.com";
    const plainExplanation = "Starred often";
    const row = {
      contextId: "550e8400-e29b-41d4-a716-446655440000",
      userId: "660e8400-e29b-41d4-a716-446655440001",
      contextKey: ContextKey.VIP_CONTACT,
      contextValue: EncryptionHelper.encrypt(plainValue),
      priority: null,
      source: Source.AUTOGENERATED,
      explanation: EncryptionHelper.encrypt(plainExplanation),
      sourceThreadIds: "tid1,tid2",
      createdAt: new Date("2024-01-01T00:00:00.000Z"),
      lastModified: new Date("2024-01-02T00:00:00.000Z"),
      needsCategoryDedup: false,
    };

    const ctx = mapRawUserContextRowToApiEntity(row);

    expect(ctx.contextValue).toBe(plainValue);
    expect(ctx.explanation).toBe(plainExplanation);
    expect(ctx.sourceThreadIds).toEqual(["tid1", "tid2"]);
  });

  it("decryptUserContextEntityForApi decrypts contextValue and explanation", () => {
    const plainValue = "Work|priority";
    const plainExplanation = "Why this category";
    const ctx = {
      contextValue: EncryptionHelper.encrypt(plainValue),
      explanation: EncryptionHelper.encrypt(plainExplanation),
    } as UserContext;

    decryptUserContextEntityForApi(ctx);

    expect(ctx.contextValue).toBe(plainValue);
    expect(ctx.explanation).toBe(plainExplanation);
  });

  it("decryptGitHubRepoMappingEntityForApi decrypts owner, repo, categories, context", () => {
    const owner = "Focus-Bear";
    const repo = "BearlyMail";
    const cats = "Other,Engineering";
    const ctx = "When filing from email";
    const mapping = {
      owner: EncryptionHelper.encrypt(owner),
      repo: EncryptionHelper.encrypt(repo),
      emailCategories: EncryptionHelper.encrypt(cats),
      context: EncryptionHelper.encrypt(ctx),
    } as GitHubRepoMapping;

    decryptGitHubRepoMappingEntityForApi(mapping);

    expect(mapping.owner).toBe(owner);
    expect(mapping.repo).toBe(repo);
    expect(mapping.emailCategories).toBe(cats);
    expect(mapping.context).toBe(ctx);
  });

  it("decryptSummarizationRuleEntityForApi decrypts rule text", () => {
    const when = "When invoices";
    const how = "Summarize amounts";
    const rule = {
      whenToUse: EncryptionHelper.encrypt(when),
      howToSummarize: EncryptionHelper.encrypt(how),
    } as SummarizationRule;

    decryptSummarizationRuleEntityForApi(rule);

    expect(rule.whenToUse).toBe(when);
    expect(rule.howToSummarize).toBe(how);
  });
});
