import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import {
  canonicaliseCategoryName,
  normalizeCategoryNameForDedup,
  parseCategoryDescription,
  parseCategoryName,
  parseCategoryValue,
  resolveCategoryName,
} from "./category-name.util";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function makeContext(
  contextId: string,
  contextValue: string,
  contextKey = ContextKey.EMAIL_CATEGORY,
): UserContext {
  const ctx = new UserContext();
  ctx.contextId = contextId;
  ctx.contextKey = contextKey;
  ctx.contextValue = contextValue;
  ctx.userId = "user-1";
  ctx.source = Source.AUTOGENERATED;
  return ctx;
}

// ─── parseCategoryName ────────────────────────────────────────────────────────

describe("parseCategoryName", () => {
  it("extracts the name from a standard Name - Description value", () => {
    expect(
      parseCategoryName("PR Bot Comments - Auto-categorised PR notifications"),
    ).toBe("PR Bot Comments");
  });

  it("returns the full value when there is no separator", () => {
    expect(parseCategoryName("Simple Name")).toBe("Simple Name");
  });

  it("returns only the first segment when multiple separators exist", () => {
    expect(parseCategoryName("A - B - C")).toBe("A");
  });

  it("returns an empty string for an empty input", () => {
    expect(parseCategoryName("")).toBe("");
  });

  it("trims surrounding whitespace from the name", () => {
    expect(parseCategoryName("  Name  -  Desc  ")).toBe("Name");
  });

  it("handles a value that is only whitespace", () => {
    expect(parseCategoryName("   ")).toBe("");
  });

  it("handles a separator with no description part", () => {
    expect(parseCategoryName("Newsletter - ")).toBe("Newsletter");
  });
});

// ─── parseCategoryDescription ─────────────────────────────────────────────────

describe("parseCategoryDescription", () => {
  it("extracts the description from a standard Name - Description value", () => {
    expect(
      parseCategoryDescription(
        "PR Bot Comments - Auto-categorised PR notifications",
      ),
    ).toBe("Auto-categorised PR notifications");
  });

  it("returns null when there is no separator", () => {
    expect(parseCategoryDescription("Simple Name")).toBeNull();
  });

  it("preserves the remainder as description when multiple separators exist", () => {
    expect(parseCategoryDescription("A - B - C")).toBe("B - C");
  });

  it("returns null for an empty input", () => {
    expect(parseCategoryDescription("")).toBeNull();
  });

  it("trims surrounding whitespace from the description", () => {
    expect(parseCategoryDescription("  Name  -  Desc  ")).toBe("Desc");
  });

  it("returns null when the description segment is empty after trimming", () => {
    expect(parseCategoryDescription("Newsletter - ")).toBeNull();
  });
});

// ─── parseCategoryValue ───────────────────────────────────────────────────────

describe("parseCategoryValue", () => {
  it("returns name and description together", () => {
    expect(
      parseCategoryValue("PR Bot Comments - Auto-categorised PR notifications"),
    ).toEqual({
      name: "PR Bot Comments",
      description: "Auto-categorised PR notifications",
    });
  });

  it("returns null description when there is no separator", () => {
    expect(parseCategoryValue("Simple Name")).toEqual({
      name: "Simple Name",
      description: null,
    });
  });
});

// ─── normalizeCategoryNameForDedup ────────────────────────────────────────────

describe("normalizeCategoryNameForDedup", () => {
  it("collapses the same name behind different emoji to one key", () => {
    expect(normalizeCategoryNameForDedup("🚀 App Store Notifications")).toBe(
      "app store notifications",
    );
    expect(normalizeCategoryNameForDedup("📱 App Store Notifications")).toBe(
      "app store notifications",
    );
  });

  it("does NOT collapse a colon description clause into the bare name", () => {
    // Conservative: a verbose "Name: description" must not exact-merge with the
    // bare "Name" — that judgement is left to the LLM semantic pass.
    expect(
      normalizeCategoryNameForDedup(
        "🎧 Media & Communications: Podcast and media invitations",
      ),
    ).not.toBe(normalizeCategoryNameForDedup("🎧 Media & Communications"));
    expect(normalizeCategoryNameForDedup("🎧 Media & Communications")).toBe(
      "media & communications",
    );
  });

  it("keeps ampersands but normalises casing and whitespace", () => {
    expect(normalizeCategoryNameForDedup("Payments  &  Financials")).toBe(
      "payments & financials",
    );
  });

  it("does NOT collapse genuinely different names", () => {
    expect(normalizeCategoryNameForDedup("🔧 GitHub PR Updates")).not.toBe(
      normalizeCategoryNameForDedup("Pull Request Updates"),
    );
  });

  it("returns an empty string for emoji/punctuation-only names", () => {
    expect(normalizeCategoryNameForDedup("🔥✨")).toBe("");
    expect(normalizeCategoryNameForDedup("   ")).toBe("");
  });
});

// ─── resolveCategoryName ──────────────────────────────────────────────────────

describe("resolveCategoryName", () => {
  const contexts: UserContext[] = [
    makeContext("ctx-1", "PR Bot Comments - Auto-categorised PR notifications"),
    makeContext("ctx-2", "Newsletters - Marketing emails"),
    makeContext(
      "ctx-3",
      "Internal - Team updates",
      // wrong key — should be ignored
      ContextKey.WORKING_ON,
    ),
  ];

  it("resolves a known categoryId to its display name", () => {
    expect(resolveCategoryName("ctx-1", contexts)).toBe("PR Bot Comments");
  });

  it("resolves a second known categoryId correctly", () => {
    expect(resolveCategoryName("ctx-2", contexts)).toBe("Newsletters");
  });

  it("returns null for an unknown categoryId", () => {
    expect(resolveCategoryName("ctx-unknown", contexts)).toBeNull();
  });

  it("returns null when categoryId is null", () => {
    expect(resolveCategoryName(null, contexts)).toBeNull();
  });

  it("returns null when categoryId is undefined", () => {
    expect(resolveCategoryName(undefined, contexts)).toBeNull();
  });

  it("returns null when the context exists but has the wrong contextKey", () => {
    // ctx-3 is WORKING_ON, not EMAIL_CATEGORY — must not match
    expect(resolveCategoryName("ctx-3", contexts)).toBeNull();
  });

  it("returns null when contexts array is empty", () => {
    expect(resolveCategoryName("ctx-1", [])).toBeNull();
  });
});

// ─── canonicaliseCategoryName ─────────────────────────────────────────────────

describe("canonicaliseCategoryName", () => {
  const known = [
    "❌ CI/CD & QA Pipeline Failures",
    "🐛 New GitHub issues (bot-created)",
    "🆕 New Human-Created GitHub Issues",
    "🔧 GitHub PR Updates",
  ];

  it("returns the name unchanged for Other / empty", () => {
    expect(canonicaliseCategoryName("Other", known)).toBe("Other");
    expect(canonicaliseCategoryName("", known)).toBe("");
  });

  it("exact-matches case-insensitively", () => {
    expect(canonicaliseCategoryName("🔧 github pr updates", known)).toBe(
      "🔧 GitHub PR Updates",
    );
  });

  it("resolves an emoji-stripped LLM name to the stored emoji name", () => {
    // The bug: LLM returns the name without the leading emoji; the case-only
    // checks miss it, so it used to fall through to proto-fuzzy mis-routing.
    expect(
      canonicaliseCategoryName("CI/CD & QA Pipeline Failures", known),
    ).toBe("❌ CI/CD & QA Pipeline Failures");
  });

  it("does NOT snap a shorter GitHub name onto the longest sibling (no bot-created sink)", () => {
    // Old prefix-superset rule mapped "New GitHub issues" → the LONGEST match
    // "🐛 New GitHub issues (bot-created)". It must now stay unresolved instead.
    expect(canonicaliseCategoryName("New GitHub issues", known)).toBe(
      "New GitHub issues",
    );
  });

  it("leaves ambiguous normalised keys unresolved rather than guessing", () => {
    const ambiguous = ["🐙 GitHub Notifications", "GitHub notifications!!"];
    expect(canonicaliseCategoryName("github notifications", ambiguous)).toBe(
      "github notifications",
    );
  });
});
