import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import {
  parseCategoryDescription,
  parseCategoryName,
  parseCategoryValue,
  resolveCategoryName,
} from "./category-name.util";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function makeContext(
  contextId: string,
  contextValue: string,
  contextKey = ContextKey.EMAIL_CATEGORY,
): UserContext {
  const ctx = new UserContext();
  ctx.contextId = contextId;
  ctx.contextKey = contextKey;
  ctx.contextValue = contextValue;
  ctx.userId = "user-1";
  ctx.source = Source.AUTOGENERATED;
  return ctx;
}

// ─── parseCategoryName ────────────────────────────────────────────────────────

describe("parseCategoryName", () => {
  it("extracts the name from a standard Name - Description value", () => {
    expect(
      parseCategoryName("PR Bot Comments - Auto-categorised PR notifications"),
    ).toBe("PR Bot Comments");
  });

  it("returns the full value when there is no separator", () => {
    expect(parseCategoryName("Simple Name")).toBe("Simple Name");
  });

  it("returns only the first segment when multiple separators exist", () => {
    expect(parseCategoryName("A - B - C")).toBe("A");
  });

  it("returns an empty string for an empty input", () => {
    expect(parseCategoryName("")).toBe("");
  });

  it("trims surrounding whitespace from the name", () => {
    expect(parseCategoryName("  Name  -  Desc  ")).toBe("Name");
  });

  it("handles a value that is only whitespace", () => {
    expect(parseCategoryName("   ")).toBe("");
  });

  it("handles a separator with no description part", () => {
    expect(parseCategoryName("Newsletter - ")).toBe("Newsletter");
  });
});

// ─── parseCategoryDescription ─────────────────────────────────────────────────

describe("parseCategoryDescription", () => {
  it("extracts the description from a standard Name - Description value", () => {
    expect(
      parseCategoryDescription(
        "PR Bot Comments - Auto-categorised PR notifications",
      ),
    ).toBe("Auto-categorised PR notifications");
  });

  it("returns null when there is no separator", () => {
    expect(parseCategoryDescription("Simple Name")).toBeNull();
  });

  it("preserves the remainder as description when multiple separators exist", () => {
    expect(parseCategoryDescription("A - B - C")).toBe("B - C");
  });

  it("returns null for an empty input", () => {
    expect(parseCategoryDescription("")).toBeNull();
  });

  it("trims surrounding whitespace from the description", () => {
    expect(parseCategoryDescription("  Name  -  Desc  ")).toBe("Desc");
  });

  it("returns null when the description segment is empty after trimming", () => {
    expect(parseCategoryDescription("Newsletter - ")).toBeNull();
  });
});

// ─── parseCategoryValue ───────────────────────────────────────────────────────

describe("parseCategoryValue", () => {
  it("returns name and description together", () => {
    expect(
      parseCategoryValue("PR Bot Comments - Auto-categorised PR notifications"),
    ).toEqual({
      name: "PR Bot Comments",
      description: "Auto-categorised PR notifications",
    });
  });

  it("returns null description when there is no separator", () => {
    expect(parseCategoryValue("Simple Name")).toEqual({
      name: "Simple Name",
      description: null,
    });
  });
});

// ─── resolveCategoryName ──────────────────────────────────────────────────────

describe("resolveCategoryName", () => {
  const contexts: UserContext[] = [
    makeContext("ctx-1", "PR Bot Comments - Auto-categorised PR notifications"),
    makeContext("ctx-2", "Newsletters - Marketing emails"),
    makeContext(
      "ctx-3",
      "Internal - Team updates",
      // wrong key — should be ignored
      ContextKey.WORKING_ON,
    ),
  ];

  it("resolves a known categoryId to its display name", () => {
    expect(resolveCategoryName("ctx-1", contexts)).toBe("PR Bot Comments");
  });

  it("resolves a second known categoryId correctly", () => {
    expect(resolveCategoryName("ctx-2", contexts)).toBe("Newsletters");
  });

  it("returns null for an unknown categoryId", () => {
    expect(resolveCategoryName("ctx-unknown", contexts)).toBeNull();
  });

  it("returns null when categoryId is null", () => {
    expect(resolveCategoryName(null, contexts)).toBeNull();
  });

  it("returns null when categoryId is undefined", () => {
    expect(resolveCategoryName(undefined, contexts)).toBeNull();
  });

  it("returns null when the context exists but has the wrong contextKey", () => {
    // ctx-3 is WORKING_ON, not EMAIL_CATEGORY — must not match
    expect(resolveCategoryName("ctx-3", contexts)).toBeNull();
  });

  it("returns null when contexts array is empty", () => {
    expect(resolveCategoryName("ctx-1", [])).toBeNull();
  });
});
