import { NotFoundException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { Test, TestingModule } from "@nestjs/testing";
import { getDataSourceToken, getRepositoryToken } from "@nestjs/typeorm";

import { CategoryKeyAssignmentService } from "../category-keys/category-key-assignment.service";
import { EmailThread } from "../database/entities/email-thread.entity";
import { ProtoCategory } from "../database/entities/proto-category.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { LLMCoreService } from "../llm/llm-core.service";
import { MAX_BOOTSTRAP_CATEGORIES } from "./proto-categories.constants";
import { ProtoCategoriesService } from "./proto-categories.service";

const mockProtoCategoryRepo = () => ({
  find: jest.fn(),
  findOne: jest.fn(),
  create: jest.fn(),
  save: jest.fn(),
  update: jest.fn(),
  increment: jest.fn(),
  delete: jest.fn(),
});

/**
 * Chainable mock for the update query builder used by
 * updateThreadCategoryWithPrecedence. Captures the `.set()` payload so tests
 * can assert on the guarded category write.
 */
const makeUpdateQueryBuilderMock = () => {
  const builder = {
    update: jest.fn(),
    set: jest.fn(),
    andWhere: jest.fn(),
    execute: jest.fn().mockResolvedValue({ affected: 1 }),
  };
  builder.update.mockReturnValue(builder);
  builder.set.mockReturnValue(builder);
  builder.andWhere.mockReturnValue(builder);
  return builder;
};

const mockEmailThreadRepo = () => {
  const queryBuilder = makeUpdateQueryBuilderMock();
  return {
    update: jest.fn(),
    createQueryBuilder: jest.fn().mockReturnValue(queryBuilder),
    queryBuilder,
  };
};

const mockUserContextRepo = () => ({
  find: jest.fn(),
  create: jest.fn(),
  save: jest.fn(),
  update: jest.fn(),
  // Default to the bootstrap cap so existing tests treat the user as an
  // established (non-bootstrapping) user; bootstrap tests override this.
  count: jest.fn().mockResolvedValue(MAX_BOOTSTRAP_CATEGORIES),
});

const mockDataSource = () => ({
  transaction: jest.fn(),
});

const mockCategoryKeyService = () => ({
  allocateKeyForNewCategory: jest.fn().mockResolvedValue("test_category_key"),
});

const mockLLMCoreService = () => ({
  generateText: jest.fn(),
});

/**
 * Builds a `generateText` mock that mimics the strong dedup model over the
 * list-based prompt: it scans the numbered `categoryList` embedded in the
 * rendered prompt for the line whose category name contains `needle` and
 * returns that line's number as `duplicateNumber` (0 when none match). Because
 * it reads the ACTUAL numbered list the service built (Levenshtein-sorted), the
 * returned index is correct regardless of where the match sits in the raw repo
 * order — proving nothing is pre-filtered.
 */
const respondWithMatch =
  (needle: string) =>
  async (request: { prompt: string }): Promise<string> => {
    for (const line of request.prompt.split("\n")) {
      const parsed = line.trim().match(/^(\d+)\.\s+(.*)$/);
      if (parsed && parsed[2].includes(needle)) {
        return `{"duplicateNumber": ${parsed[1]}, "reasoning": "match"}`;
      }
    }
    return '{"duplicateNumber": 0, "reasoning": "no match"}';
  };

const NO_MATCH_RESPONSE = '{"duplicateNumber": 0, "reasoning": "no match"}';

function makeUserContext(
  contextId: string,
  contextValue: string,
  alternateNames: string[] | null = null,
): UserContext {
  const ctx = new UserContext();
  ctx.contextId = contextId;
  ctx.userId = "user-1";
  ctx.contextKey = ContextKey.EMAIL_CATEGORY;
  ctx.contextValue = contextValue;
  ctx.alternateNames = alternateNames;
  ctx.source = Source.AUTOGENERATED;
  return ctx;
}

jest.mock("../llm/prompts", () => ({
  getPrompt: jest.fn().mockReturnValue({
    prompt:
      'New category: "{{newCategory}}"\nExisting categories:\n{{categoryList}}',
    systemPrompt: "You are a dedup assistant.",
  }),
  renderPrompt: jest
    .fn()
    .mockImplementation((template: string, vars: Record<string, string>) =>
      template.replace(
        /\{\{(\w+)\}\}/g,
        (_match: string, key: string) => vars[key] ?? "",
      ),
    ),
  UTILITY_PROMPT_IDS: { CHECK_CATEGORY_DUPLICATE: "check_category_duplicate" },
}));

describe("ProtoCategoriesService", () => {
  let service: ProtoCategoriesService;
  let protoCategoryRepo: ReturnType<typeof mockProtoCategoryRepo>;
  let emailThreadRepo: ReturnType<typeof mockEmailThreadRepo>;
  let userContextRepo: ReturnType<typeof mockUserContextRepo>;
  let dataSource: ReturnType<typeof mockDataSource>;
  let llmCoreService: ReturnType<typeof mockLLMCoreService>;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ProtoCategoriesService,
        {
          provide: getRepositoryToken(ProtoCategory),
          useFactory: mockProtoCategoryRepo,
        },
        {
          provide: getRepositoryToken(EmailThread),
          useFactory: mockEmailThreadRepo,
        },
        {
          provide: getRepositoryToken(UserContext),
          useFactory: mockUserContextRepo,
        },
        { provide: getDataSourceToken(), useFactory: mockDataSource },
        {
          provide: CategoryKeyAssignmentService,
          useFactory: mockCategoryKeyService,
        },
        {
          provide: LLMCoreService,
          useFactory: mockLLMCoreService,
        },
        {
          provide: ConfigService,
          useValue: { get: jest.fn().mockReturnValue(undefined) },
        },
      ],
    }).compile();

    service = module.get(ProtoCategoriesService);
    protoCategoryRepo = module.get(getRepositoryToken(ProtoCategory));
    emailThreadRepo = module.get(getRepositoryToken(EmailThread));
    userContextRepo = module.get(getRepositoryToken(UserContext));
    dataSource = module.get(getDataSourceToken());
    llmCoreService = module.get(LLMCoreService);
  });

  describe("findMatchingFullCategory", () => {
    it("returns null when no categories exist", async () => {
      userContextRepo.find.mockResolvedValue([]);
      const result = await service.findMatchingFullCategory("user-1", "Foo");
      expect(result).toBeNull();
    });

    it("matches by exact name (case-insensitive)", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "Newsletters - Weekly digests"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "newsletters",
      );
      expect(result).toEqual({ name: "Newsletters", contextId: "ctx-1" });
    });

    it("matches by emoji-stripped name", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "📰 Newsletters - Weekly digests"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Newsletters",
      );
      expect(result).toEqual({ name: "📰 Newsletters", contextId: "ctx-1" });
    });

    it("matches via alternate names without calling LLM", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "📰 Newsletters - Weekly digests", [
          "Newslters",
          "Newsltters",
        ]),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Newslters",
      );
      expect(result).toEqual({ name: "📰 Newsletters", contextId: "ctx-1" });
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("calls the LLM with the full list and returns the match when the model picks its number", async () => {
      const stored = makeUserContext(
        "ctx-1",
        "CI/CD Alerts - Pipeline notifications",
      );
      userContextRepo.find.mockResolvedValue([stored]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(stored),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      llmCoreService.generateText.mockImplementation(
        respondWithMatch("CI/CD Alerts"),
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
      expect(result).toEqual({ name: "CI/CD Alerts", contextId: "ctx-1" });
      expect(txRepo.update).toHaveBeenCalledWith(
        { contextId: "ctx-1" },
        expect.objectContaining({
          alternateNames: expect.arrayContaining(["CI/CD Alert"]),
        }),
      );
    });

    it("returns null when the model returns 0 (no duplicate)", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "CI/CD Alerts - Pipeline notifications"),
      ]);
      llmCoreService.generateText.mockResolvedValue(NO_MATCH_RESPONSE);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Recruitment",
      );
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
      expect(result).toBeNull();
      expect(dataSource.transaction).not.toHaveBeenCalled();
    });

    it("returns null and does not throw when the LLM call fails", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "CI/CD Alerts"),
      ]);
      llmCoreService.generateText.mockRejectedValue(new Error("LLM timeout"));

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(result).toBeNull();
    });

    it("picks the correct candidate by number from a decoy-heavy full list (nothing pre-filtered)", async () => {
      // The real match sits LAST in the raw repo order behind four decoys.
      // Because the whole list reaches the model, it still resolves correctly.
      const realMatch = makeUserContext(
        "ctx-github-prs",
        "🐙 GitHub PRs - Pull request notifications",
      );
      const decoys = [
        makeUserContext("ctx-invoices", "Invoices"),
        makeUserContext("ctx-newsletters", "📰 Newsletters"),
        makeUserContext("ctx-meetings", "Meeting scheduling"),
        makeUserContext("ctx-notif", "🔔 Notifications"),
      ];
      userContextRepo.find.mockResolvedValue([...decoys, realMatch]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(realMatch),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      llmCoreService.generateText.mockImplementation(
        respondWithMatch("GitHub PRs"),
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Github and Code",
      );
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
      expect(result?.name).toBe("🐙 GitHub PRs");
    });

    it("resolves the cold-outreach paraphrase from a decoy-heavy full list", async () => {
      const realMatch = makeUserContext(
        "ctx-cold-outreach",
        "📨 Cold outreach: from others to me",
      );
      const decoys = [
        makeUserContext("ctx-cold-weather", "🥶 Cold weather alerts"),
        makeUserContext("ctx-outreach-events", "📣 Outreach events"),
        makeUserContext("ctx-sales-pipeline", "💰 Sales pipeline"),
        makeUserContext("ctx-cold-calls", "☎️ Cold calls I make"),
      ];
      userContextRepo.find.mockResolvedValue([...decoys, realMatch]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(realMatch),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      llmCoreService.generateText.mockImplementation(
        respondWithMatch("from others to me"),
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Cold Sales Outreach",
      );
      expect(result?.name).toBe("📨 Cold outreach: from others to me");
    });
  });

  describe("findMatchingProtoCategory", () => {
    it("returns null when no active proto categories exist", async () => {
      protoCategoryRepo.find.mockResolvedValue([]);
      const result = await service.findMatchingProtoCategory("user-1", "Foo");
      expect(result).toBeNull();
    });

    it("does not swallow a sibling proto by substring — asks the LLM, which returns 0", async () => {
      // "New GitHub issues" is a prefix of this proto. There is no exact match,
      // so the full-list LLM call runs; here the model rejects it (returns 0),
      // so distinct GitHub categories are NOT collapsed into the "(bot-created)"
      // bucket.
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "New GitHub issues (bot-created)",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockResolvedValue(NO_MATCH_RESPONSE);

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "New GitHub issues",
      );
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
      expect(result).toBeNull();
    });

    it("still matches an exact name after emoji stripping (no LLM call)", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "🐛 Newsletters",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Newsletters",
      );
      expect(result).toBe(proto);
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("calls the LLM with the full list and returns the proto when the model picks its number", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Newsletters",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockImplementation(
        respondWithMatch("Newsletters"),
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Newslters",
      );
      expect(result).toBe(proto);
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
    });

    it("returns null when the model returns 0", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Project A",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockResolvedValue(NO_MATCH_RESPONSE);

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Project B",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
    });

    it("returns null and does not throw when the LLM call fails", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Finance Reports",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockRejectedValue(new Error("LLM timeout"));

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Recruitment",
      );
      expect(result).toBeNull();
    });

    it("folds a source-specific newsletter sibling into a generic proto via the full-list LLM call", async () => {
      // The key anti-proliferation case: "AI Weekly Newsletter" is a large edit
      // distance from "📰 Newsletters", but the whole list reaches the model,
      // which folds the source-specific variant into the existing generic bucket
      // instead of spawning yet another newsletter proto.
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-news",
        userId: "user-1",
        name: "📰 Newsletters",
        isPromoted: false,
        emailCount: 3,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockImplementation(
        respondWithMatch("Newsletters"),
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "AI Weekly Newsletter",
      );
      expect(result).toBe(proto);
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
    });

    it("picks the correct proto by number from a decoy-heavy full list (nothing pre-filtered)", async () => {
      const realMatch = Object.assign(new ProtoCategory(), {
        id: "proto-news",
        userId: "user-1",
        name: "📰 Newsletters",
        isPromoted: false,
        emailCount: 3,
      });
      const decoys = [
        "Invoices",
        "Meeting scheduling",
        "GitHub PRs",
        "Receipts",
      ].map((name, i) =>
        Object.assign(new ProtoCategory(), {
          id: `decoy-${i}`,
          userId: "user-1",
          name,
          isPromoted: false,
          emailCount: 1,
        }),
      );
      protoCategoryRepo.find.mockResolvedValue([...decoys, realMatch]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockImplementation(
        respondWithMatch("Newsletters"),
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "AI Weekly Newsletter",
      );
      expect(result).toBe(realMatch);
      expect(llmCoreService.generateText).toHaveBeenCalledTimes(1);
    });

    it("excludes the thread's own proto from matching (self-guard)", async () => {
      // Re-analysing a thread must not let its suggestion match — and double-count
      // into — the very proto it already belongs to.
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Newsletters",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Newsletters",
        undefined,
        "proto-1",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });
  });

  describe("assignThreadToProtoCategory", () => {
    it("throws NotFoundException when proto category not found", async () => {
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );
      protoCategoryRepo.increment.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(null);

      await expect(
        service.assignThreadToProtoCategory("missing-id", "thread-1"),
      ).rejects.toThrow(NotFoundException);
    });
  });

  describe("promoteToCategory", () => {
    const makeProto = (overrides = {}): ProtoCategory =>
      ({
        id: "proto-1",
        userId: "user-1",
        name: "Meeting Acceptance Notifications",
        description: "Calendar acceptance confirmations",
        emailCount: 5,
        isPromoted: false,
        ...overrides,
      }) as ProtoCategory;

    it("returns early without creating a category when already promoted", async () => {
      const result = await service.promoteToCategory(
        makeProto({ isPromoted: true }),
      );
      expect(result.isPromoted).toBe(true);
      expect(userContextRepo.save).not.toHaveBeenCalled();
    });

    it("folds into an existing near-duplicate category instead of creating a duplicate", async () => {
      // A sibling proto already promoted into this real category.
      userContextRepo.find.mockResolvedValue([
        makeUserContext(
          "ctx-existing",
          "Acceptances to Internal Meetings - standup, OKR, planning",
        ),
      ]);
      llmCoreService.generateText.mockResolvedValue(
        '{"duplicateNumber": 1, "reasoning": "Both are meeting acceptance notifications"}',
      );
      const txQueryBuilder = makeUpdateQueryBuilderMock();
      const txRepo = {
        findOne: jest
          .fn()
          .mockResolvedValue(makeUserContext("ctx-existing", "x")),
        update: jest.fn().mockResolvedValue({}),
        createQueryBuilder: jest.fn().mockReturnValue(txQueryBuilder),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-existing" }),
      );

      await service.promoteToCategory(makeProto());

      // No new category minted...
      expect(userContextRepo.save).not.toHaveBeenCalled();
      // ...proto pointed at the existing category...
      expect(txRepo.update).toHaveBeenCalledWith(
        { id: "proto-1" },
        expect.objectContaining({
          isPromoted: true,
          promotedCategoryId: "ctx-existing",
        }),
      );
      // ...its threads reassigned to the existing category via the guarded
      // bulk update (filtered to this proto's threads)...
      expect(txQueryBuilder.set).toHaveBeenCalledWith(
        expect.objectContaining({ categoryId: "ctx-existing" }),
      );
      expect(txQueryBuilder.andWhere).toHaveBeenCalledWith(
        '"protoCategoryId" = :where_protoCategoryId',
        { where_protoCategoryId: "proto-1" },
      );
      expect(txQueryBuilder.execute).toHaveBeenCalledTimes(1);
      // ...and any guard-skipped threads detached from the dead proto.
      expect(txRepo.update).toHaveBeenCalledWith(
        { protoCategoryId: "proto-1" },
        { protoCategoryId: null },
      );
    });

    it("creates a new category when no duplicate exists", async () => {
      userContextRepo.find.mockResolvedValue([]);
      userContextRepo.create.mockImplementation((ctx: unknown) => ctx);
      userContextRepo.save.mockResolvedValue({ contextId: "ctx-new" });
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-new" }),
      );

      await service.promoteToCategory(makeProto());

      expect(userContextRepo.save).toHaveBeenCalled();
    });

    it("stamps a proto-promotion decision trace and clears categorySource on reassigned threads", async () => {
      userContextRepo.find.mockResolvedValue([]);
      userContextRepo.create.mockImplementation((ctx: unknown) => ctx);
      userContextRepo.save.mockResolvedValue({ contextId: "ctx-new" });
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-new" }),
      );
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );

      await service.promoteToCategory(makeProto());

      // The guarded bulk update targets this proto's threads...
      expect(emailThreadRepo.queryBuilder.andWhere).toHaveBeenCalledWith(
        '"protoCategoryId" = :where_protoCategoryId',
        { where_protoCategoryId: "proto-1" },
      );
      expect(emailThreadRepo.queryBuilder.execute).toHaveBeenCalledTimes(1);
      const payload = emailThreadRepo.queryBuilder.set.mock.calls[0][0];
      expect(payload.categoryId).toBe("ctx-new");
      expect(payload.protoCategoryId).toBeNull();
      // stale "priority" cleared, and the promotion recorded as the applied step
      expect(payload.categorySource).toBeNull();
      expect(payload.categoryDecisionTrace.steps[0].step).toBe(
        "proto-promotion",
      );
      expect(payload.categoryDecisionTrace.steps[0].outcome).toBe("applied");
      // ...and guard-skipped threads are detached from the dead proto.
      expect(emailThreadRepo.update).toHaveBeenCalledWith(
        { protoCategoryId: "proto-1" },
        { protoCategoryId: null },
      );
    });

    it("records promotion timestamp, reasoning, and considered candidates", async () => {
      userContextRepo.find.mockResolvedValue([]);
      userContextRepo.create.mockImplementation((ctx: unknown) => ctx);
      userContextRepo.save.mockResolvedValue({ contextId: "ctx-new" });
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-new" }),
      );

      const creationCandidates = [
        { name: "GitHub PRs", isDuplicate: false, reasoning: "Different" },
      ];
      await service.promoteToCategory(
        makeProto({ duplicateCandidates: creationCandidates }),
      );

      const updateCall = protoCategoryRepo.update.mock.calls[0][1];
      expect(updateCall.promotedCategoryId).toBe("ctx-new");
      expect(updateCall.promotedAt).toBeInstanceOf(Date);
      expect(updateCall.promotionReasoning).toContain("Auto-promoted");
      expect(updateCall.duplicateCandidates).toEqual(creationCandidates);
    });
  });

  describe("createAndAssignToThread", () => {
    it("persists considered duplicate candidates on the new proto category", async () => {
      protoCategoryRepo.find.mockResolvedValue([]);
      protoCategoryRepo.create.mockImplementation(
        (input: Partial<ProtoCategory>) => input,
      );
      protoCategoryRepo.save.mockImplementation(
        async (input: Partial<ProtoCategory>) => ({ id: "proto-1", ...input }),
      );
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );

      const considered = [
        {
          name: "GitHub PRs",
          isDuplicate: false,
          reasoning: "Different scope",
        },
      ];

      await service.createAndAssignToThread(
        "user-1",
        "GitHub Releases",
        null,
        "thread-1",
        { consideredCandidates: considered },
      );

      expect(protoCategoryRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({ duplicateCandidates: considered }),
      );
    });

    it("persists the categoriser's creation reasoning (closest rejects + why)", async () => {
      protoCategoryRepo.find.mockResolvedValue([]);
      protoCategoryRepo.create.mockImplementation(
        (input: Partial<ProtoCategory>) => input,
      );
      protoCategoryRepo.save.mockImplementation(
        async (input: Partial<ProtoCategory>) => ({ id: "proto-1", ...input }),
      );
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );

      const reasoning =
        "'GitHub PRs' was closest but this is a release note, not a PR.";

      await service.createAndAssignToThread(
        "user-1",
        "GitHub Releases",
        null,
        "thread-1",
        { creationReasoning: reasoning },
      );

      expect(protoCategoryRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({ creationReasoning: reasoning }),
      );
    });
  });

  describe("createAndAssignToThread — bootstrap auto-promotion", () => {
    // Wire up the mocks a fresh (deduped) proto walks through when it is
    // created and then immediately promoted during bootstrap.
    const setupNewProtoCreation = () => {
      protoCategoryRepo.find.mockResolvedValue([]);
      protoCategoryRepo.create.mockImplementation(
        (input: Partial<ProtoCategory>) => input,
      );
      protoCategoryRepo.save.mockImplementation(
        async (input: Partial<ProtoCategory>) => ({ id: "proto-1", ...input }),
      );
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );
    };

    it("immediately promotes a new deduped suggestion when the user has 0 real categories", async () => {
      userContextRepo.count.mockResolvedValue(0);
      setupNewProtoCreation();
      // No existing real categories → dedup finds no match, a real category is minted.
      userContextRepo.find.mockResolvedValue([]);
      userContextRepo.create.mockImplementation((ctx: unknown) => ctx);
      userContextRepo.save.mockResolvedValue({ contextId: "ctx-new" });
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue({
        id: "proto-1",
        name: "Customer Support",
        isPromoted: true,
        promotedCategoryId: "ctx-new",
      } as ProtoCategory);

      const result = await service.createAndAssignToThread(
        "user-1",
        "Customer Support",
        null,
        "thread-1",
      );

      // A real category was minted immediately — no 5-email wait.
      expect(userContextRepo.save).toHaveBeenCalled();
      expect(result.isPromoted).toBe(true);
    });

    it("folds a new suggestion into an existing category (no duplicate) even in bootstrap mode", async () => {
      userContextRepo.count.mockResolvedValue(3);
      setupNewProtoCreation();
      // An existing real category the strong-model dedup will match against.
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-existing", "Customer Support - support tickets"),
      ]);
      llmCoreService.generateText.mockResolvedValue(
        '{"duplicateNumber": 1, "reasoning": "Same category"}',
      );
      const txQueryBuilder = makeUpdateQueryBuilderMock();
      const txRepo = {
        findOne: jest
          .fn()
          .mockResolvedValue(makeUserContext("ctx-existing", "x")),
        update: jest.fn().mockResolvedValue({}),
        createQueryBuilder: jest.fn().mockReturnValue(txQueryBuilder),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue({
        id: "proto-1",
        name: "Support",
        isPromoted: true,
        promotedCategoryId: "ctx-existing",
      } as ProtoCategory);

      await service.createAndAssignToThread("user-1", "Support", null, "t-1");

      // No new category minted — folded into the existing one.
      expect(userContextRepo.save).not.toHaveBeenCalled();
      expect(txRepo.update).toHaveBeenCalledWith(
        { id: "proto-1" },
        expect.objectContaining({ promotedCategoryId: "ctx-existing" }),
      );
    });

    it("does NOT auto-promote once the user is at the cap (falls back to the 5-email threshold)", async () => {
      userContextRepo.count.mockResolvedValue(MAX_BOOTSTRAP_CATEGORIES);
      setupNewProtoCreation();

      const result = await service.createAndAssignToThread(
        "user-1",
        "Yet Another Category",
        null,
        "thread-1",
      );

      expect(protoCategoryRepo.save).toHaveBeenCalled();
      expect(userContextRepo.save).not.toHaveBeenCalled();
      expect(result.isPromoted).toBe(false);
    });

    it("does NOT auto-promote for an established user above the cap", async () => {
      userContextRepo.count.mockResolvedValue(MAX_BOOTSTRAP_CATEGORIES + 5);
      setupNewProtoCreation();

      const result = await service.createAndAssignToThread(
        "user-1",
        "New Category",
        null,
        "thread-1",
      );

      expect(userContextRepo.save).not.toHaveBeenCalled();
      expect(result.isPromoted).toBe(false);
    });
  });

  describe("findPromotedByUser", () => {
    it("returns promotion metadata keyed by live category id", async () => {
      const promotedAt = new Date("2026-06-17T00:00:00Z");
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "GitHub Releases",
          isPromoted: true,
          promotedCategoryId: "ctx-1",
          promotedAt,
          promotionReasoning: "Auto-promoted",
          duplicateCandidates: [
            { name: "GitHub PRs", isDuplicate: false, reasoning: "Different" },
          ],
        },
        { name: "Orphan", isPromoted: true, promotedCategoryId: null },
      ]);

      const result = await service.findPromotedByUser("user-1");

      expect(result).toEqual([
        {
          promotedCategoryId: "ctx-1",
          name: "GitHub Releases",
          promotedAt,
          promotionReasoning: "Auto-promoted",
          duplicateCandidates: [
            { name: "GitHub PRs", isDuplicate: false, reasoning: "Different" },
          ],
        },
      ]);
    });

    it("falls back to the live category's createdAt when promotedAt is null", async () => {
      const liveCreatedAt = new Date("2026-01-05T00:00:00Z");
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "CI/CD & QA Pipeline Failures",
          isPromoted: true,
          promotedCategoryId: "ctx-9",
          promotedAt: null,
          promotionReasoning: null,
          duplicateCandidates: null,
          createdAt: new Date("2025-12-01T00:00:00Z"),
        },
      ]);
      userContextRepo.find.mockResolvedValue([
        { contextId: "ctx-9", createdAt: liveCreatedAt },
      ]);

      const result = await service.findPromotedByUser("user-1");

      expect(userContextRepo.find).toHaveBeenCalled();
      expect(result[0].promotedAt).toEqual(liveCreatedAt);
    });

    it("falls back to the proto's own createdAt when the live category is missing", async () => {
      const protoCreatedAt = new Date("2025-11-01T00:00:00Z");
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "Legacy",
          isPromoted: true,
          promotedCategoryId: "ctx-missing",
          promotedAt: null,
          createdAt: protoCreatedAt,
        },
      ]);
      userContextRepo.find.mockResolvedValue([]);

      const result = await service.findPromotedByUser("user-1");

      expect(result[0].promotedAt).toEqual(protoCreatedAt);
    });

    it("sorts newest-promoted first after backfilling null dates", async () => {
      // DB returns NULLS FIRST (promotedAt DESC), so the backfilled-old row arrives
      // ahead of the recent one — the in-memory sort must reorder by resolved date.
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "Old (backfilled)",
          isPromoted: true,
          promotedCategoryId: "ctx-old",
          promotedAt: null,
          createdAt: new Date("2025-01-01T00:00:00Z"),
        },
        {
          name: "Recent",
          isPromoted: true,
          promotedCategoryId: "ctx-recent",
          promotedAt: new Date("2026-06-01T00:00:00Z"),
        },
      ]);
      userContextRepo.find.mockResolvedValue([
        { contextId: "ctx-old", createdAt: new Date("2025-01-01T00:00:00Z") },
      ]);

      const result = await service.findPromotedByUser("user-1");

      expect(result.map((info) => info.name)).toEqual([
        "Recent",
        "Old (backfilled)",
      ]);
    });
  });
});
