import { NotFoundException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { Test, TestingModule } from "@nestjs/testing";
import { getDataSourceToken, getRepositoryToken } from "@nestjs/typeorm";

import { CategoryKeyAssignmentService } from "../category-keys/category-key-assignment.service";
import { EmailThread } from "../database/entities/email-thread.entity";
import { ProtoCategory } from "../database/entities/proto-category.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { EmbeddingService } from "../llm/embedding.service";
import { LLMCoreService } from "../llm/llm-core.service";
import { ProtoCategoriesService } from "./proto-categories.service";

const mockProtoCategoryRepo = () => ({
  find: jest.fn(),
  findOne: jest.fn(),
  create: jest.fn(),
  save: jest.fn(),
  update: jest.fn(),
  increment: jest.fn(),
  delete: jest.fn(),
});

/**
 * Chainable mock for the update query builder used by
 * updateThreadCategoryWithPrecedence. Captures the `.set()` payload so tests
 * can assert on the guarded category write.
 */
const makeUpdateQueryBuilderMock = () => {
  const builder = {
    update: jest.fn(),
    set: jest.fn(),
    andWhere: jest.fn(),
    execute: jest.fn().mockResolvedValue({ affected: 1 }),
  };
  builder.update.mockReturnValue(builder);
  builder.set.mockReturnValue(builder);
  builder.andWhere.mockReturnValue(builder);
  return builder;
};

const mockEmailThreadRepo = () => {
  const queryBuilder = makeUpdateQueryBuilderMock();
  return {
    update: jest.fn(),
    createQueryBuilder: jest.fn().mockReturnValue(queryBuilder),
    queryBuilder,
  };
};

const mockUserContextRepo = () => ({
  find: jest.fn(),
  create: jest.fn(),
  save: jest.fn(),
  update: jest.fn(),
});

const mockDataSource = () => ({
  transaction: jest.fn(),
});

const mockCategoryKeyService = () => ({
  allocateKeyForNewCategory: jest.fn().mockResolvedValue("test_category_key"),
});

const mockLLMCoreService = () => ({
  generateText: jest.fn(),
});

const mockEmbeddingService = () => ({
  isAvailable: jest.fn().mockReturnValue(false),
  embed: jest.fn(),
});

function makeUserContext(
  contextId: string,
  contextValue: string,
  alternateNames: string[] | null = null,
): UserContext {
  const ctx = new UserContext();
  ctx.contextId = contextId;
  ctx.userId = "user-1";
  ctx.contextKey = ContextKey.EMAIL_CATEGORY;
  ctx.contextValue = contextValue;
  ctx.alternateNames = alternateNames;
  ctx.source = Source.AUTOGENERATED;
  return ctx;
}

jest.mock("../llm/prompts", () => ({
  getPrompt: jest.fn().mockReturnValue({
    prompt: "Are '{{categoryA}}' and '{{categoryB}}' duplicates?",
    systemPrompt: "You are a dedup assistant.",
  }),
  renderPrompt: jest
    .fn()
    .mockImplementation((template: string, vars: Record<string, string>) =>
      template.replace(
        /\{\{(\w+)\}\}/g,
        (_match: string, key: string) => vars[key] ?? "",
      ),
    ),
  UTILITY_PROMPT_IDS: { CHECK_CATEGORY_DUPLICATE: "check_category_duplicate" },
}));

describe("ProtoCategoriesService", () => {
  let service: ProtoCategoriesService;
  let protoCategoryRepo: ReturnType<typeof mockProtoCategoryRepo>;
  let emailThreadRepo: ReturnType<typeof mockEmailThreadRepo>;
  let userContextRepo: ReturnType<typeof mockUserContextRepo>;
  let dataSource: ReturnType<typeof mockDataSource>;
  let llmCoreService: ReturnType<typeof mockLLMCoreService>;
  let embeddingService: ReturnType<typeof mockEmbeddingService>;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ProtoCategoriesService,
        {
          provide: getRepositoryToken(ProtoCategory),
          useFactory: mockProtoCategoryRepo,
        },
        {
          provide: getRepositoryToken(EmailThread),
          useFactory: mockEmailThreadRepo,
        },
        {
          provide: getRepositoryToken(UserContext),
          useFactory: mockUserContextRepo,
        },
        { provide: getDataSourceToken(), useFactory: mockDataSource },
        {
          provide: CategoryKeyAssignmentService,
          useFactory: mockCategoryKeyService,
        },
        {
          provide: LLMCoreService,
          useFactory: mockLLMCoreService,
        },
        {
          provide: EmbeddingService,
          useFactory: mockEmbeddingService,
        },
        {
          provide: ConfigService,
          useValue: { get: jest.fn().mockReturnValue(undefined) },
        },
      ],
    }).compile();

    service = module.get(ProtoCategoriesService);
    protoCategoryRepo = module.get(getRepositoryToken(ProtoCategory));
    emailThreadRepo = module.get(getRepositoryToken(EmailThread));
    userContextRepo = module.get(getRepositoryToken(UserContext));
    dataSource = module.get(getDataSourceToken());
    llmCoreService = module.get(LLMCoreService);
    embeddingService = module.get(EmbeddingService);
  });

  describe("findMatchingFullCategory", () => {
    it("returns null when no categories exist", async () => {
      userContextRepo.find.mockResolvedValue([]);
      const result = await service.findMatchingFullCategory("user-1", "Foo");
      expect(result).toBeNull();
    });

    it("matches by exact name (case-insensitive)", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "Newsletters - Weekly digests"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "newsletters",
      );
      expect(result).toEqual({ name: "Newsletters", contextId: "ctx-1" });
    });

    it("matches by emoji-stripped name", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "📰 Newsletters - Weekly digests"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Newsletters",
      );
      expect(result).toEqual({ name: "📰 Newsletters", contextId: "ctx-1" });
    });

    it("matches via alternate names without calling LLM", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "📰 Newsletters - Weekly digests", [
          "Newslters",
          "Newsltters",
        ]),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Newslters",
      );
      expect(result).toEqual({ name: "📰 Newsletters", contextId: "ctx-1" });
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("calls LLM for near-duplicate and returns match when confirmed", async () => {
      const stored = makeUserContext(
        "ctx-1",
        "CI/CD Alerts - Pipeline notifications",
      );
      userContextRepo.find.mockResolvedValue([stored]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(stored),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same category"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(llmCoreService.generateText).toHaveBeenCalled();
      expect(result).toEqual({ name: "CI/CD Alerts", contextId: "ctx-1" });
      expect(txRepo.update).toHaveBeenCalledWith(
        { contextId: "ctx-1" },
        expect.objectContaining({
          alternateNames: expect.arrayContaining(["CI/CD Alert"]),
        }),
      );
    });

    it("returns null when LLM says near-duplicate is not the same", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "CI/CD Alerts - Pipeline notifications"),
      ]);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Different"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(result).toBeNull();
      expect(dataSource.transaction).not.toHaveBeenCalled();
    });

    it("returns null and does not throw when LLM call fails", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "CI/CD Alerts"),
      ]);
      llmCoreService.generateText.mockRejectedValue(new Error("LLM timeout"));

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(result).toBeNull();
    });

    it("does not call LLM for clearly different category names", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "Finance Reports - Invoices and billing"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Recruitment",
      );
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
      expect(result).toBeNull();
    });

    it("catches semantic paraphrase via embedding similarity + LLM (full)", async () => {
      const stored = makeUserContext("ctx-1", "QA Passed - Test results");
      userContextRepo.find.mockResolvedValue([stored]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(stored),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) =>
            text === "QA Passed" || text === "Tests Green" ? [1, 0] : [0, 1],
          ),
        ),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same outcome"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Tests Green",
      );
      expect(embeddingService.embed).toHaveBeenCalled();
      expect(result).toEqual({ name: "QA Passed", contextId: "ctx-1" });
      expect(txRepo.update).toHaveBeenCalledWith(
        { contextId: "ctx-1" },
        expect.objectContaining({
          alternateNames: expect.arrayContaining(["Tests Green"]),
        }),
      );
    });

    it("does not embed-match when similarity is below threshold", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "Finance Reports"),
      ]);
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) => (text === "Tests Green" ? [1, 0] : [0, 1])),
        ),
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Tests Green",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("blocks broad platform catch-all via Phase 4 shared-token check (issue #2065 follow-up)", async () => {
      const stored = makeUserContext(
        "ctx-github-prs",
        "🐙 GitHub PRs - Pull request notifications",
      );
      const stored2 = makeUserContext(
        "ctx-github-notif",
        "🔔 GitHub Notifications - General GitHub alerts",
      );
      userContextRepo.find.mockResolvedValue([stored, stored2]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(stored),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      // LLM says the broad "Github and Code" is a duplicate of the specific "🐙 GitHub PRs"
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Broad catch-all for GitHub emails"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Github and Code",
      );
      expect(llmCoreService.generateText).toHaveBeenCalled();
      expect(result).not.toBeNull();
      expect(result?.name).toBe("🐙 GitHub PRs");
    });

    it("allows specific platform sub-category when LLM says not a duplicate", async () => {
      const stored = makeUserContext(
        "ctx-github-prs",
        "🐙 GitHub PRs - Pull request notifications",
      );
      userContextRepo.find.mockResolvedValue([stored]);
      // LLM says "GitHub Releases" is NOT a duplicate of "GitHub PRs"
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Different GitHub sub-categories"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "GitHub Releases",
      );
      expect(llmCoreService.generateText).toHaveBeenCalled();
      expect(result).toBeNull();
    });
  });

  describe("findMatchingProtoCategory", () => {
    it("returns null when no active proto categories exist", async () => {
      protoCategoryRepo.find.mockResolvedValue([]);
      const result = await service.findMatchingProtoCategory("user-1", "Foo");
      expect(result).toBeNull();
    });

    it("does not swallow a sibling proto by substring without LLM confirmation", async () => {
      // "New GitHub issues" is a prefix of this proto. The old substring `includes()`
      // check returned it immediately (no confirmation), collapsing distinct GitHub
      // categories into the "(bot-created)" bucket. It must now fall through to the
      // LLM-confirmed fuzzy passes, which here reject the match.
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "New GitHub issues (bot-created)",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Distinct GitHub categories"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "New GitHub issues",
      );
      expect(result).toBeNull();
    });

    it("still matches an exact name after emoji stripping", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "🐛 Newsletters",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Newsletters",
      );
      expect(result).toBe(proto);
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("matches by Levenshtein similarity when LLM confirms duplicate", async () => {
      // Use names that pass Levenshtein but fail containment so the LLM path runs.
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Newsletters",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same category"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Newslters",
      );
      expect(result).toBe(proto);
      expect(llmCoreService.generateText).toHaveBeenCalled();
    });

    it("returns null when Levenshtein matches but LLM rejects the duplicate", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Project A",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Distinct projects"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Project B",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).toHaveBeenCalled();
    });

    it("returns null for clearly different names without calling LLM", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Finance Reports",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Recruitment",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("catches semantic paraphrase via embedding similarity + LLM (proto)", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "QA Passed",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) =>
            text === "QA Passed" || text === "Tests Green" ? [1, 0] : [0, 1],
          ),
        ),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same outcome"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Tests Green",
      );
      expect(embeddingService.embed).toHaveBeenCalled();
      expect(result).toBe(proto);
    });

    it("returns null when embedding flags a candidate but LLM rejects it", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "QA Passed",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) =>
            text === "QA Passed" || text === "Tests Green" ? [1, 0] : [0, 1],
          ),
        ),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Different"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Tests Green",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).toHaveBeenCalled();
    });
  });

  describe("assignThreadToProtoCategory", () => {
    it("throws NotFoundException when proto category not found", async () => {
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );
      protoCategoryRepo.increment.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(null);

      await expect(
        service.assignThreadToProtoCategory("missing-id", "thread-1"),
      ).rejects.toThrow(NotFoundException);
    });
  });

  describe("promoteToCategory", () => {
    const makeProto = (overrides = {}): ProtoCategory =>
      ({
        id: "proto-1",
        userId: "user-1",
        name: "Meeting Acceptance Notifications",
        description: "Calendar acceptance confirmations",
        emailCount: 5,
        isPromoted: false,
        ...overrides,
      }) as ProtoCategory;

    it("returns early without creating a category when already promoted", async () => {
      const result = await service.promoteToCategory(
        makeProto({ isPromoted: true }),
      );
      expect(result.isPromoted).toBe(true);
      expect(userContextRepo.save).not.toHaveBeenCalled();
    });

    it("folds into an existing near-duplicate category instead of creating a duplicate", async () => {
      // A sibling proto already promoted into this real category.
      userContextRepo.find.mockResolvedValue([
        makeUserContext(
          "ctx-existing",
          "Acceptances to Internal Meetings - standup, OKR, planning",
        ),
      ]);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Both are meeting acceptance notifications"}',
      );
      const txQueryBuilder = makeUpdateQueryBuilderMock();
      const txRepo = {
        findOne: jest
          .fn()
          .mockResolvedValue(makeUserContext("ctx-existing", "x")),
        update: jest.fn().mockResolvedValue({}),
        createQueryBuilder: jest.fn().mockReturnValue(txQueryBuilder),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-existing" }),
      );

      await service.promoteToCategory(makeProto());

      // No new category minted...
      expect(userContextRepo.save).not.toHaveBeenCalled();
      // ...proto pointed at the existing category...
      expect(txRepo.update).toHaveBeenCalledWith(
        { id: "proto-1" },
        expect.objectContaining({
          isPromoted: true,
          promotedCategoryId: "ctx-existing",
        }),
      );
      // ...its threads reassigned to the existing category via the guarded
      // bulk update (filtered to this proto's threads)...
      expect(txQueryBuilder.set).toHaveBeenCalledWith(
        expect.objectContaining({ categoryId: "ctx-existing" }),
      );
      expect(txQueryBuilder.andWhere).toHaveBeenCalledWith(
        '"protoCategoryId" = :where_protoCategoryId',
        { where_protoCategoryId: "proto-1" },
      );
      expect(txQueryBuilder.execute).toHaveBeenCalledTimes(1);
      // ...and any guard-skipped threads detached from the dead proto.
      expect(txRepo.update).toHaveBeenCalledWith(
        { protoCategoryId: "proto-1" },
        { protoCategoryId: null },
      );
    });

    it("creates a new category when no duplicate exists", async () => {
      userContextRepo.find.mockResolvedValue([]);
      userContextRepo.create.mockImplementation((ctx: unknown) => ctx);
      userContextRepo.save.mockResolvedValue({ contextId: "ctx-new" });
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-new" }),
      );

      await service.promoteToCategory(makeProto());

      expect(userContextRepo.save).toHaveBeenCalled();
    });

    it("stamps a proto-promotion decision trace and clears categorySource on reassigned threads", async () => {
      userContextRepo.find.mockResolvedValue([]);
      userContextRepo.create.mockImplementation((ctx: unknown) => ctx);
      userContextRepo.save.mockResolvedValue({ contextId: "ctx-new" });
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-new" }),
      );
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );

      await service.promoteToCategory(makeProto());

      // The guarded bulk update targets this proto's threads...
      expect(emailThreadRepo.queryBuilder.andWhere).toHaveBeenCalledWith(
        '"protoCategoryId" = :where_protoCategoryId',
        { where_protoCategoryId: "proto-1" },
      );
      expect(emailThreadRepo.queryBuilder.execute).toHaveBeenCalledTimes(1);
      const payload = emailThreadRepo.queryBuilder.set.mock.calls[0][0];
      expect(payload.categoryId).toBe("ctx-new");
      expect(payload.protoCategoryId).toBeNull();
      // stale "priority" cleared, and the promotion recorded as the applied step
      expect(payload.categorySource).toBeNull();
      expect(payload.categoryDecisionTrace.steps[0].step).toBe(
        "proto-promotion",
      );
      expect(payload.categoryDecisionTrace.steps[0].outcome).toBe("applied");
      // ...and guard-skipped threads are detached from the dead proto.
      expect(emailThreadRepo.update).toHaveBeenCalledWith(
        { protoCategoryId: "proto-1" },
        { protoCategoryId: null },
      );
    });

    it("records promotion timestamp, reasoning, and considered candidates", async () => {
      userContextRepo.find.mockResolvedValue([]);
      userContextRepo.create.mockImplementation((ctx: unknown) => ctx);
      userContextRepo.save.mockResolvedValue({ contextId: "ctx-new" });
      protoCategoryRepo.update.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(
        makeProto({ isPromoted: true, promotedCategoryId: "ctx-new" }),
      );

      const creationCandidates = [
        { name: "GitHub PRs", isDuplicate: false, reasoning: "Different" },
      ];
      await service.promoteToCategory(
        makeProto({ duplicateCandidates: creationCandidates }),
      );

      const updateCall = protoCategoryRepo.update.mock.calls[0][1];
      expect(updateCall.promotedCategoryId).toBe("ctx-new");
      expect(updateCall.promotedAt).toBeInstanceOf(Date);
      expect(updateCall.promotionReasoning).toContain("Auto-promoted");
      expect(updateCall.duplicateCandidates).toEqual(creationCandidates);
    });
  });

  describe("createAndAssignToThread", () => {
    it("persists considered duplicate candidates on the new proto category", async () => {
      protoCategoryRepo.find.mockResolvedValue([]);
      protoCategoryRepo.create.mockImplementation(
        (input: Partial<ProtoCategory>) => input,
      );
      protoCategoryRepo.save.mockImplementation(
        async (input: Partial<ProtoCategory>) => ({ id: "proto-1", ...input }),
      );
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );

      const considered = [
        {
          name: "GitHub PRs",
          isDuplicate: false,
          reasoning: "Different scope",
        },
      ];

      await service.createAndAssignToThread(
        "user-1",
        "GitHub Releases",
        null,
        "thread-1",
        considered,
      );

      expect(protoCategoryRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({ duplicateCandidates: considered }),
      );
    });
  });

  describe("findPromotedByUser", () => {
    it("returns promotion metadata keyed by live category id", async () => {
      const promotedAt = new Date("2026-06-17T00:00:00Z");
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "GitHub Releases",
          isPromoted: true,
          promotedCategoryId: "ctx-1",
          promotedAt,
          promotionReasoning: "Auto-promoted",
          duplicateCandidates: [
            { name: "GitHub PRs", isDuplicate: false, reasoning: "Different" },
          ],
        },
        { name: "Orphan", isPromoted: true, promotedCategoryId: null },
      ]);

      const result = await service.findPromotedByUser("user-1");

      expect(result).toEqual([
        {
          promotedCategoryId: "ctx-1",
          name: "GitHub Releases",
          promotedAt,
          promotionReasoning: "Auto-promoted",
          duplicateCandidates: [
            { name: "GitHub PRs", isDuplicate: false, reasoning: "Different" },
          ],
        },
      ]);
    });

    it("falls back to the live category's createdAt when promotedAt is null", async () => {
      const liveCreatedAt = new Date("2026-01-05T00:00:00Z");
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "CI/CD & QA Pipeline Failures",
          isPromoted: true,
          promotedCategoryId: "ctx-9",
          promotedAt: null,
          promotionReasoning: null,
          duplicateCandidates: null,
          createdAt: new Date("2025-12-01T00:00:00Z"),
        },
      ]);
      userContextRepo.find.mockResolvedValue([
        { contextId: "ctx-9", createdAt: liveCreatedAt },
      ]);

      const result = await service.findPromotedByUser("user-1");

      expect(userContextRepo.find).toHaveBeenCalled();
      expect(result[0].promotedAt).toEqual(liveCreatedAt);
    });

    it("falls back to the proto's own createdAt when the live category is missing", async () => {
      const protoCreatedAt = new Date("2025-11-01T00:00:00Z");
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "Legacy",
          isPromoted: true,
          promotedCategoryId: "ctx-missing",
          promotedAt: null,
          createdAt: protoCreatedAt,
        },
      ]);
      userContextRepo.find.mockResolvedValue([]);

      const result = await service.findPromotedByUser("user-1");

      expect(result[0].promotedAt).toEqual(protoCreatedAt);
    });

    it("sorts newest-promoted first after backfilling null dates", async () => {
      // DB returns NULLS FIRST (promotedAt DESC), so the backfilled-old row arrives
      // ahead of the recent one — the in-memory sort must reorder by resolved date.
      protoCategoryRepo.find.mockResolvedValue([
        {
          name: "Old (backfilled)",
          isPromoted: true,
          promotedCategoryId: "ctx-old",
          promotedAt: null,
          createdAt: new Date("2025-01-01T00:00:00Z"),
        },
        {
          name: "Recent",
          isPromoted: true,
          promotedCategoryId: "ctx-recent",
          promotedAt: new Date("2026-06-01T00:00:00Z"),
        },
      ]);
      userContextRepo.find.mockResolvedValue([
        { contextId: "ctx-old", createdAt: new Date("2025-01-01T00:00:00Z") },
      ]);

      const result = await service.findPromotedByUser("user-1");

      expect(result.map((info) => info.name)).toEqual([
        "Recent",
        "Old (backfilled)",
      ]);
    });
  });
});
