import { NotFoundException } from "@nestjs/common";
import { Test, TestingModule } from "@nestjs/testing";
import { getDataSourceToken, getRepositoryToken } from "@nestjs/typeorm";

import { CategoryKeyAssignmentService } from "../category-keys/category-key-assignment.service";
import { EmailThread } from "../database/entities/email-thread.entity";
import { ProtoCategory } from "../database/entities/proto-category.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { EmbeddingService } from "../llm/embedding.service";
import { LLMCoreService } from "../llm/llm-core.service";
import { ProtoCategoriesService } from "./proto-categories.service";

const mockProtoCategoryRepo = () => ({
  find: jest.fn(),
  findOne: jest.fn(),
  create: jest.fn(),
  save: jest.fn(),
  update: jest.fn(),
  increment: jest.fn(),
  delete: jest.fn(),
});

const mockEmailThreadRepo = () => ({
  update: jest.fn(),
});

const mockUserContextRepo = () => ({
  find: jest.fn(),
  create: jest.fn(),
  save: jest.fn(),
  update: jest.fn(),
});

const mockDataSource = () => ({
  transaction: jest.fn(),
});

const mockCategoryKeyService = () => ({
  allocateKeyForNewCategory: jest.fn().mockResolvedValue("test_category_key"),
});

const mockLLMCoreService = () => ({
  generateText: jest.fn(),
});

const mockEmbeddingService = () => ({
  isAvailable: jest.fn().mockReturnValue(false),
  embed: jest.fn(),
});

function makeUserContext(
  contextId: string,
  contextValue: string,
  alternateNames: string[] | null = null,
): UserContext {
  const ctx = new UserContext();
  ctx.contextId = contextId;
  ctx.userId = "user-1";
  ctx.contextKey = ContextKey.EMAIL_CATEGORY;
  ctx.contextValue = contextValue;
  ctx.alternateNames = alternateNames;
  ctx.source = Source.AUTOGENERATED;
  return ctx;
}

jest.mock("../llm/prompts", () => ({
  getPrompt: jest.fn().mockReturnValue({
    prompt: "Are '{{categoryA}}' and '{{categoryB}}' duplicates?",
    systemPrompt: "You are a dedup assistant.",
  }),
  renderPrompt: jest
    .fn()
    .mockImplementation((template: string, vars: Record<string, string>) =>
      template.replace(
        /\{\{(\w+)\}\}/g,
        (_match: string, key: string) => vars[key] ?? "",
      ),
    ),
  UTILITY_PROMPT_IDS: { CHECK_CATEGORY_DUPLICATE: "check_category_duplicate" },
}));

describe("ProtoCategoriesService", () => {
  let service: ProtoCategoriesService;
  let protoCategoryRepo: ReturnType<typeof mockProtoCategoryRepo>;
  let userContextRepo: ReturnType<typeof mockUserContextRepo>;
  let dataSource: ReturnType<typeof mockDataSource>;
  let llmCoreService: ReturnType<typeof mockLLMCoreService>;
  let embeddingService: ReturnType<typeof mockEmbeddingService>;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ProtoCategoriesService,
        {
          provide: getRepositoryToken(ProtoCategory),
          useFactory: mockProtoCategoryRepo,
        },
        {
          provide: getRepositoryToken(EmailThread),
          useFactory: mockEmailThreadRepo,
        },
        {
          provide: getRepositoryToken(UserContext),
          useFactory: mockUserContextRepo,
        },
        { provide: getDataSourceToken(), useFactory: mockDataSource },
        {
          provide: CategoryKeyAssignmentService,
          useFactory: mockCategoryKeyService,
        },
        {
          provide: LLMCoreService,
          useFactory: mockLLMCoreService,
        },
        {
          provide: EmbeddingService,
          useFactory: mockEmbeddingService,
        },
      ],
    }).compile();

    service = module.get(ProtoCategoriesService);
    protoCategoryRepo = module.get(getRepositoryToken(ProtoCategory));
    userContextRepo = module.get(getRepositoryToken(UserContext));
    dataSource = module.get(getDataSourceToken());
    llmCoreService = module.get(LLMCoreService);
    embeddingService = module.get(EmbeddingService);
  });

  describe("findMatchingFullCategory", () => {
    it("returns null when no categories exist", async () => {
      userContextRepo.find.mockResolvedValue([]);
      const result = await service.findMatchingFullCategory("user-1", "Foo");
      expect(result).toBeNull();
    });

    it("matches by exact name (case-insensitive)", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "Newsletters - Weekly digests"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "newsletters",
      );
      expect(result).toEqual({ name: "Newsletters", contextId: "ctx-1" });
    });

    it("matches by emoji-stripped name", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "📰 Newsletters - Weekly digests"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Newsletters",
      );
      expect(result).toEqual({ name: "📰 Newsletters", contextId: "ctx-1" });
    });

    it("matches via alternate names without calling LLM", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "📰 Newsletters - Weekly digests", [
          "Newslters",
          "Newsltters",
        ]),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Newslters",
      );
      expect(result).toEqual({ name: "📰 Newsletters", contextId: "ctx-1" });
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("calls LLM for near-duplicate and returns match when confirmed", async () => {
      const stored = makeUserContext(
        "ctx-1",
        "CI/CD Alerts - Pipeline notifications",
      );
      userContextRepo.find.mockResolvedValue([stored]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(stored),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same category"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(llmCoreService.generateText).toHaveBeenCalled();
      expect(result).toEqual({ name: "CI/CD Alerts", contextId: "ctx-1" });
      expect(txRepo.update).toHaveBeenCalledWith(
        { contextId: "ctx-1" },
        expect.objectContaining({
          alternateNames: expect.arrayContaining(["CI/CD Alert"]),
        }),
      );
    });

    it("returns null when LLM says near-duplicate is not the same", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "CI/CD Alerts - Pipeline notifications"),
      ]);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Different"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(result).toBeNull();
      expect(dataSource.transaction).not.toHaveBeenCalled();
    });

    it("returns null and does not throw when LLM call fails", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "CI/CD Alerts"),
      ]);
      llmCoreService.generateText.mockRejectedValue(new Error("LLM timeout"));

      const result = await service.findMatchingFullCategory(
        "user-1",
        "CI/CD Alert",
      );
      expect(result).toBeNull();
    });

    it("does not call LLM for clearly different category names", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "Finance Reports - Invoices and billing"),
      ]);

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Recruitment",
      );
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
      expect(result).toBeNull();
    });

    it("catches semantic paraphrase via embedding similarity + LLM (full)", async () => {
      const stored = makeUserContext("ctx-1", "QA Passed - Test results");
      userContextRepo.find.mockResolvedValue([stored]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(stored),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) =>
            text === "QA Passed" || text === "Tests Green" ? [1, 0] : [0, 1],
          ),
        ),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same outcome"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Tests Green",
      );
      expect(embeddingService.embed).toHaveBeenCalled();
      expect(result).toEqual({ name: "QA Passed", contextId: "ctx-1" });
      expect(txRepo.update).toHaveBeenCalledWith(
        { contextId: "ctx-1" },
        expect.objectContaining({
          alternateNames: expect.arrayContaining(["Tests Green"]),
        }),
      );
    });

    it("does not embed-match when similarity is below threshold", async () => {
      userContextRepo.find.mockResolvedValue([
        makeUserContext("ctx-1", "Finance Reports"),
      ]);
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) => (text === "Tests Green" ? [1, 0] : [0, 1])),
        ),
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Tests Green",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("blocks broad platform catch-all via Phase 4 shared-token check (issue #2065 follow-up)", async () => {
      const stored = makeUserContext(
        "ctx-github-prs",
        "🐙 GitHub PRs - Pull request notifications",
      );
      const stored2 = makeUserContext(
        "ctx-github-notif",
        "🔔 GitHub Notifications - General GitHub alerts",
      );
      userContextRepo.find.mockResolvedValue([stored, stored2]);
      const txRepo = {
        findOne: jest.fn().mockResolvedValue(stored),
        update: jest.fn().mockResolvedValue({}),
      };
      dataSource.transaction.mockImplementation(
        async (cb: (manager: unknown) => Promise<unknown>) =>
          cb({ getRepository: () => txRepo }),
      );
      // LLM says the broad "Github and Code" is a duplicate of the specific "🐙 GitHub PRs"
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Broad catch-all for GitHub emails"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "Github and Code",
      );
      expect(llmCoreService.generateText).toHaveBeenCalled();
      expect(result).not.toBeNull();
      expect(result?.name).toBe("🐙 GitHub PRs");
    });

    it("allows specific platform sub-category when LLM says not a duplicate", async () => {
      const stored = makeUserContext(
        "ctx-github-prs",
        "🐙 GitHub PRs - Pull request notifications",
      );
      userContextRepo.find.mockResolvedValue([stored]);
      // LLM says "GitHub Releases" is NOT a duplicate of "GitHub PRs"
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Different GitHub sub-categories"}',
      );

      const result = await service.findMatchingFullCategory(
        "user-1",
        "GitHub Releases",
      );
      expect(llmCoreService.generateText).toHaveBeenCalled();
      expect(result).toBeNull();
    });
  });

  describe("findMatchingProtoCategory", () => {
    it("returns null when no active proto categories exist", async () => {
      protoCategoryRepo.find.mockResolvedValue([]);
      const result = await service.findMatchingProtoCategory("user-1", "Foo");
      expect(result).toBeNull();
    });

    it("matches by Levenshtein similarity when LLM confirms duplicate", async () => {
      // Use names that pass Levenshtein but fail containment so the LLM path runs.
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Newsletters",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same category"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Newslters",
      );
      expect(result).toBe(proto);
      expect(llmCoreService.generateText).toHaveBeenCalled();
    });

    it("returns null when Levenshtein matches but LLM rejects the duplicate", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Project A",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Distinct projects"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Project B",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).toHaveBeenCalled();
    });

    it("returns null for clearly different names without calling LLM", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "Finance Reports",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Recruitment",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).not.toHaveBeenCalled();
    });

    it("catches semantic paraphrase via embedding similarity + LLM (proto)", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "QA Passed",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) =>
            text === "QA Passed" || text === "Tests Green" ? [1, 0] : [0, 1],
          ),
        ),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": true, "reasoning": "Same outcome"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Tests Green",
      );
      expect(embeddingService.embed).toHaveBeenCalled();
      expect(result).toBe(proto);
    });

    it("returns null when embedding flags a candidate but LLM rejects it", async () => {
      const proto = Object.assign(new ProtoCategory(), {
        id: "proto-1",
        userId: "user-1",
        name: "QA Passed",
        isPromoted: false,
        emailCount: 2,
      });
      protoCategoryRepo.find.mockResolvedValue([proto]);
      protoCategoryRepo.findOne.mockResolvedValue(null);
      embeddingService.isAvailable.mockReturnValue(true);
      embeddingService.embed.mockImplementation((texts: string[]) =>
        Promise.resolve(
          texts.map((text) =>
            text === "QA Passed" || text === "Tests Green" ? [1, 0] : [0, 1],
          ),
        ),
      );
      llmCoreService.generateText.mockResolvedValue(
        '{"isDuplicate": false, "reasoning": "Different"}',
      );

      const result = await service.findMatchingProtoCategory(
        "user-1",
        "Tests Green",
      );
      expect(result).toBeNull();
      expect(llmCoreService.generateText).toHaveBeenCalled();
    });
  });

  describe("assignThreadToProtoCategory", () => {
    it("throws NotFoundException when proto category not found", async () => {
      (service["emailThreadRepository"].update as jest.Mock).mockResolvedValue(
        {},
      );
      protoCategoryRepo.increment.mockResolvedValue({});
      protoCategoryRepo.findOne.mockResolvedValue(null);

      await expect(
        service.assignThreadToProtoCategory("missing-id", "thread-1"),
      ).rejects.toThrow(NotFoundException);
    });
  });
});
