import { Test, TestingModule } from "@nestjs/testing";
import { getRepositoryToken } from "@nestjs/typeorm";
import { Repository } from "typeorm";

import { CategoryFamily } from "../database/entities/category-family.entity";
import { CategoryRule } from "../database/entities/category-rule.entity";
import { EmailThread } from "../database/entities/email-thread.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { LLMService } from "../llm/llm.service";
import { CategoryConsolidationService } from "./category-consolidation.service";
import { CategoryFamilyService } from "./category-family.service";
import { OTHER_FAMILY } from "./category-family.taxonomy";

interface FakeContext {
  contextId: string;
  contextValue: string;
  familyId: string | null;
  source: Source;
  contextKey: ContextKey;
}

const ctx = (
  contextId: string,
  contextValue: string,
  familyId: string | null,
  source: Source = Source.AUTOGENERATED,
): FakeContext => ({
  contextId,
  contextValue,
  familyId,
  source,
  contextKey: ContextKey.EMAIL_CATEGORY,
});

// FA = GitHub / Pull Requests, FB = Meetings & Calendar, FOTHER = Other family.
const FA = "fa";
const FB = "fb";
const FOTHER = "fother";

describe("CategoryConsolidationService", () => {
  let service: CategoryConsolidationService;
  let contextRepo: jest.Mocked<Repository<UserContext>>;
  let threadRepo: jest.Mocked<Repository<EmailThread>>;
  let ruleRepo: jest.Mocked<Repository<CategoryRule>>;
  let familyRepo: jest.Mocked<Repository<CategoryFamily>>;
  let llmService: { identifyDuplicateCategories: jest.Mock };
  let familyService: { ensureFamiliesForUser: jest.Mock };

  // a1/a2 = exact-name duplicates in DIFFERENT families (App Store Notifications)
  // a3/a4 = semantic duplicates the LLM merges (GitHub PR Updates)
  // a5     = never-used (count 0)               a6 = rarely-used in family fa
  // a7     = rarely-used but in the Other family (must NOT fold)
  // u1     = user-added, empty (must NOT prune) u2 = user-added, tiny (must NOT fold)
  const allContexts: FakeContext[] = [
    ctx("a1", "🚀 App Store Notifications - ios", FA),
    ctx("a2", "📱 App Store Notifications - android", FB),
    ctx("a3", "🔧 GitHub PR Updates - prs", FA),
    ctx("a4", "Pull Request Updates - pr activity", FA),
    ctx("a5", "🗑 Dead Category - never used", FA),
    ctx("a6", "🐛 Tiny Bug Notes - bugs", FA),
    ctx("a7", "🔔 Misc Other - misc", FOTHER),
    ctx("u1", "My Project - mine", null, Source.USER_EDITED),
    ctx("u2", "My Small Topic - mine", FA, Source.USER_EDITED),
  ];

  beforeEach(async () => {
    const threadCountRows = [
      { categoryId: "a1", count: "3" },
      { categoryId: "a2", count: "4" },
      { categoryId: "a3", count: "10" },
      { categoryId: "a4", count: "6" },
      // a5 (0) and u1 (0) absent — never had a thread.
      { categoryId: "a6", count: "2" },
      { categoryId: "a7", count: "1" },
      { categoryId: "u2", count: "1" },
    ];
    const qb = {
      select: jest.fn().mockReturnThis(),
      addSelect: jest.fn().mockReturnThis(),
      where: jest.fn().mockReturnThis(),
      andWhere: jest.fn().mockReturnThis(),
      groupBy: jest.fn().mockReturnThis(),
      getRawMany: jest.fn().mockResolvedValue(threadCountRows),
    };

    contextRepo = {
      find: jest.fn().mockResolvedValue(allContexts),
      delete: jest.fn().mockResolvedValue({ affected: 1 }),
    } as unknown as jest.Mocked<Repository<UserContext>>;

    threadRepo = {
      createQueryBuilder: jest.fn().mockReturnValue(qb),
      update: jest.fn().mockResolvedValue({ affected: 3 }),
    } as unknown as jest.Mocked<Repository<EmailThread>>;

    ruleRepo = {
      delete: jest.fn().mockResolvedValue({ affected: 0 }),
      update: jest.fn().mockResolvedValue({ affected: 0 }),
    } as unknown as jest.Mocked<Repository<CategoryRule>>;

    familyRepo = {
      find: jest.fn().mockResolvedValue([
        { id: FA, name: "GitHub / Pull Requests" },
        { id: FB, name: "Meetings & Calendar" },
        { id: FOTHER, name: OTHER_FAMILY },
      ]),
    } as unknown as jest.Mocked<Repository<CategoryFamily>>;

    llmService = {
      identifyDuplicateCategories: jest.fn().mockResolvedValue([
        {
          canonical: "🔧 GitHub PR Updates",
          members: ["🔧 GitHub PR Updates", "Pull Request Updates"],
        },
      ]),
    };
    familyService = { ensureFamiliesForUser: jest.fn().mockResolvedValue(0) };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        CategoryConsolidationService,
        { provide: getRepositoryToken(UserContext), useValue: contextRepo },
        { provide: getRepositoryToken(EmailThread), useValue: threadRepo },
        { provide: getRepositoryToken(CategoryRule), useValue: ruleRepo },
        { provide: getRepositoryToken(CategoryFamily), useValue: familyRepo },
        { provide: LLMService, useValue: llmService },
        { provide: CategoryFamilyService, useValue: familyService },
      ],
    }).compile();

    service = module.get(CategoryConsolidationService);
  });

  it("merges exact-name duplicates ACROSS families without the LLM", async () => {
    const result = await service.consolidate("u1");

    const exact = result.mergedGroups.find(
      (group) => group.method === "exact-name",
    );
    expect(exact).toBeDefined();
    // a2 (4 threads, has family) wins over a1 (3 threads).
    expect(exact).toMatchObject({
      survivor: "📱 App Store Notifications",
      merged: ["🚀 App Store Notifications"],
    });
    expect(threadRepo.update).toHaveBeenCalledWith(
      { userId: "u1", categoryId: "a1" },
      { categoryId: "a2" },
    );
    expect(contextRepo.delete).toHaveBeenCalledWith("a1");
  });

  it("prunes only auto categories that never had a thread", async () => {
    const result = await service.consolidate("u1");

    expect(result.prunedCategories).toContainEqual({
      name: "🗑 Dead Category",
      reason: "never-used",
    });
    expect(contextRepo.delete).toHaveBeenCalledWith(["a5"]);
    // u1 is user-added + empty → never pruned.
    const deletedIds = contextRepo.delete.mock.calls.flatMap((call) => call[0]);
    expect(deletedIds).not.toContain("u1");
  });

  it("merges LLM-judged semantic duplicates across all families in one call", async () => {
    const result = await service.consolidate("u1");

    expect(llmService.identifyDuplicateCategories).toHaveBeenCalledTimes(1);
    expect(llmService.identifyDuplicateCategories).toHaveBeenCalledWith(
      "all of your categories",
      expect.any(Array),
      undefined,
      "u1",
      true,
    );
    const semantic = result.mergedGroups.find(
      (group) => group.method === "semantic",
    );
    expect(semantic).toMatchObject({
      survivor: "🔧 GitHub PR Updates",
      merged: ["Pull Request Updates"],
    });
    expect(threadRepo.update).toHaveBeenCalledWith(
      { userId: "u1", categoryId: "a4" },
      { categoryId: "a3" },
    );
  });

  it("folds a rarely-used auto category into the largest sibling in its family", async () => {
    const result = await service.consolidate("u1");

    expect(result.prunedCategories).toContainEqual({
      name: "🐛 Tiny Bug Notes",
      reason: "rarely-used",
    });
    // a6 folds into a3 (the largest fa survivor after the semantic merge).
    expect(threadRepo.update).toHaveBeenCalledWith(
      { userId: "u1", categoryId: "a6" },
      { categoryId: "a3" },
    );
  });

  it("never folds Other-family or user-added small categories", async () => {
    const result = await service.consolidate("u1");
    const foldedNames = result.prunedCategories
      .filter((prune) => prune.reason === "rarely-used")
      .map((prune) => prune.name);
    // 🔔 Misc Other is in the Other family; My Small Topic is user-added.
    expect(foldedNames).not.toContain("🔔 Misc Other");
    expect(foldedNames).not.toContain("My Small Topic");
    const survivorNames = result.categories.map((category) => category.name);
    expect(survivorNames).toContain("🔔 Misc Other");
    expect(survivorNames).toContain("My Small Topic");
  });

  it("reports original / consolidated / user-added counts", async () => {
    const result = await service.consolidate("u1");
    // 9 → survivors: a2, a3, a7, u1, u2 = 5
    expect(result.originalCount).toBe(9);
    expect(result.consolidatedCount).toBe(5);
    expect(result.userAddedCount).toBe(2);
  });

  it("returns an empty result when the user has no categories", async () => {
    contextRepo.find = jest.fn().mockResolvedValue([]);
    const result = await service.consolidate("u1");
    expect(result).toEqual({
      originalCount: 0,
      consolidatedCount: 0,
      userAddedCount: 0,
      mergedGroups: [],
      prunedCategories: [],
      categories: [],
    });
    expect(llmService.identifyDuplicateCategories).not.toHaveBeenCalled();
  });

  describe("listNeverUsedCategories", () => {
    it("lists never-used auto categories without deleting anything", async () => {
      const unused = await service.listNeverUsedCategories("u1");
      expect(unused).toEqual([
        { name: "🗑 Dead Category", reason: "never-used" },
      ]);
      expect(contextRepo.delete).not.toHaveBeenCalled();
      expect(ruleRepo.delete).not.toHaveBeenCalled();
      // Rarely-used (a6) is NOT in the never-used preview.
      expect(unused.map((unusedCat) => unusedCat.name)).not.toContain(
        "🐛 Tiny Bug Notes",
      );
    });

    it("excludes empty user-added categories from the preview", async () => {
      const unused = await service.listNeverUsedCategories("u1");
      expect(unused.map((category) => category.name)).not.toContain(
        "My Project",
      );
    });
  });

  describe("pruneNeverUsedCategories", () => {
    it("deletes never-used auto categories and their rules only", async () => {
      const result = await service.pruneNeverUsedCategories("u1");
      expect(result.prunedCount).toBe(1);
      expect(result.prunedCategories).toEqual([
        { name: "🗑 Dead Category", reason: "never-used" },
      ]);
      expect(contextRepo.delete).toHaveBeenCalledWith(["a5"]);
      expect(ruleRepo.delete).toHaveBeenCalledWith({
        userId: "u1",
        categoryId: expect.anything(),
      });
      // Prune-only path never consults the LLM and never folds.
      expect(llmService.identifyDuplicateCategories).not.toHaveBeenCalled();
      expect(threadRepo.update).not.toHaveBeenCalled();
    });

    it("is a no-op when there are no never-used categories", async () => {
      contextRepo.find = jest
        .fn()
        .mockResolvedValue([ctx("a3", "🔧 GitHub PR Updates - x", FA)]);
      const result = await service.pruneNeverUsedCategories("u1");
      expect(result.prunedCount).toBe(0);
      expect(contextRepo.delete).not.toHaveBeenCalled();
    });
  });
});
