import {
  BadRequestException,
  Injectable,
  Logger,
  NotFoundException,
} from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";

import { CategoryFamily } from "../database/entities/category-family.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { assignFamily, OTHER_FAMILY } from "./category-family.taxonomy";

export interface FamilyWithCategories {
  /** null for the synthetic "Other / Uncategorised" group */
  id: string | null;
  name: string;
  displayOrder: number;
  source: Source;
  categories: { contextId: string; name: string }[];
}

/**
 * Manages category families — the coarse level of the category hierarchy.
 *
 * Families are seeded from the keyword taxonomy ({@link assignFamily}) the first
 * time they're needed and whenever new categories appear, then are user-editable
 * (rename, reorder, reassign a category to a different family). Categories with
 * no family fall under a synthetic "Other / Uncategorised" group in the UI.
 */
@Injectable()
export class CategoryFamilyService {
  private readonly logger = new Logger(CategoryFamilyService.name);

  constructor(
    @InjectRepository(CategoryFamily)
    private readonly familyRepository: Repository<CategoryFamily>,
    @InjectRepository(UserContext)
    private readonly contextRepository: Repository<UserContext>,
  ) {}

  /**
   * Ensures every EMAIL_CATEGORY context has a family, creating the families the
   * taxonomy calls for and assigning each unassigned category to its family.
   * Idempotent: existing families are reused (matched by name) and categories
   * the user has already reassigned are left untouched. Returns the number of
   * categories newly assigned.
   */
  async ensureFamiliesForUser(userId: string): Promise<number> {
    const categories = await this.contextRepository.find({
      where: { userId, contextKey: ContextKey.EMAIL_CATEGORY },
    });

    const existing = await this.familyRepository.find({ where: { userId } });
    const familyByName = new Map(existing.map((fam) => [fam.name, fam]));

    // Create any missing families in a single bulk save (avoids N+1 inserts).
    const newFamilyNames = new Set<string>();
    for (const category of categories) {
      if (category.familyId) continue;
      const familyName = assignFamily(category.contextValue);
      if (familyName === OTHER_FAMILY) continue;
      if (!familyByName.has(familyName)) newFamilyNames.add(familyName);
    }

    if (newFamilyNames.size > 0) {
      const newFamilies = Array.from(newFamilyNames).map((name, index) =>
        this.familyRepository.create({
          userId,
          name,
          displayOrder: familyByName.size + index,
          source: Source.AUTOGENERATED,
        }),
      );
      const savedFamilies = await this.familyRepository.save(newFamilies);
      for (const fam of savedFamilies) familyByName.set(fam.name, fam);
    }

    // Assign families and persist all changed categories in a single bulk save.
    let assigned = 0;
    const categoriesToSave: UserContext[] = [];
    for (const category of categories) {
      // Skip categories already assigned (by an earlier seed or by the user).
      if (category.familyId) continue;
      const familyName = assignFamily(category.contextValue);
      // Leave taxonomy-unmatched categories under the synthetic Other group.
      if (familyName === OTHER_FAMILY) continue;

      const family = familyByName.get(familyName);
      if (family) {
        category.familyId = family.id;
        categoriesToSave.push(category);
        assigned += 1;
      }
    }

    if (categoriesToSave.length > 0) {
      await this.contextRepository.save(categoriesToSave);
    }

    if (assigned > 0) {
      this.logger.log(
        `Seeded families for ${userId}: assigned ${assigned} categories`,
      );
    }
    return assigned;
  }

  /**
   * Returns the user's families, each with its categories, plus a synthetic
   * "Other / Uncategorised" group for categories with no family. Ordered by
   * `displayOrder`; the Other group sorts last.
   */
  async getFamiliesWithCategories(
    userId: string,
  ): Promise<FamilyWithCategories[]> {
    const [families, categories] = await Promise.all([
      this.familyRepository.find({
        where: { userId },
        order: { displayOrder: "ASC" },
      }),
      this.contextRepository.find({
        where: { userId, contextKey: ContextKey.EMAIL_CATEGORY },
      }),
    ]);

    const groups = new Map<string | null, FamilyWithCategories>();
    for (const family of families) {
      groups.set(family.id, {
        id: family.id,
        name: family.name,
        displayOrder: family.displayOrder,
        source: family.source,
        categories: [],
      });
    }
    const other: FamilyWithCategories = {
      id: null,
      name: OTHER_FAMILY,
      displayOrder: Number.MAX_SAFE_INTEGER,
      source: Source.AUTOGENERATED,
      categories: [],
    };

    for (const category of categories) {
      const group =
        (category.familyId && groups.get(category.familyId)) || other;
      group.categories.push({
        contextId: category.contextId,
        name: category.contextValue,
      });
    }

    const result = [...groups.values()];
    if (other.categories.length > 0) result.push(other);
    return result.sort((left, right) => left.displayOrder - right.displayOrder);
  }

  /** Moves a category to a different family (or to no family when `familyId` is
   * null). Validates that both belong to the user. */
  async reassignCategory(
    userId: string,
    contextId: string,
    familyId: string | null,
  ): Promise<void> {
    const category = await this.contextRepository.findOne({
      where: { contextId, userId, contextKey: ContextKey.EMAIL_CATEGORY },
    });
    if (!category) throw new NotFoundException("Category not found");

    if (familyId) {
      const family = await this.familyRepository.findOne({
        where: { id: familyId, userId },
      });
      if (!family) throw new NotFoundException("Family not found");
    }

    category.familyId = familyId ?? null;
    await this.contextRepository.save(category);
  }

  /** Renames a family (marks it USER_EDITED). */
  async renameFamily(
    userId: string,
    familyId: string,
    name: string,
  ): Promise<CategoryFamily> {
    const trimmedName = name?.trim();
    if (!trimmedName) {
      throw new BadRequestException("Family name cannot be empty");
    }
    const family = await this.familyRepository.findOne({
      where: { id: familyId, userId },
    });
    if (!family) throw new NotFoundException("Family not found");
    family.name = trimmedName;
    family.source = Source.USER_EDITED;
    return this.familyRepository.save(family);
  }

  /** Creates a new (user-defined) family. */
  async createFamily(userId: string, name: string): Promise<CategoryFamily> {
    const trimmedName = name?.trim();
    if (!trimmedName) {
      throw new BadRequestException("Family name cannot be empty");
    }
    const count = await this.familyRepository.count({ where: { userId } });
    return this.familyRepository.save(
      this.familyRepository.create({
        userId,
        name: trimmedName,
        displayOrder: count,
        source: Source.USER_EDITED,
      }),
    );
  }
}
