import { Test, TestingModule } from "@nestjs/testing";
import { getRepositoryToken } from "@nestjs/typeorm";
import { Repository } from "typeorm";

import { CategoryFamily } from "../database/entities/category-family.entity";
import { CategoryRule } from "../database/entities/category-rule.entity";
import { EmailThread } from "../database/entities/email-thread.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { LLMService } from "../llm/llm.service";
import { CategoryConsolidationService } from "./category-consolidation.service";
import { CategoryFamilyService } from "./category-family.service";

interface FakeContext {
  contextId: string;
  contextValue: string;
  familyId: string | null;
  source: Source;
  contextKey: ContextKey;
}

const ctx = (
  contextId: string,
  contextValue: string,
  familyId: string | null,
  source: Source = Source.AUTOGENERATED,
): FakeContext => ({
  contextId,
  contextValue,
  familyId,
  source,
  contextKey: ContextKey.EMAIL_CATEGORY,
});

describe("CategoryConsolidationService", () => {
  let service: CategoryConsolidationService;
  let contextRepo: jest.Mocked<Repository<UserContext>>;
  let threadRepo: jest.Mocked<Repository<EmailThread>>;
  let ruleRepo: jest.Mocked<Repository<CategoryRule>>;
  let familyRepo: jest.Mocked<Repository<CategoryFamily>>;
  let llmService: { identifyDuplicateCategories: jest.Mock };
  let familyService: { ensureFamiliesForUser: jest.Mock };

  const allContexts: FakeContext[] = [
    ctx("c1", "🔧 GitHub PR Updates - updates", "fa"),
    ctx("c2", "Pull Request Updates - pr activity", "fa"),
    ctx("c3", "🐛 Bug Issues - bugs", "fa"),
    ctx("c4", "📅 Meeting Recaps - notes", "fb"),
    ctx("c5", "🗑 Dead Category - never used", "fa"),
    ctx("c6", "My Project - mine", null, Source.USER_EDITED),
  ];

  // After prune (c5) + merge (c2 into c1): c1, c3, c4, c6 remain.
  const remainingContexts: FakeContext[] = [
    allContexts[0],
    allContexts[2],
    allContexts[3],
    allContexts[5],
  ];

  beforeEach(async () => {
    const threadCountRows = [
      { categoryId: "c1", count: "10" },
      { categoryId: "c2", count: "3" },
      { categoryId: "c3", count: "5" },
      { categoryId: "c4", count: "2" },
      // c5 (0) and c6 (0) intentionally absent — never had a thread.
    ];
    const qb = {
      select: jest.fn().mockReturnThis(),
      addSelect: jest.fn().mockReturnThis(),
      where: jest.fn().mockReturnThis(),
      andWhere: jest.fn().mockReturnThis(),
      groupBy: jest.fn().mockReturnThis(),
      getRawMany: jest.fn().mockResolvedValue(threadCountRows),
    };

    contextRepo = {
      find: jest
        .fn()
        .mockResolvedValueOnce(allContexts)
        .mockResolvedValueOnce(remainingContexts),
      delete: jest.fn().mockResolvedValue({ affected: 1 }),
    } as unknown as jest.Mocked<Repository<UserContext>>;

    threadRepo = {
      createQueryBuilder: jest.fn().mockReturnValue(qb),
      update: jest.fn().mockResolvedValue({ affected: 3 }),
    } as unknown as jest.Mocked<Repository<EmailThread>>;

    ruleRepo = {
      delete: jest.fn().mockResolvedValue({ affected: 0 }),
      update: jest.fn().mockResolvedValue({ affected: 0 }),
    } as unknown as jest.Mocked<Repository<CategoryRule>>;

    familyRepo = {
      find: jest.fn().mockResolvedValue([
        { id: "fa", name: "GitHub / Pull Requests" },
        { id: "fb", name: "Meetings & Calendar" },
      ]),
    } as unknown as jest.Mocked<Repository<CategoryFamily>>;

    llmService = {
      identifyDuplicateCategories: jest.fn().mockResolvedValue([
        {
          canonical: "🔧 GitHub PR Updates",
          members: ["🔧 GitHub PR Updates", "Pull Request Updates"],
        },
      ]),
    };
    familyService = { ensureFamiliesForUser: jest.fn().mockResolvedValue(0) };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        CategoryConsolidationService,
        { provide: getRepositoryToken(UserContext), useValue: contextRepo },
        { provide: getRepositoryToken(EmailThread), useValue: threadRepo },
        { provide: getRepositoryToken(CategoryRule), useValue: ruleRepo },
        { provide: getRepositoryToken(CategoryFamily), useValue: familyRepo },
        { provide: LLMService, useValue: llmService },
        { provide: CategoryFamilyService, useValue: familyService },
      ],
    }).compile();

    service = module.get(CategoryConsolidationService);
  });

  it("prunes only auto-generated categories that never had a thread", async () => {
    const result = await service.consolidate("u1");

    expect(result.prunedCategories).toEqual([
      { name: "🗑 Dead Category", reason: "never-used" },
    ]);
    // c5 deleted during prune (and not the empty USER_EDITED c6).
    expect(contextRepo.delete).toHaveBeenCalledWith(["c5"]);
    // Its rules are removed too.
    expect(ruleRepo.delete).toHaveBeenCalledWith({
      userId: "u1",
      categoryId: expect.anything(),
    });
  });

  it("does NOT prune empty user-added categories", async () => {
    await service.consolidate("u1");
    const deletedIds = contextRepo.delete.mock.calls.flatMap((call) => call[0]);
    expect(deletedIds).not.toContain("c6");
  });

  it("merges true duplicates within a family, re-pointing threads and rules", async () => {
    const result = await service.consolidate("u1");

    expect(result.mergedGroups).toEqual([
      {
        survivor: "🔧 GitHub PR Updates",
        merged: ["Pull Request Updates"],
        family: "GitHub / Pull Requests",
        threadsReassigned: 3,
      },
    ]);
    // Loser c2's threads re-pointed to survivor c1.
    expect(threadRepo.update).toHaveBeenCalledWith(
      { userId: "u1", categoryId: "c2" },
      { categoryId: "c1" },
    );
    // Loser c2's rules re-pointed + renamed to survivor.
    expect(ruleRepo.update).toHaveBeenCalledWith(
      { userId: "u1", categoryId: "c2" },
      { categoryId: "c1", categoryName: "🔧 GitHub PR Updates" },
    );
    // Loser context deleted.
    expect(contextRepo.delete).toHaveBeenCalledWith("c2");
  });

  it("only asks the LLM about families with 2+ surviving categories", async () => {
    await service.consolidate("u1");
    // Family fa (3 cats after prune) is checked; family fb (1 cat) is not.
    expect(llmService.identifyDuplicateCategories).toHaveBeenCalledTimes(1);
    expect(llmService.identifyDuplicateCategories).toHaveBeenCalledWith(
      "GitHub / Pull Requests",
      expect.arrayContaining([
        expect.objectContaining({ name: "🔧 GitHub PR Updates" }),
      ]),
      undefined,
      "u1",
    );
  });

  it("reports the surviving category count", async () => {
    const result = await service.consolidate("u1");
    expect(result.originalCount).toBe(6);
    expect(result.consolidatedCount).toBe(4);
    expect(result.userAddedCount).toBe(1);
  });

  it("returns an empty result when the user has no categories", async () => {
    contextRepo.find = jest.fn().mockResolvedValue([]);
    const result = await service.consolidate("u1");
    expect(result).toEqual({
      originalCount: 0,
      consolidatedCount: 0,
      userAddedCount: 0,
      mergedGroups: [],
      prunedCategories: [],
      categories: [],
    });
    expect(llmService.identifyDuplicateCategories).not.toHaveBeenCalled();
  });

  describe("listNeverUsedCategories", () => {
    it("lists never-used auto categories without deleting anything", async () => {
      const unused = await service.listNeverUsedCategories("u1");
      expect(unused).toEqual([
        { name: "🗑 Dead Category", reason: "never-used" },
      ]);
      expect(contextRepo.delete).not.toHaveBeenCalled();
      expect(ruleRepo.delete).not.toHaveBeenCalled();
    });

    it("excludes empty user-added categories from the preview", async () => {
      const unused = await service.listNeverUsedCategories("u1");
      expect(unused.map((category) => category.name)).not.toContain(
        "My Project",
      );
    });
  });

  describe("pruneNeverUsedCategories", () => {
    it("deletes never-used auto categories and their rules", async () => {
      const result = await service.pruneNeverUsedCategories("u1");
      expect(result).toEqual({
        originalCount: 6,
        prunedCount: 1,
        remainingCount: 5,
        prunedCategories: [{ name: "🗑 Dead Category", reason: "never-used" }],
      });
      expect(contextRepo.delete).toHaveBeenCalledWith(["c5"]);
      expect(ruleRepo.delete).toHaveBeenCalledWith({
        userId: "u1",
        categoryId: expect.anything(),
      });
      // Never merges — the LLM is not consulted by the prune-only path.
      expect(llmService.identifyDuplicateCategories).not.toHaveBeenCalled();
    });

    it("is a no-op when there are no never-used categories", async () => {
      contextRepo.find = jest
        .fn()
        .mockResolvedValue([ctx("c1", "🔧 GitHub PR Updates - x", "fa")]);
      // c1 has threads (count 10 from the shared mock).
      const result = await service.pruneNeverUsedCategories("u1");
      expect(result.prunedCount).toBe(0);
      expect(contextRepo.delete).not.toHaveBeenCalled();
    });
  });
});
