import { NotFoundException } from "@nestjs/common";
import { Test, TestingModule } from "@nestjs/testing";
import { getRepositoryToken } from "@nestjs/typeorm";

import { CategoryFamily } from "../database/entities/category-family.entity";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { CategoryFamilyService } from "./category-family.service";
import { OTHER_FAMILY } from "./category-family.taxonomy";

const USER = "user-1";

function makeCategory(overrides: Partial<UserContext> = {}): UserContext {
  return {
    contextId: "ctx-1",
    userId: USER,
    contextKey: ContextKey.EMAIL_CATEGORY,
    contextValue: "🔧 GitHub PR Updates - human-sent PR notifications",
    familyId: null,
    ...overrides,
  } as UserContext;
}

function withGeneratedIds(families: CategoryFamily[]): CategoryFamily[] {
  return families.map((family, index) => ({
    ...family,
    id: `fam-${index + 1}`,
  }));
}

describe("CategoryFamilyService", () => {
  let service: CategoryFamilyService;
  const familyRepo = {
    find: jest.fn(),
    findOne: jest.fn(),
    create: jest.fn((entity) => entity),
    save: jest.fn(),
    count: jest.fn(),
  };
  const contextRepo = { find: jest.fn(), findOne: jest.fn(), save: jest.fn() };

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        CategoryFamilyService,
        { provide: getRepositoryToken(CategoryFamily), useValue: familyRepo },
        { provide: getRepositoryToken(UserContext), useValue: contextRepo },
      ],
    }).compile();
    service = module.get(CategoryFamilyService);
    jest.clearAllMocks();
  });

  describe("ensureFamiliesForUser", () => {
    it("creates the taxonomy family and assigns an unassigned category", async () => {
      contextRepo.find.mockResolvedValue([makeCategory()]);
      familyRepo.find.mockResolvedValue([]);
      familyRepo.save.mockImplementation(async (fams) =>
        withGeneratedIds(fams),
      );
      contextRepo.save.mockImplementation(async (ctx) => ctx);

      const assigned = await service.ensureFamiliesForUser(USER);

      expect(assigned).toBe(1);
      expect(familyRepo.save).toHaveBeenCalledWith([
        expect.objectContaining({
          name: "GitHub / Pull Requests",
          userId: USER,
        }),
      ]);
      expect(contextRepo.save).toHaveBeenCalledWith([
        expect.objectContaining({ familyId: "fam-1" }),
      ]);
    });

    it("skips categories that already have a family", async () => {
      contextRepo.find.mockResolvedValue([makeCategory({ familyId: "fam-x" })]);
      familyRepo.find.mockResolvedValue([]);

      const assigned = await service.ensureFamiliesForUser(USER);

      expect(assigned).toBe(0);
      expect(contextRepo.save).not.toHaveBeenCalled();
    });

    it("reuses an existing family instead of creating a duplicate", async () => {
      contextRepo.find.mockResolvedValue([
        makeCategory({ contextId: "c1" }),
        makeCategory({
          contextId: "c2",
          contextValue: "🤖 GitHub Bot PR Updates - bot PRs",
        }),
      ]);
      familyRepo.find.mockResolvedValue([
        {
          id: "fam-1",
          userId: USER,
          name: "GitHub / Pull Requests",
        } as CategoryFamily,
      ]);
      contextRepo.save.mockImplementation(async (ctx) => ctx);

      const assigned = await service.ensureFamiliesForUser(USER);

      expect(assigned).toBe(2);
      // family already existed, so no new one is created
      expect(familyRepo.save).not.toHaveBeenCalled();
    });

    it("leaves taxonomy-unmatched categories unassigned", async () => {
      contextRepo.find.mockResolvedValue([
        makeCategory({ contextValue: "Something totally unmatched xyz" }),
      ]);
      familyRepo.find.mockResolvedValue([]);

      const assigned = await service.ensureFamiliesForUser(USER);

      expect(assigned).toBe(0);
    });
  });

  describe("getFamiliesWithCategories", () => {
    it("groups categories under their family and collects orphans in Other", async () => {
      familyRepo.find.mockResolvedValue([
        {
          id: "fam-1",
          userId: USER,
          name: "GitHub / Pull Requests",
          displayOrder: 0,
          source: Source.AUTOGENERATED,
        } as CategoryFamily,
      ]);
      contextRepo.find.mockResolvedValue([
        makeCategory({ contextId: "c1", familyId: "fam-1" }),
        makeCategory({
          contextId: "c2",
          contextValue: "Newsletters",
          familyId: null,
        }),
      ]);

      const groups = await service.getFamiliesWithCategories(USER);

      const pr = groups.find((group) => group.id === "fam-1");
      const other = groups.find((group) => group.id === null);
      expect(pr?.categories).toHaveLength(1);
      expect(other?.name).toBe(OTHER_FAMILY);
      expect(other?.categories[0].contextId).toBe("c2");
      // Other group sorts last
      expect(groups[groups.length - 1].id).toBeNull();
    });

    it("omits the Other group when every category has a family", async () => {
      familyRepo.find.mockResolvedValue([
        {
          id: "fam-1",
          userId: USER,
          name: "GitHub / Pull Requests",
          displayOrder: 0,
          source: Source.AUTOGENERATED,
        } as CategoryFamily,
      ]);
      contextRepo.find.mockResolvedValue([makeCategory({ familyId: "fam-1" })]);

      const groups = await service.getFamiliesWithCategories(USER);

      expect(groups.every((group) => group.id !== null)).toBe(true);
    });
  });

  describe("reassignCategory", () => {
    it("throws when the category is not the user's", async () => {
      contextRepo.findOne.mockResolvedValue(null);
      await expect(
        service.reassignCategory(USER, "ctx-x", "fam-1"),
      ).rejects.toThrow(NotFoundException);
    });

    it("throws when the target family is not the user's", async () => {
      contextRepo.findOne.mockResolvedValue(makeCategory());
      familyRepo.findOne.mockResolvedValue(null);
      await expect(
        service.reassignCategory(USER, "ctx-1", "fam-x"),
      ).rejects.toThrow(NotFoundException);
    });

    it("updates the category's familyId", async () => {
      const category = makeCategory();
      contextRepo.findOne.mockResolvedValue(category);
      familyRepo.findOne.mockResolvedValue({
        id: "fam-1",
        userId: USER,
      } as CategoryFamily);
      contextRepo.save.mockImplementation(async (ctx) => ctx);

      await service.reassignCategory(USER, "ctx-1", "fam-1");

      expect(category.familyId).toBe("fam-1");
      expect(contextRepo.save).toHaveBeenCalledWith(category);
    });

    it("allows unassigning a category (familyId null)", async () => {
      const category = makeCategory({ familyId: "fam-1" });
      contextRepo.findOne.mockResolvedValue(category);
      contextRepo.save.mockImplementation(async (ctx) => ctx);

      await service.reassignCategory(USER, "ctx-1", null);

      expect(category.familyId).toBeNull();
      expect(familyRepo.findOne).not.toHaveBeenCalled();
    });
  });
});
