import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { UserContext, ContextKey, Source } from '../database/entities/user-context.entity';
import { Email } from '../database/entities/email.entity';
import * as natural from 'natural';

@Injectable()
export class ContextService {
  constructor(
    @InjectRepository(UserContext)
    private contextRepository: Repository<UserContext>,
    @InjectRepository(Email)
    private emailRepository: Repository<Email>,
  ) {}

  async getUserContext(userId: number): Promise<UserContext[]> {
    return this.contextRepository.find({
      where: { userId },
      order: { lastModified: 'DESC' },
    });
  }

  async analyzeAndLearnFromEmails(userId: number): Promise<void> {
    // Get user's sent emails to learn writing style
    const emails = await this.emailRepository.find({
      where: { userId },
      take: 100,
    });

    // Extract common phrases
    const phrases = this.extractCommonPhrases(emails);
    for (const phrase of phrases) {
      await this.createOrUpdateContext(
        userId,
        ContextKey.COMMON_PHRASE,
        phrase,
        Source.AUTOGENERATED,
      );
    }

    // Extract writing tone
    const tone = this.analyzeTone(emails);
    if (tone) {
      await this.createOrUpdateContext(
        userId,
        ContextKey.WRITING_STYLE_TONE,
        tone,
        Source.AUTOGENERATED,
      );
    }

    // Extract project names and colleague names from received emails
    const receivedEmails = await this.emailRepository
      .createQueryBuilder('email')
      .where('email.userId = :userId', { userId })
      .andWhere('email.from IS NOT NULL')
      .getMany();

    const colleagues = new Set<string>();
    receivedEmails.forEach((email) => {
      if (email.fromName) {
        colleagues.add(email.fromName);
      }
    });

    for (const colleague of Array.from(colleagues).slice(0, 20)) {
      await this.createOrUpdateContext(
        userId,
        ContextKey.COLLEAGUE_NAME,
        colleague,
        Source.AUTOGENERATED,
      );
    }
  }

  private extractCommonPhrases(emails: Email[]): string[] {
    const phrases = new Map<string, number>();
    const tokenizer = new natural.WordTokenizer();

    emails.forEach((email) => {
      const tokens = tokenizer.tokenize(email.body?.toLowerCase() || '') || [];
      for (let i = 0; i < tokens.length - 2; i++) {
        const phrase = `${tokens[i]} ${tokens[i + 1]} ${tokens[i + 2]}`;
        phrases.set(phrase, (phrases.get(phrase) || 0) + 1);
      }
    });

    return Array.from(phrases.entries())
      .filter(([, count]) => count >= 3)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10)
      .map(([phrase]) => phrase);
  }

  private analyzeTone(emails: Email[]): string {
    const formalWords = ['please', 'thank you', 'regards', 'sincerely', 'respectfully'];
    const casualWords = ['hey', 'thanks', 'cheers', 'yep', 'nope'];
    
    let formalCount = 0;
    let casualCount = 0;

    emails.forEach((email) => {
      const body = (email.body || '').toLowerCase();
      formalWords.forEach((word) => {
        if (body.includes(word)) formalCount++;
      });
      casualWords.forEach((word) => {
        if (body.includes(word)) casualCount++;
      });
    });

    if (formalCount > casualCount * 1.5) return 'formal';
    if (casualCount > formalCount * 1.5) return 'casual';
    return 'professional';
  }

  async createOrUpdateContext(
    userId: number,
    contextKey: ContextKey,
    contextValue: string,
    source: Source,
  ): Promise<UserContext> {
    const existing = await this.contextRepository.findOne({
      where: { userId, contextKey, contextValue },
    });

    if (existing) {
      existing.lastModified = new Date();
      if (source === Source.USER_EDITED) {
        existing.source = Source.USER_EDITED;
      }
      return this.contextRepository.save(existing);
    }

    const context = this.contextRepository.create({
      userId,
      contextKey,
      contextValue,
      source,
    });

    return this.contextRepository.save(context);
  }

  async updateContext(
    contextId: number,
    userId: number,
    updates: Partial<UserContext>,
  ): Promise<UserContext> {
    updates.source = Source.USER_EDITED;
    await this.contextRepository.update({ contextId, userId }, updates);
    return this.contextRepository.findOne({ where: { contextId, userId } });
  }

  async deleteContext(contextId: number, userId: number): Promise<void> {
    await this.contextRepository.delete({ contextId, userId });
  }
}

