import { Injectable, Logger } from "@nestjs/common";
import { Inject } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import PgBoss from "pg-boss";
import { In, Repository } from "typeorm";

import { JOB_NAMES } from "../constants/job-names";
import { QUERY_LIMITS } from "../constants/query-limits";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { LLMService } from "../llm/llm.service";
import { getJobPriority } from "../queue/job-priorities";
import { parseCategoryName } from "../utils/category-name.util";
import { ContextCategoryService } from "./context-category.service";

@Injectable()
export class ContextCompressionService {
  private readonly logger = new Logger(ContextCompressionService.name);

  constructor(
    @InjectRepository(UserContext)
    private contextRepository: Repository<UserContext>,
    private llmService: LLMService,
    private categoryService: ContextCategoryService,
    @Inject("PG_BOSS") private boss: PgBoss,
  ) {}

  /**
   * Consolidate existing email categories in the database using LLM.
   * Delegates to ContextCategoryService.
   */
  async consolidateExistingCategories(userId: string): Promise<{
    originalCount: number;
    consolidatedCount: number;
    userAddedCount: number;
    categories: Array<{
      name: string;
      description: string;
      isUserAdded: boolean;
    }>;
  }> {
    return this.categoryService.consolidateExistingCategories(userId);
  }

  /**
   * Generate new categories from emails currently in "Other" category.
   * Delegates to ContextCategoryService.
   */
  async generateCategoriesFromOther(userId: string): Promise<{
    newCategoriesCount: number;
    totalCategoriesCount: number;
    newCategories: Array<{ name: string; description: string }>;
    reclassifyJobsQueued: number;
  }> {
    return this.categoryService.generateCategoriesFromOther(userId);
  }

  private getCompressibleContextKeys(): ContextKey[] {
    return [
      ContextKey.MY_GOALS,
      ContextKey.DONT_CARE,
      ContextKey.WORKING_ON,
      ContextKey.USER_INFO,
      ContextKey.URGENT,
      ContextKey.NOT_IMPORTANT,
      ContextKey.Q_AND_A,
      ContextKey.PROJECT_NAME,
      ContextKey.CURRENT_TOPIC,
      ContextKey.OTHER,
    ];
  }

  async enqueueContextCompressionIfNeeded(userId: string): Promise<boolean> {
    const keys = this.getCompressibleContextKeys();
    const items = await this.contextRepository.find({
      where: { userId, source: Source.AUTOGENERATED, contextKey: In(keys) },
      select: ["contextKey"],
    });

    const keyCounts = new Map<string, number>();
    for (const item of items) {
      keyCounts.set(item.contextKey, (keyCounts.get(item.contextKey) || 0) + 1);
    }

    const tooManyItems =
      items.length > QUERY_LIMITS.CONTEXT_COMPRESSION_TOTAL_THRESHOLD;
    const tooManyPerKey = Array.from(keyCounts.values()).some(
      (count) => count > QUERY_LIMITS.CONTEXT_COMPRESSION_PER_KEY_THRESHOLD,
    );

    if (!tooManyItems && !tooManyPerKey) return false;

    await this.boss.send(
      JOB_NAMES.COMPRESS_CONTEXT,
      { userId, force: false },
      { priority: getJobPriority(JOB_NAMES.ANALYZE_CONTEXT, false) },
    );
    return true;
  }

  async compressUserContext(
    userId: string,
    force = false,
  ): Promise<{
    originalCount: number;
    compressedCount: number;
    changed: boolean;
    notes?: string;
  }> {
    const keys = this.getCompressibleContextKeys();
    const existing = await this.contextRepository.find({
      where: { userId, source: Source.AUTOGENERATED, contextKey: In(keys) },
      order: { lastModified: "DESC" },
    });

    if (existing.length === 0) {
      return { originalCount: 0, compressedCount: 0, changed: false };
    }

    const keyCounts = new Map<string, number>();
    for (const item of existing) {
      keyCounts.set(item.contextKey, (keyCounts.get(item.contextKey) || 0) + 1);
    }

    const shouldCompress =
      force ||
      existing.length > QUERY_LIMITS.CONTEXT_COMPRESSION_TOTAL_THRESHOLD ||
      Array.from(keyCounts.values()).some(
        (count) => count > QUERY_LIMITS.CONTEXT_COMPRESSION_PER_KEY_THRESHOLD,
      );

    if (!shouldCompress) {
      return {
        originalCount: existing.length,
        compressedCount: existing.length,
        changed: false,
      };
    }

    const llmInput = existing.map((item) => ({
      key: item.contextKey,
      value: item.contextValue,
      priority: item.priority,
      explanation: item.explanation,
    }));

    const compressed = await this.llmService.compressUserContext(
      llmInput,
      QUERY_LIMITS.CONTEXT_COMPRESSION_MAX_ITEMS_PER_KEY,
      undefined,
      userId,
    );

    if (!compressed || compressed.items.length === 0) {
      return {
        originalCount: existing.length,
        compressedCount: existing.length,
        changed: false,
      };
    }

    const toSave = compressed.items
      .filter((item) => keys.includes(item.key as ContextKey))
      .filter((item) => item.value && item.value.trim().length > 0);

    if (toSave.length === 0) {
      return {
        originalCount: existing.length,
        compressedCount: existing.length,
        changed: false,
      };
    }

    const existingIds = existing.map((err) => err.contextId);
    if (existingIds.length > 0) {
      await this.contextRepository.delete({ contextId: In(existingIds) });
    }

    // Fix #1258: filter out EMAIL_CATEGORY collisions with user-edited entries.
    const filteredToSave = await this.resolveEmailCategoryCollisions(
      userId,
      toSave,
    );

    await this.saveCompressedEntities(userId, filteredToSave);

    return {
      originalCount: existing.length,
      compressedCount: filteredToSave.length,
      changed: filteredToSave.length !== existing.length,
      notes: compressed.notes,
    };
  }

  /** Persist the final compressed items as new AUTOGENERATED context entities. */
  private async saveCompressedEntities(
    userId: string,
    items: Array<{
      key: string;
      value: string;
      priority?: number;
      explanation?: string;
    }>,
  ): Promise<void> {
    const entities = items.map((item) =>
      this.contextRepository.create({
        userId,
        contextKey: item.key as ContextKey,
        contextValue: item.value,
        source: Source.AUTOGENERATED,
        priority: item.priority,
        explanation: item.explanation,
      }),
    );
    await this.contextRepository.save(entities);
  }

  /**
   * Fix #1258: after deleting auto-generated entries, check against any
   * surviving user-edited EMAIL_CATEGORY rows to prevent name collisions.
   */
  private async resolveEmailCategoryCollisions(
    userId: string,
    items: Array<{
      key: string;
      value: string;
      priority?: number;
      explanation?: string;
    }>,
  ): Promise<
    Array<{
      key: string;
      value: string;
      priority?: number;
      explanation?: string;
    }>
  > {
    const userEditedCategories = await this.contextRepository.find({
      where: {
        userId,
        contextKey: ContextKey.EMAIL_CATEGORY,
        source: Source.USER_EDITED,
      },
      select: ["contextValue"],
    });
    const userEditedNames = new Set(
      userEditedCategories.map((ctx) =>
        parseCategoryName(ctx.contextValue).toLowerCase(),
      ),
    );

    return items.filter((item) => {
      if ((item.key as ContextKey) !== ContextKey.EMAIL_CATEGORY) return true;
      const name = parseCategoryName(item.value).toLowerCase();
      if (userEditedNames.has(name)) {
        this.logger.warn(
          `[compressContextItems] Skipping EMAIL_CATEGORY "${parseCategoryName(item.value)}" for user ${userId} — name collision with user-edited entry`,
        );
        return false;
      }
      return true;
    });
  }
}
