import { Injectable, Logger, Inject } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import {
  UserContext,
  ContextKey,
  Source,
} from "../database/entities/user-context.entity";
import { Email } from "../database/entities/email.entity";
import { EmailThread } from "../database/entities/email-thread.entity";
import { getErrorMessage } from "../types/common";
import { LLMService } from "../llm/llm.service";
import { cleanEmailContent } from "../llm/email-content-cleaner";
import { getJobPriority } from "../queue/job-priorities";
import PgBoss = require("pg-boss");

/**
 * Service for managing email category consolidation and generation.
 * Handles LLM-powered category management operations.
 */
@Injectable()
export class ContextCategoryService {
  private readonly logger = new Logger(ContextCategoryService.name);

  constructor(
    @InjectRepository(UserContext)
    private contextRepository: Repository<UserContext>,
    @InjectRepository(Email)
    private emailRepository: Repository<Email>,
    @InjectRepository(EmailThread)
    private emailThreadRepository: Repository<EmailThread>,
    private llmService: LLMService,
    @Inject("PG_BOSS") private boss: PgBoss,
  ) {}

  /**
   * Consolidate existing email categories in the database using LLM.
   * This is called manually via the "Consolidate Categories" button.
   */
  async consolidateExistingCategories(userId: string): Promise<{
    originalCount: number;
    consolidatedCount: number;
    userAddedCount: number;
    categories: Array<{
      name: string;
      description: string;
      isUserAdded: boolean;
    }>;
  }> {
    this.logger.log(
      `[CATEGORY-CONSOLIDATION] Starting manual consolidation for user ${userId}`,
    );

    // Fetch all existing EMAIL_CATEGORY context items
    const existingCategories = await this.contextRepository.find({
      where: {
        userId,
        contextKey: ContextKey.EMAIL_CATEGORY,
      },
    });

    this.logger.log(
      `[CATEGORY-CONSOLIDATION] Found ${existingCategories.length} existing categories`,
    );

    if (existingCategories.length === 0) {
      return {
        originalCount: 0,
        consolidatedCount: 0,
        userAddedCount: 0,
        categories: [],
      };
    }

    // Separate user-added and auto-generated categories
    const userAddedContexts = existingCategories.filter(
      (ctx) => ctx.source === Source.USER_EDITED,
    );
    const autoGeneratedContexts = existingCategories.filter(
      (ctx) => ctx.source !== Source.USER_EDITED,
    );

    this.logger.log(
      `[CATEGORY-CONSOLIDATION] ${autoGeneratedContexts.length} auto-generated, ${userAddedContexts.length} user-added`,
    );

    // Parse categories into name/description format
    const autoGeneratedCategories = autoGeneratedContexts.map((ctx) => {
      const parts = ctx.contextValue.split(" - ");
      return {
        name: parts[0].trim(),
        description: parts.length > 1 ? parts.slice(1).join(" - ").trim() : "",
      };
    });

    const userAddedCategories = userAddedContexts.map((ctx) => {
      const parts = ctx.contextValue.split(" - ");
      return {
        name: parts[0].trim(),
        description: parts.length > 1 ? parts.slice(1).join(" - ").trim() : "",
      };
    });

    // Call LLM to consolidate
    this.logger.log(
      `[CATEGORY-CONSOLIDATION] Calling LLM to consolidate ${autoGeneratedCategories.length} auto-generated categories...`,
    );

    const consolidatedCategories =
      await this.llmService.consolidateEmailCategories(
        autoGeneratedCategories,
        userAddedCategories,
        undefined,
        userId,
      );

    this.logger.log(
      `[CATEGORY-CONSOLIDATION] LLM returned ${consolidatedCategories.length} consolidated categories`,
    );

    // Delete all existing auto-generated categories
    const autoGeneratedIds = autoGeneratedContexts.map((ctx) => ctx.contextId);
    if (autoGeneratedIds.length > 0) {
      this.logger.log(
        `[CATEGORY-CONSOLIDATION] Deleting ${autoGeneratedIds.length} old auto-generated categories`,
      );
      await this.contextRepository.delete(autoGeneratedIds);
    }

    // Save the new consolidated categories (only auto-generated ones, user-added are preserved)
    const newAutoGeneratedCategories = consolidatedCategories.filter(
      (cat) => !cat.isUserAdded,
    );

    this.logger.log(
      `[CATEGORY-CONSOLIDATION] Saving ${newAutoGeneratedCategories.length} new consolidated categories`,
    );

    for (const cat of newAutoGeneratedCategories) {
      const contextValue = `${cat.name} - ${cat.description}`;
      const newContext = this.contextRepository.create({
        userId,
        contextKey: ContextKey.EMAIL_CATEGORY,
        contextValue,
        source: Source.AUTOGENERATED,
      });
      await this.contextRepository.save(newContext);
    }

    const result = {
      originalCount: existingCategories.length,
      consolidatedCount:
        newAutoGeneratedCategories.length + userAddedContexts.length,
      userAddedCount: userAddedContexts.length,
      categories: consolidatedCategories,
    };

    this.logger.log(
      `[CATEGORY-CONSOLIDATION] Consolidation complete: ${result.originalCount} -> ${result.consolidatedCount} categories (${result.userAddedCount} user-added preserved)`,
    );

    return result;
  }

  /**
   * Generate new categories from emails currently in "Other" category.
   * This analyzes the emails and suggests more specific categories that would better organize them.
   */
  async generateCategoriesFromOther(userId: string): Promise<{
    newCategoriesCount: number;
    totalCategoriesCount: number;
    newCategories: Array<{ name: string; description: string }>;
    reclassifyJobsQueued: number;
  }> {
    this.logger.log(
      `[GENERATE-CATEGORIES] Starting category generation from Other emails for user ${userId}`,
    );

    // Fetch thread IDs in "Other" category (category is encrypted, so filter in code)
    const threads = await this.emailThreadRepository.find({
      where: { userId, isArchived: false },
      select: ["id", "category"],
    });
    const otherThreadIds = threads
      .filter((t) => t.category === "Other" || !t.category)
      .map((t) => t.id);

    if (otherThreadIds.length === 0) {
      return {
        newCategoriesCount: 0,
        totalCategoriesCount: 0,
        newCategories: [],
        reclassifyJobsQueued: 0,
      };
    }

    const otherEmails = await this.emailRepository
      .createQueryBuilder("email")
      .where("email.userId = :userId", { userId })
      .andWhere("email.emailThreadId IN (:...threadIds)", {
        threadIds: otherThreadIds,
      })
      .select([
        "email.id",
        "email.from",
        "email.fromName",
        "email.subject",
        "email.body",
      ])
      .orderBy("email.receivedAt", "DESC")
      .limit(50)
      .getMany();

    this.logger.log(
      `[GENERATE-CATEGORIES] Found ${otherEmails.length} emails in "Other" category`,
    );

    if (otherEmails.length === 0) {
      return {
        newCategoriesCount: 0,
        totalCategoriesCount: 0,
        newCategories: [],
        reclassifyJobsQueued: 0,
      };
    }

    // Fetch existing categories
    const existingCategoryContexts = await this.contextRepository.find({
      where: {
        userId,
        contextKey: ContextKey.EMAIL_CATEGORY,
      },
    });

    const existingCategories = existingCategoryContexts.map((ctx) => {
      const parts = ctx.contextValue.split(" - ");
      return {
        name: parts[0].trim(),
        description: parts.length > 1 ? parts.slice(1).join(" - ").trim() : "",
      };
    });

    this.logger.log(
      `[GENERATE-CATEGORIES] Found ${existingCategories.length} existing categories`,
    );

    // Call LLM to generate new categories
    const newCategories = await this.llmService.generateCategoriesFromOther(
      otherEmails.map((e) => ({
        from: e.from || "",
        fromName: e.fromName,
        subject: e.subject || "",
        body: cleanEmailContent(e.body, null, 300),
      })),
      existingCategories,
      undefined,
      userId,
    );

    if (newCategories.length === 0) {
      this.logger.log(
        `[GENERATE-CATEGORIES] No new categories generated from Other emails`,
      );
      return {
        newCategoriesCount: 0,
        totalCategoriesCount: existingCategories.length,
        newCategories: [],
        reclassifyJobsQueued: 0,
      };
    }

    // Save the new categories
    this.logger.log(
      `[GENERATE-CATEGORIES] Saving ${newCategories.length} new categories`,
    );

    for (const cat of newCategories) {
      const contextValue = `${cat.name} - ${cat.description}`;
      const newContext = this.contextRepository.create({
        userId,
        contextKey: ContextKey.EMAIL_CATEGORY,
        contextValue,
        source: Source.AUTOGENERATED,
      });
      await this.contextRepository.save(newContext);
    }

    // Queue refine-priority jobs for all emails in "Other" to reclassify them
    // with the new categories available
    this.logger.log(
      `[GENERATE-CATEGORIES] Queueing reclassification jobs for ${otherEmails.length} emails in "Other"`,
    );

    let reclassifyJobsQueued = 0;
    for (const email of otherEmails) {
      try {
        await this.boss.send(
          "refine-priority",
          { userId, emailId: email.id, forceRecalculate: true },
          {
            priority: getJobPriority("refine-priority-background", false),
            singletonKey: `refine-priority-reclassify-${email.id}`,
          },
        );
        reclassifyJobsQueued++;
      } catch (error) {
        this.logger.warn(
          `[GENERATE-CATEGORIES] Failed to queue reclassification job for email ${email.id}: ${getErrorMessage(error)}`,
        );
      }
    }

    this.logger.log(
      `[GENERATE-CATEGORIES] Queued ${reclassifyJobsQueued} reclassification jobs`,
    );

    const result = {
      newCategoriesCount: newCategories.length,
      totalCategoriesCount: existingCategories.length + newCategories.length,
      newCategories,
      reclassifyJobsQueued,
    };

    this.logger.log(
      `[GENERATE-CATEGORIES] Category generation complete: ${result.newCategoriesCount} new categories added (total: ${result.totalCategoriesCount}), ${reclassifyJobsQueued} emails queued for reclassification`,
    );

    return result;
  }
}
