import { Test, TestingModule } from "@nestjs/testing";
import { getRepositoryToken } from "@nestjs/typeorm";
import { In } from "typeorm";

import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { LLMService } from "../llm/llm.service";
import { AutoResponderQaService } from "./auto-responder-qa.service";

const mockUserContextRepository = {
  find: jest.fn(),
};

const mockLlmService = {
  generateText: jest.fn(),
};

jest.mock("../llm/prompts", () => ({
  getPrompt: jest.fn().mockReturnValue({
    prompt: "Q&A context: {{qaPairs}}\nQuestion: {{subject}}\n{{body}}",
    systemPrompt: "You are a helpful assistant.",
  }),
  renderPrompt: jest.fn((template: string, vars: Record<string, string>) =>
    template.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? ""),
  ),
  REPLY_PROMPT_IDS: { GENERATE_QA_ANSWER: "generate_qa_answer" },
}));

describe("AutoResponderQaService", () => {
  let service: AutoResponderQaService;

  beforeEach(async () => {
    jest.clearAllMocks();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AutoResponderQaService,
        {
          provide: getRepositoryToken(UserContext),
          useValue: mockUserContextRepository,
        },
        { provide: LLMService, useValue: mockLlmService },
      ],
    }).compile();

    service = module.get<AutoResponderQaService>(AutoResponderQaService);
  });

  it("returns null when only UNAPPROVED Q&A exists", async () => {
    mockUserContextRepository.find.mockResolvedValue([]);

    const result = await service.generateQAAnswer(
      "user1",
      "Subject",
      "Body",
      0.8,
    );

    expect(result).toBeNull();
    expect(mockUserContextRepository.find).toHaveBeenCalledWith(
      expect.objectContaining({
        where: expect.objectContaining({
          source: In([Source.AUTOGENERATED, Source.USER_EDITED]),
        }),
      }),
    );
  });

  it("only queries approved Q&A sources", async () => {
    mockUserContextRepository.find.mockResolvedValue([]);

    await service.generateQAAnswer("user1", "Subject", "Body", 0.8);

    const findCall = mockUserContextRepository.find.mock.calls[0][0];
    expect(findCall.where.contextKey).toBe(ContextKey.Q_AND_A);
    expect(findCall.where.userId).toBe("user1");
  });

  it("generates answer when approved Q&A exists", async () => {
    const approvedContext: Partial<UserContext> = {
      contextId: "ctx1",
      userId: "user1",
      contextKey: ContextKey.Q_AND_A,
      contextValue: "Q: What is your refund policy? | A: 30 days.",
      source: Source.AUTOGENERATED,
    };
    mockUserContextRepository.find.mockResolvedValue([approvedContext]);
    mockLlmService.generateText.mockResolvedValue(
      JSON.stringify({ answer: "30 days.", confidence: 0.95, sources: [1] }),
    );

    const result = await service.generateQAAnswer(
      "user1",
      "Refund question",
      "I want to know your refund policy",
      0.8,
    );

    expect(result).not.toBeNull();
    expect(result?.answer).toBe("30 days.");
    expect(result?.confidence).toBe(0.95);
  });
});
