import { forwardRef, Inject, Injectable, Logger } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { In, Repository } from "typeorm";

import { RATIOS } from "../constants/percentages";
import {
  ContextKey,
  Source,
  UserContext,
} from "../database/entities/user-context.entity";
import { cleanEmailContent } from "../llm/email-content-cleaner";
import { LLMService } from "../llm/llm.service";
import { LLM_OP_GENERATE_QA_ANSWER } from "../llm/llm-operations";
import { getPrompt, renderPrompt, REPLY_PROMPT_IDS } from "../llm/prompts";
import { LLM_CONFIG } from "./auto-responder-constants";
import { QASearchResult } from "./types/auto-responder.types";

/**
 * Service for generating Q&A answers from user context
 */
@Injectable()
export class AutoResponderQaService {
  private readonly logger = new Logger(AutoResponderQaService.name);

  constructor(
    @InjectRepository(UserContext)
    private userContextRepository: Repository<UserContext>,
    @Inject(forwardRef(() => LLMService))
    private llmService: LLMService,
  ) {}

  /**
   * Generate Q&A answer from user's context
   */
  async generateQAAnswer(
    userId: string,
    subject: string,
    body: string,
    minConfidence: number,
  ): Promise<QASearchResult | null> {
    try {
      const qaContexts = await this.userContextRepository.find({
        where: {
          userId,
          contextKey: ContextKey.Q_AND_A,
          source: In([Source.AUTOGENERATED, Source.USER_EDITED]),
        },
      });
      if (qaContexts.length === 0) return null;

      const qaPairs = this.parseQAPairs(qaContexts);
      if (qaPairs.length === 0) return null;

      const promptConfig = getPrompt(REPLY_PROMPT_IDS.GENERATE_QA_ANSWER);
      if (!promptConfig) {
        this.logger.warn("generate_qa_answer prompt not found");
        return null;
      }

      const cleanedBody = cleanEmailContent(
        body,
        null,
        LLM_CONFIG.MAX_BODY_LENGTH_FOR_QA,
      );
      const prompt = renderPrompt(promptConfig.prompt || "", {
        subject,
        body: cleanedBody,
        qaPairs: qaPairs
          .map((qa, i) => `${i + 1}. Q: ${qa.question}\n   A: ${qa.answer}`)
          .join("\n\n"),
      });

      const response = await this.llmService.generateText(
        {
          prompt,
          systemPrompt: promptConfig.systemPrompt || "",
          temperature: RATIOS.THIRTY_PERCENT,
          maxTokens: LLM_CONFIG.QA_MAX_TOKENS,
        },
        undefined,
        userId,
        LLM_OP_GENERATE_QA_ANSWER,
      );

      return this.parseQALLMResponse(response, minConfidence);
    } catch (error) {
      this.logger.error("Failed to generate Q&A answer", error);
      return null;
    }
  }

  private parseQAPairs(
    qaContexts: UserContext[],
  ): Array<{ question: string; answer: string }> {
    const qaPairs: Array<{ question: string; answer: string }> = [];
    for (const ctx of qaContexts) {
      try {
        const parsed = JSON.parse(ctx.contextValue);
        if (parsed.question && parsed.answer) {
          qaPairs.push(parsed);
        }
      } catch {
        const match = ctx.contextValue.match(/Q:\s*(.*?)\s*A:\s*(.*)/is);
        if (match) {
          qaPairs.push({ question: match[1].trim(), answer: match[2].trim() });
        }
      }
    }
    return qaPairs;
  }

  private parseQALLMResponse(
    response: string,
    minConfidence: number,
  ): QASearchResult | null {
    try {
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        if (parsed.confidence >= minConfidence && parsed.answer) {
          return {
            answer: parsed.answer,
            confidence: parsed.confidence,
            sources: parsed.sources || [],
          };
        }
      }
    } catch (parseError) {
      this.logger.warn("Failed to parse Q&A response", parseError);
    }
    return null;
  }
}
